// Code generated by ent, DO NOT EDIT.

package groupbuyactivity

import (
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the groupbuyactivity type in the database.
	Label = "group_buy_activity"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldActivityID holds the string denoting the activity_id field in the database.
	FieldActivityID = "activity_id"
	// FieldActivityName holds the string denoting the activity_name field in the database.
	FieldActivityName = "activity_name"
	// FieldDiscountID holds the string denoting the discount_id field in the database.
	FieldDiscountID = "discount_id"
	// FieldGroupType holds the string denoting the group_type field in the database.
	FieldGroupType = "group_type"
	// FieldTargetCount holds the string denoting the target_count field in the database.
	FieldTargetCount = "target_count"
	// FieldValidTime holds the string denoting the valid_time field in the database.
	FieldValidTime = "valid_time"
	// FieldTagID holds the string denoting the tag_id field in the database.
	FieldTagID = "tag_id"
	// FieldActivityState holds the string denoting the activity_state field in the database.
	FieldActivityState = "activity_state"
	// Table holds the table name of the groupbuyactivity in the database.
	Table = "group_buy_activities"
)

// Columns holds all SQL columns for groupbuyactivity fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldActivityID,
	FieldActivityName,
	FieldDiscountID,
	FieldGroupType,
	FieldTargetCount,
	FieldValidTime,
	FieldTagID,
	FieldActivityState,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ActivityIDValidator is a validator for the "activity_id" field. It is called by the builders before save.
	ActivityIDValidator func(string) error
	// ActivityNameValidator is a validator for the "activity_name" field. It is called by the builders before save.
	ActivityNameValidator func(string) error
	// DiscountIDValidator is a validator for the "discount_id" field. It is called by the builders before save.
	DiscountIDValidator func(string) error
	// DefaultGroupType holds the default value on creation for the "group_type" field.
	DefaultGroupType int32
	// DefaultTargetCount holds the default value on creation for the "target_count" field.
	DefaultTargetCount int32
	// DefaultValidTime holds the default value on creation for the "valid_time" field.
	DefaultValidTime int32
	// TagIDValidator is a validator for the "tag_id" field. It is called by the builders before save.
	TagIDValidator func(string) error
	// DefaultActivityState holds the default value on creation for the "activity_state" field.
	DefaultActivityState int32
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the GroupBuyActivity queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByActivityID orders the results by the activity_id field.
func ByActivityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActivityID, opts...).ToFunc()
}

// ByActivityName orders the results by the activity_name field.
func ByActivityName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActivityName, opts...).ToFunc()
}

// ByDiscountID orders the results by the discount_id field.
func ByDiscountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDiscountID, opts...).ToFunc()
}

// ByGroupType orders the results by the group_type field.
func ByGroupType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupType, opts...).ToFunc()
}

// ByTargetCount orders the results by the target_count field.
func ByTargetCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetCount, opts...).ToFunc()
}

// ByValidTime orders the results by the valid_time field.
func ByValidTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValidTime, opts...).ToFunc()
}

// ByTagID orders the results by the tag_id field.
func ByTagID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTagID, opts...).ToFunc()
}

// ByActivityState orders the results by the activity_state field.
func ByActivityState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActivityState, opts...).ToFunc()
}
