// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SeckillActivitiesColumns holds the columns for the "seckill_activities" table.
	SeckillActivitiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "activity_id", Type: field.TypeString, Unique: true, Size: 32},
		{Name: "activity_name", Type: field.TypeString, Size: 64},
		{Name: "sku_id", Type: field.TypeString, Size: 32},
		{Name: "total_count", Type: field.TypeInt32, Default: 0},
		{Name: "limit_count", Type: field.TypeInt32, Default: 1},
		{Name: "activity_state", Type: field.TypeInt32, Default: 0},
		{Name: "start_time", Type: field.TypeTime},
		{Name: "end_time", Type: field.TypeTime},
	}
	// SeckillActivitiesTable holds the schema information for the "seckill_activities" table.
	SeckillActivitiesTable = &schema.Table{
		Name:       "seckill_activities",
		Columns:    SeckillActivitiesColumns,
		PrimaryKey: []*schema.Column{SeckillActivitiesColumns[0]},
	}
	// SeckillOrdersColumns holds the columns for the "seckill_orders" table.
	SeckillOrdersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "order_id", Type: field.TypeString, Unique: true, Size: 32},
		{Name: "activity_id", Type: field.TypeString, Size: 32},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "sku_id", Type: field.TypeString, Size: 32},
		{Name: "order_state", Type: field.TypeInt32, Default: 0},
		{Name: "order_time", Type: field.TypeTime},
		{Name: "pay_time", Type: field.TypeTime, Nullable: true},
	}
	// SeckillOrdersTable holds the schema information for the "seckill_orders" table.
	SeckillOrdersTable = &schema.Table{
		Name:       "seckill_orders",
		Columns:    SeckillOrdersColumns,
		PrimaryKey: []*schema.Column{SeckillOrdersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SeckillActivitiesTable,
		SeckillOrdersTable,
	}
)

func init() {
}
