// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// LotteryActivity is the predicate function for lotteryactivity builders.
type LotteryActivity func(*sql.Selector)

// LotteryOrder is the predicate function for lotteryorder builders.
type LotteryOrder func(*sql.Selector)

// LotteryStrategy is the predicate function for lotterystrategy builders.
type LotteryStrategy func(*sql.Selector)

// StrategyAward is the predicate function for strategyaward builders.
type StrategyAward func(*sql.Selector)
