// Code generated by ent, DO NOT EDIT.

package notifytask

import (
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the notifytask type in the database.
	Label = "notify_task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldTaskID holds the string denoting the task_id field in the database.
	FieldTaskID = "task_id"
	// FieldNotifyType holds the string denoting the notify_type field in the database.
	FieldNotifyType = "notify_type"
	// FieldNotifyStatus holds the string denoting the notify_status field in the database.
	FieldNotifyStatus = "notify_status"
	// FieldNotifyURL holds the string denoting the notify_url field in the database.
	FieldNotifyURL = "notify_url"
	// FieldNotifyData holds the string denoting the notify_data field in the database.
	FieldNotifyData = "notify_data"
	// FieldUUID holds the string denoting the uuid field in the database.
	FieldUUID = "uuid"
	// FieldRetryCount holds the string denoting the retry_count field in the database.
	FieldRetryCount = "retry_count"
	// FieldMaxRetry holds the string denoting the max_retry field in the database.
	FieldMaxRetry = "max_retry"
	// FieldNextTime holds the string denoting the next_time field in the database.
	FieldNextTime = "next_time"
	// Table holds the table name of the notifytask in the database.
	Table = "notify_tasks"
)

// Columns holds all SQL columns for notifytask fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldTaskID,
	FieldNotifyType,
	FieldNotifyStatus,
	FieldNotifyURL,
	FieldNotifyData,
	FieldUUID,
	FieldRetryCount,
	FieldMaxRetry,
	FieldNextTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TaskIDValidator is a validator for the "task_id" field. It is called by the builders before save.
	TaskIDValidator func(string) error
	// NotifyTypeValidator is a validator for the "notify_type" field. It is called by the builders before save.
	NotifyTypeValidator func(string) error
	// DefaultNotifyStatus holds the default value on creation for the "notify_status" field.
	DefaultNotifyStatus int32
	// NotifyURLValidator is a validator for the "notify_url" field. It is called by the builders before save.
	NotifyURLValidator func(string) error
	// UUIDValidator is a validator for the "uuid" field. It is called by the builders before save.
	UUIDValidator func(string) error
	// DefaultRetryCount holds the default value on creation for the "retry_count" field.
	DefaultRetryCount int32
	// DefaultMaxRetry holds the default value on creation for the "max_retry" field.
	DefaultMaxRetry int32
	// DefaultNextTime holds the default value on creation for the "next_time" field.
	DefaultNextTime int64
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the NotifyTask queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTaskID orders the results by the task_id field.
func ByTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskID, opts...).ToFunc()
}

// ByNotifyType orders the results by the notify_type field.
func ByNotifyType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotifyType, opts...).ToFunc()
}

// ByNotifyStatus orders the results by the notify_status field.
func ByNotifyStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotifyStatus, opts...).ToFunc()
}

// ByNotifyURL orders the results by the notify_url field.
func ByNotifyURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotifyURL, opts...).ToFunc()
}

// ByNotifyData orders the results by the notify_data field.
func ByNotifyData(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotifyData, opts...).ToFunc()
}

// ByUUID orders the results by the uuid field.
func ByUUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUUID, opts...).ToFunc()
}

// ByRetryCount orders the results by the retry_count field.
func ByRetryCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetryCount, opts...).ToFunc()
}

// ByMaxRetry orders the results by the max_retry field.
func ByMaxRetry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxRetry, opts...).ToFunc()
}

// ByNextTime orders the results by the next_time field.
func ByNextTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextTime, opts...).ToFunc()
}
