// Code generated by ent, DO NOT EDIT.

package lotteryactivity

import (
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the lotteryactivity type in the database.
	Label = "lottery_activity"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldActivityID holds the string denoting the activity_id field in the database.
	FieldActivityID = "activity_id"
	// FieldActivityName holds the string denoting the activity_name field in the database.
	FieldActivityName = "activity_name"
	// FieldStrategyID holds the string denoting the strategy_id field in the database.
	FieldStrategyID = "strategy_id"
	// FieldActivityState holds the string denoting the activity_state field in the database.
	FieldActivityState = "activity_state"
	// Table holds the table name of the lotteryactivity in the database.
	Table = "lottery_activities"
)

// Columns holds all SQL columns for lotteryactivity fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldActivityID,
	FieldActivityName,
	FieldStrategyID,
	FieldActivityState,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ActivityIDValidator is a validator for the "activity_id" field. It is called by the builders before save.
	ActivityIDValidator func(string) error
	// ActivityNameValidator is a validator for the "activity_name" field. It is called by the builders before save.
	ActivityNameValidator func(string) error
	// StrategyIDValidator is a validator for the "strategy_id" field. It is called by the builders before save.
	StrategyIDValidator func(string) error
	// DefaultActivityState holds the default value on creation for the "activity_state" field.
	DefaultActivityState int32
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the LotteryActivity queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByActivityID orders the results by the activity_id field.
func ByActivityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActivityID, opts...).ToFunc()
}

// ByActivityName orders the results by the activity_name field.
func ByActivityName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActivityName, opts...).ToFunc()
}

// ByStrategyID orders the results by the strategy_id field.
func ByStrategyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStrategyID, opts...).ToFunc()
}

// ByActivityState orders the results by the activity_state field.
func ByActivityState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActivityState, opts...).ToFunc()
}
