// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"github.com/marketing-platform/internal/seckill/data/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/marketing-platform/internal/seckill/data/ent/seckillactivity"
	"github.com/marketing-platform/internal/seckill/data/ent/seckillorder"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// SeckillActivity is the client for interacting with the SeckillActivity builders.
	SeckillActivity *SeckillActivityClient
	// SeckillOrder is the client for interacting with the SeckillOrder builders.
	SeckillOrder *SeckillOrderClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.SeckillActivity = NewSeckillActivityClient(c.config)
	c.SeckillOrder = NewSeckillOrderClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		SeckillActivity: NewSeckillActivityClient(cfg),
		SeckillOrder:    NewSeckillOrderClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		SeckillActivity: NewSeckillActivityClient(cfg),
		SeckillOrder:    NewSeckillOrderClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		SeckillActivity.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.SeckillActivity.Use(hooks...)
	c.SeckillOrder.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.SeckillActivity.Intercept(interceptors...)
	c.SeckillOrder.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *SeckillActivityMutation:
		return c.SeckillActivity.mutate(ctx, m)
	case *SeckillOrderMutation:
		return c.SeckillOrder.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// SeckillActivityClient is a client for the SeckillActivity schema.
type SeckillActivityClient struct {
	config
}

// NewSeckillActivityClient returns a client for the SeckillActivity from the given config.
func NewSeckillActivityClient(c config) *SeckillActivityClient {
	return &SeckillActivityClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `seckillactivity.Hooks(f(g(h())))`.
func (c *SeckillActivityClient) Use(hooks ...Hook) {
	c.hooks.SeckillActivity = append(c.hooks.SeckillActivity, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `seckillactivity.Intercept(f(g(h())))`.
func (c *SeckillActivityClient) Intercept(interceptors ...Interceptor) {
	c.inters.SeckillActivity = append(c.inters.SeckillActivity, interceptors...)
}

// Create returns a builder for creating a SeckillActivity entity.
func (c *SeckillActivityClient) Create() *SeckillActivityCreate {
	mutation := newSeckillActivityMutation(c.config, OpCreate)
	return &SeckillActivityCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SeckillActivity entities.
func (c *SeckillActivityClient) CreateBulk(builders ...*SeckillActivityCreate) *SeckillActivityCreateBulk {
	return &SeckillActivityCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SeckillActivityClient) MapCreateBulk(slice any, setFunc func(*SeckillActivityCreate, int)) *SeckillActivityCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SeckillActivityCreateBulk{err: fmt.Errorf("calling to SeckillActivityClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SeckillActivityCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SeckillActivityCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SeckillActivity.
func (c *SeckillActivityClient) Update() *SeckillActivityUpdate {
	mutation := newSeckillActivityMutation(c.config, OpUpdate)
	return &SeckillActivityUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SeckillActivityClient) UpdateOne(_m *SeckillActivity) *SeckillActivityUpdateOne {
	mutation := newSeckillActivityMutation(c.config, OpUpdateOne, withSeckillActivity(_m))
	return &SeckillActivityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SeckillActivityClient) UpdateOneID(id uuid.UUID) *SeckillActivityUpdateOne {
	mutation := newSeckillActivityMutation(c.config, OpUpdateOne, withSeckillActivityID(id))
	return &SeckillActivityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SeckillActivity.
func (c *SeckillActivityClient) Delete() *SeckillActivityDelete {
	mutation := newSeckillActivityMutation(c.config, OpDelete)
	return &SeckillActivityDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SeckillActivityClient) DeleteOne(_m *SeckillActivity) *SeckillActivityDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SeckillActivityClient) DeleteOneID(id uuid.UUID) *SeckillActivityDeleteOne {
	builder := c.Delete().Where(seckillactivity.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SeckillActivityDeleteOne{builder}
}

// Query returns a query builder for SeckillActivity.
func (c *SeckillActivityClient) Query() *SeckillActivityQuery {
	return &SeckillActivityQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSeckillActivity},
		inters: c.Interceptors(),
	}
}

// Get returns a SeckillActivity entity by its id.
func (c *SeckillActivityClient) Get(ctx context.Context, id uuid.UUID) (*SeckillActivity, error) {
	return c.Query().Where(seckillactivity.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SeckillActivityClient) GetX(ctx context.Context, id uuid.UUID) *SeckillActivity {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SeckillActivityClient) Hooks() []Hook {
	return c.hooks.SeckillActivity
}

// Interceptors returns the client interceptors.
func (c *SeckillActivityClient) Interceptors() []Interceptor {
	return c.inters.SeckillActivity
}

func (c *SeckillActivityClient) mutate(ctx context.Context, m *SeckillActivityMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SeckillActivityCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SeckillActivityUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SeckillActivityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SeckillActivityDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SeckillActivity mutation op: %q", m.Op())
	}
}

// SeckillOrderClient is a client for the SeckillOrder schema.
type SeckillOrderClient struct {
	config
}

// NewSeckillOrderClient returns a client for the SeckillOrder from the given config.
func NewSeckillOrderClient(c config) *SeckillOrderClient {
	return &SeckillOrderClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `seckillorder.Hooks(f(g(h())))`.
func (c *SeckillOrderClient) Use(hooks ...Hook) {
	c.hooks.SeckillOrder = append(c.hooks.SeckillOrder, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `seckillorder.Intercept(f(g(h())))`.
func (c *SeckillOrderClient) Intercept(interceptors ...Interceptor) {
	c.inters.SeckillOrder = append(c.inters.SeckillOrder, interceptors...)
}

// Create returns a builder for creating a SeckillOrder entity.
func (c *SeckillOrderClient) Create() *SeckillOrderCreate {
	mutation := newSeckillOrderMutation(c.config, OpCreate)
	return &SeckillOrderCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SeckillOrder entities.
func (c *SeckillOrderClient) CreateBulk(builders ...*SeckillOrderCreate) *SeckillOrderCreateBulk {
	return &SeckillOrderCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SeckillOrderClient) MapCreateBulk(slice any, setFunc func(*SeckillOrderCreate, int)) *SeckillOrderCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SeckillOrderCreateBulk{err: fmt.Errorf("calling to SeckillOrderClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SeckillOrderCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SeckillOrderCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SeckillOrder.
func (c *SeckillOrderClient) Update() *SeckillOrderUpdate {
	mutation := newSeckillOrderMutation(c.config, OpUpdate)
	return &SeckillOrderUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SeckillOrderClient) UpdateOne(_m *SeckillOrder) *SeckillOrderUpdateOne {
	mutation := newSeckillOrderMutation(c.config, OpUpdateOne, withSeckillOrder(_m))
	return &SeckillOrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SeckillOrderClient) UpdateOneID(id uuid.UUID) *SeckillOrderUpdateOne {
	mutation := newSeckillOrderMutation(c.config, OpUpdateOne, withSeckillOrderID(id))
	return &SeckillOrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SeckillOrder.
func (c *SeckillOrderClient) Delete() *SeckillOrderDelete {
	mutation := newSeckillOrderMutation(c.config, OpDelete)
	return &SeckillOrderDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SeckillOrderClient) DeleteOne(_m *SeckillOrder) *SeckillOrderDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SeckillOrderClient) DeleteOneID(id uuid.UUID) *SeckillOrderDeleteOne {
	builder := c.Delete().Where(seckillorder.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SeckillOrderDeleteOne{builder}
}

// Query returns a query builder for SeckillOrder.
func (c *SeckillOrderClient) Query() *SeckillOrderQuery {
	return &SeckillOrderQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSeckillOrder},
		inters: c.Interceptors(),
	}
}

// Get returns a SeckillOrder entity by its id.
func (c *SeckillOrderClient) Get(ctx context.Context, id uuid.UUID) (*SeckillOrder, error) {
	return c.Query().Where(seckillorder.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SeckillOrderClient) GetX(ctx context.Context, id uuid.UUID) *SeckillOrder {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SeckillOrderClient) Hooks() []Hook {
	return c.hooks.SeckillOrder
}

// Interceptors returns the client interceptors.
func (c *SeckillOrderClient) Interceptors() []Interceptor {
	return c.inters.SeckillOrder
}

func (c *SeckillOrderClient) mutate(ctx context.Context, m *SeckillOrderMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SeckillOrderCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SeckillOrderUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SeckillOrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SeckillOrderDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SeckillOrder mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		SeckillActivity, SeckillOrder []ent.Hook
	}
	inters struct {
		SeckillActivity, SeckillOrder []ent.Interceptor
	}
)
