// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/marketing-platform/internal/seckill/data/ent/seckillorder"
)

// SeckillOrderCreate is the builder for creating a SeckillOrder entity.
type SeckillOrderCreate struct {
	config
	mutation *SeckillOrderMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *SeckillOrderCreate) SetCreatedAt(v time.Time) *SeckillOrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SeckillOrderCreate) SetNillableCreatedAt(v *time.Time) *SeckillOrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SeckillOrderCreate) SetUpdatedAt(v time.Time) *SeckillOrderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SeckillOrderCreate) SetNillableUpdatedAt(v *time.Time) *SeckillOrderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetOrderID sets the "order_id" field.
func (_c *SeckillOrderCreate) SetOrderID(v string) *SeckillOrderCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetActivityID sets the "activity_id" field.
func (_c *SeckillOrderCreate) SetActivityID(v string) *SeckillOrderCreate {
	_c.mutation.SetActivityID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *SeckillOrderCreate) SetUserID(v int64) *SeckillOrderCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetSkuID sets the "sku_id" field.
func (_c *SeckillOrderCreate) SetSkuID(v string) *SeckillOrderCreate {
	_c.mutation.SetSkuID(v)
	return _c
}

// SetOrderState sets the "order_state" field.
func (_c *SeckillOrderCreate) SetOrderState(v int32) *SeckillOrderCreate {
	_c.mutation.SetOrderState(v)
	return _c
}

// SetNillableOrderState sets the "order_state" field if the given value is not nil.
func (_c *SeckillOrderCreate) SetNillableOrderState(v *int32) *SeckillOrderCreate {
	if v != nil {
		_c.SetOrderState(*v)
	}
	return _c
}

// SetOrderTime sets the "order_time" field.
func (_c *SeckillOrderCreate) SetOrderTime(v time.Time) *SeckillOrderCreate {
	_c.mutation.SetOrderTime(v)
	return _c
}

// SetPayTime sets the "pay_time" field.
func (_c *SeckillOrderCreate) SetPayTime(v time.Time) *SeckillOrderCreate {
	_c.mutation.SetPayTime(v)
	return _c
}

// SetNillablePayTime sets the "pay_time" field if the given value is not nil.
func (_c *SeckillOrderCreate) SetNillablePayTime(v *time.Time) *SeckillOrderCreate {
	if v != nil {
		_c.SetPayTime(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SeckillOrderCreate) SetID(v uuid.UUID) *SeckillOrderCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SeckillOrderCreate) SetNillableID(v *uuid.UUID) *SeckillOrderCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the SeckillOrderMutation object of the builder.
func (_c *SeckillOrderCreate) Mutation() *SeckillOrderMutation {
	return _c.mutation
}

// Save creates the SeckillOrder in the database.
func (_c *SeckillOrderCreate) Save(ctx context.Context) (*SeckillOrder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SeckillOrderCreate) SaveX(ctx context.Context) *SeckillOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SeckillOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SeckillOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SeckillOrderCreate) defaults() {
	if _, ok := _c.mutation.OrderState(); !ok {
		v := seckillorder.DefaultOrderState
		_c.mutation.SetOrderState(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := seckillorder.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SeckillOrderCreate) check() error {
	if _, ok := _c.mutation.OrderID(); !ok {
		return &ValidationError{Name: "order_id", err: errors.New(`ent: missing required field "SeckillOrder.order_id"`)}
	}
	if v, ok := _c.mutation.OrderID(); ok {
		if err := seckillorder.OrderIDValidator(v); err != nil {
			return &ValidationError{Name: "order_id", err: fmt.Errorf(`ent: validator failed for field "SeckillOrder.order_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActivityID(); !ok {
		return &ValidationError{Name: "activity_id", err: errors.New(`ent: missing required field "SeckillOrder.activity_id"`)}
	}
	if v, ok := _c.mutation.ActivityID(); ok {
		if err := seckillorder.ActivityIDValidator(v); err != nil {
			return &ValidationError{Name: "activity_id", err: fmt.Errorf(`ent: validator failed for field "SeckillOrder.activity_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "SeckillOrder.user_id"`)}
	}
	if _, ok := _c.mutation.SkuID(); !ok {
		return &ValidationError{Name: "sku_id", err: errors.New(`ent: missing required field "SeckillOrder.sku_id"`)}
	}
	if v, ok := _c.mutation.SkuID(); ok {
		if err := seckillorder.SkuIDValidator(v); err != nil {
			return &ValidationError{Name: "sku_id", err: fmt.Errorf(`ent: validator failed for field "SeckillOrder.sku_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OrderState(); !ok {
		return &ValidationError{Name: "order_state", err: errors.New(`ent: missing required field "SeckillOrder.order_state"`)}
	}
	if _, ok := _c.mutation.OrderTime(); !ok {
		return &ValidationError{Name: "order_time", err: errors.New(`ent: missing required field "SeckillOrder.order_time"`)}
	}
	return nil
}

func (_c *SeckillOrderCreate) sqlSave(ctx context.Context) (*SeckillOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SeckillOrderCreate) createSpec() (*SeckillOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &SeckillOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(seckillorder.Table, sqlgraph.NewFieldSpec(seckillorder.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(seckillorder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(seckillorder.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.OrderID(); ok {
		_spec.SetField(seckillorder.FieldOrderID, field.TypeString, value)
		_node.OrderID = value
	}
	if value, ok := _c.mutation.ActivityID(); ok {
		_spec.SetField(seckillorder.FieldActivityID, field.TypeString, value)
		_node.ActivityID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(seckillorder.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.SkuID(); ok {
		_spec.SetField(seckillorder.FieldSkuID, field.TypeString, value)
		_node.SkuID = value
	}
	if value, ok := _c.mutation.OrderState(); ok {
		_spec.SetField(seckillorder.FieldOrderState, field.TypeInt32, value)
		_node.OrderState = value
	}
	if value, ok := _c.mutation.OrderTime(); ok {
		_spec.SetField(seckillorder.FieldOrderTime, field.TypeTime, value)
		_node.OrderTime = value
	}
	if value, ok := _c.mutation.PayTime(); ok {
		_spec.SetField(seckillorder.FieldPayTime, field.TypeTime, value)
		_node.PayTime = &value
	}
	return _node, _spec
}

// SeckillOrderCreateBulk is the builder for creating many SeckillOrder entities in bulk.
type SeckillOrderCreateBulk struct {
	config
	err      error
	builders []*SeckillOrderCreate
}

// Save creates the SeckillOrder entities in the database.
func (_c *SeckillOrderCreateBulk) Save(ctx context.Context) ([]*SeckillOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SeckillOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SeckillOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SeckillOrderCreateBulk) SaveX(ctx context.Context) []*SeckillOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SeckillOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SeckillOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
