// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/marketing-platform/internal/seckill/data/ent/predicate"
	"github.com/marketing-platform/internal/seckill/data/ent/seckillorder"
)

// SeckillOrderDelete is the builder for deleting a SeckillOrder entity.
type SeckillOrderDelete struct {
	config
	hooks    []Hook
	mutation *SeckillOrderMutation
}

// Where appends a list predicates to the SeckillOrderDelete builder.
func (_d *SeckillOrderDelete) Where(ps ...predicate.SeckillOrder) *SeckillOrderDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SeckillOrderDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SeckillOrderDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SeckillOrderDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(seckillorder.Table, sqlgraph.NewFieldSpec(seckillorder.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SeckillOrderDeleteOne is the builder for deleting a single SeckillOrder entity.
type SeckillOrderDeleteOne struct {
	_d *SeckillOrderDelete
}

// Where appends a list predicates to the SeckillOrderDelete builder.
func (_d *SeckillOrderDeleteOne) Where(ps ...predicate.SeckillOrder) *SeckillOrderDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SeckillOrderDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{seckillorder.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SeckillOrderDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
