// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"os"
	"time"

	"github.com/redis/go-redis/v9"
	"github.com/marketing-platform/internal/seckill/biz"
	"github.com/marketing-platform/internal/seckill/data"
	"github.com/marketing-platform/internal/seckill/server"
	"github.com/marketing-platform/internal/seckill/service"
)

func InitializeSeckillServer() (*server.SeckillServer, func(), error) {
	mysqlDSN := getEnv("MYSQL_DSN", "root:root@tcp(127.0.0.1:3306)/marketing_seckill?charset=utf8mb4&parseTime=True&loc=Local")
	redisAddr := getEnv("REDIS_ADDR", "127.0.0.1:6379")

	db, err := sql.Open("mysql", mysqlDSN)
	if err != nil {
		return nil, nil, err
	}

	rdb := redis.NewClient(&redis.Options{
		Addr:         redisAddr,
		ReadTimeout:  2 * time.Second,
		WriteTimeout: 2 * time.Second,
	})

	dataLayer := data.NewData(db, rdb, nil, nil, nil)

	activityRepo := data.NewActivityRepo(dataLayer)
	orderRepo := data.NewOrderRepo(dataLayer)
	redisRepo := data.NewRedisRepo(rdb)
	mqRepo := data.NewMQRepo(nil, nil)

	tradeSvc := biz.NewTradeService(orderRepo, redisRepo, mqRepo)

	svc := service.NewSeckillService(tradeSvc, activityRepo)
	seckillServer := server.NewSeckillServer(svc)

	cleanup := func() {
		dataLayer.Close()
	}

	return seckillServer, cleanup, nil
}

func getEnv(key, defaultValue string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}
	return defaultValue
}
