// Code generated by ent, DO NOT EDIT.

package groupbuyteam

import (
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the groupbuyteam type in the database.
	Label = "group_buy_team"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldTeamID holds the string denoting the team_id field in the database.
	FieldTeamID = "team_id"
	// FieldActivityID holds the string denoting the activity_id field in the database.
	FieldActivityID = "activity_id"
	// FieldTargetCount holds the string denoting the target_count field in the database.
	FieldTargetCount = "target_count"
	// FieldCompleteCount holds the string denoting the complete_count field in the database.
	FieldCompleteCount = "complete_count"
	// FieldLockCount holds the string denoting the lock_count field in the database.
	FieldLockCount = "lock_count"
	// FieldTeamState holds the string denoting the team_state field in the database.
	FieldTeamState = "team_state"
	// Table holds the table name of the groupbuyteam in the database.
	Table = "group_buy_teams"
)

// Columns holds all SQL columns for groupbuyteam fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldTeamID,
	FieldActivityID,
	FieldTargetCount,
	FieldCompleteCount,
	FieldLockCount,
	FieldTeamState,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TeamIDValidator is a validator for the "team_id" field. It is called by the builders before save.
	TeamIDValidator func(string) error
	// ActivityIDValidator is a validator for the "activity_id" field. It is called by the builders before save.
	ActivityIDValidator func(string) error
	// DefaultTargetCount holds the default value on creation for the "target_count" field.
	DefaultTargetCount int32
	// DefaultCompleteCount holds the default value on creation for the "complete_count" field.
	DefaultCompleteCount int32
	// DefaultLockCount holds the default value on creation for the "lock_count" field.
	DefaultLockCount int32
	// DefaultTeamState holds the default value on creation for the "team_state" field.
	DefaultTeamState int32
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the GroupBuyTeam queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTeamID orders the results by the team_id field.
func ByTeamID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTeamID, opts...).ToFunc()
}

// ByActivityID orders the results by the activity_id field.
func ByActivityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActivityID, opts...).ToFunc()
}

// ByTargetCount orders the results by the target_count field.
func ByTargetCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetCount, opts...).ToFunc()
}

// ByCompleteCount orders the results by the complete_count field.
func ByCompleteCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompleteCount, opts...).ToFunc()
}

// ByLockCount orders the results by the lock_count field.
func ByLockCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLockCount, opts...).ToFunc()
}

// ByTeamState orders the results by the team_state field.
func ByTeamState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTeamState, opts...).ToFunc()
}
