// Code generated by ent, DO NOT EDIT.

package strategyaward

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/marketing-platform/internal/lottery/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldEQ(FieldUpdatedAt, v))
}

// StrategyID applies equality check predicate on the "strategy_id" field. It's identical to StrategyIDEQ.
func StrategyID(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldEQ(FieldStrategyID, v))
}

// AwardID applies equality check predicate on the "award_id" field. It's identical to AwardIDEQ.
func AwardID(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldEQ(FieldAwardID, v))
}

// AwardName applies equality check predicate on the "award_name" field. It's identical to AwardNameEQ.
func AwardName(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldEQ(FieldAwardName, v))
}

// AwardRate applies equality check predicate on the "award_rate" field. It's identical to AwardRateEQ.
func AwardRate(v float64) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldEQ(FieldAwardRate, v))
}

// AwardCount applies equality check predicate on the "award_count" field. It's identical to AwardCountEQ.
func AwardCount(v int32) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldEQ(FieldAwardCount, v))
}

// RuleModels applies equality check predicate on the "rule_models" field. It's identical to RuleModelsEQ.
func RuleModels(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldEQ(FieldRuleModels, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldNotNull(FieldUpdatedAt))
}

// StrategyIDEQ applies the EQ predicate on the "strategy_id" field.
func StrategyIDEQ(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldEQ(FieldStrategyID, v))
}

// StrategyIDNEQ applies the NEQ predicate on the "strategy_id" field.
func StrategyIDNEQ(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldNEQ(FieldStrategyID, v))
}

// StrategyIDIn applies the In predicate on the "strategy_id" field.
func StrategyIDIn(vs ...string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldIn(FieldStrategyID, vs...))
}

// StrategyIDNotIn applies the NotIn predicate on the "strategy_id" field.
func StrategyIDNotIn(vs ...string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldNotIn(FieldStrategyID, vs...))
}

// StrategyIDGT applies the GT predicate on the "strategy_id" field.
func StrategyIDGT(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldGT(FieldStrategyID, v))
}

// StrategyIDGTE applies the GTE predicate on the "strategy_id" field.
func StrategyIDGTE(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldGTE(FieldStrategyID, v))
}

// StrategyIDLT applies the LT predicate on the "strategy_id" field.
func StrategyIDLT(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldLT(FieldStrategyID, v))
}

// StrategyIDLTE applies the LTE predicate on the "strategy_id" field.
func StrategyIDLTE(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldLTE(FieldStrategyID, v))
}

// StrategyIDContains applies the Contains predicate on the "strategy_id" field.
func StrategyIDContains(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldContains(FieldStrategyID, v))
}

// StrategyIDHasPrefix applies the HasPrefix predicate on the "strategy_id" field.
func StrategyIDHasPrefix(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldHasPrefix(FieldStrategyID, v))
}

// StrategyIDHasSuffix applies the HasSuffix predicate on the "strategy_id" field.
func StrategyIDHasSuffix(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldHasSuffix(FieldStrategyID, v))
}

// StrategyIDEqualFold applies the EqualFold predicate on the "strategy_id" field.
func StrategyIDEqualFold(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldEqualFold(FieldStrategyID, v))
}

// StrategyIDContainsFold applies the ContainsFold predicate on the "strategy_id" field.
func StrategyIDContainsFold(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldContainsFold(FieldStrategyID, v))
}

// AwardIDEQ applies the EQ predicate on the "award_id" field.
func AwardIDEQ(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldEQ(FieldAwardID, v))
}

// AwardIDNEQ applies the NEQ predicate on the "award_id" field.
func AwardIDNEQ(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldNEQ(FieldAwardID, v))
}

// AwardIDIn applies the In predicate on the "award_id" field.
func AwardIDIn(vs ...string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldIn(FieldAwardID, vs...))
}

// AwardIDNotIn applies the NotIn predicate on the "award_id" field.
func AwardIDNotIn(vs ...string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldNotIn(FieldAwardID, vs...))
}

// AwardIDGT applies the GT predicate on the "award_id" field.
func AwardIDGT(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldGT(FieldAwardID, v))
}

// AwardIDGTE applies the GTE predicate on the "award_id" field.
func AwardIDGTE(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldGTE(FieldAwardID, v))
}

// AwardIDLT applies the LT predicate on the "award_id" field.
func AwardIDLT(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldLT(FieldAwardID, v))
}

// AwardIDLTE applies the LTE predicate on the "award_id" field.
func AwardIDLTE(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldLTE(FieldAwardID, v))
}

// AwardIDContains applies the Contains predicate on the "award_id" field.
func AwardIDContains(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldContains(FieldAwardID, v))
}

// AwardIDHasPrefix applies the HasPrefix predicate on the "award_id" field.
func AwardIDHasPrefix(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldHasPrefix(FieldAwardID, v))
}

// AwardIDHasSuffix applies the HasSuffix predicate on the "award_id" field.
func AwardIDHasSuffix(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldHasSuffix(FieldAwardID, v))
}

// AwardIDEqualFold applies the EqualFold predicate on the "award_id" field.
func AwardIDEqualFold(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldEqualFold(FieldAwardID, v))
}

// AwardIDContainsFold applies the ContainsFold predicate on the "award_id" field.
func AwardIDContainsFold(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldContainsFold(FieldAwardID, v))
}

// AwardNameEQ applies the EQ predicate on the "award_name" field.
func AwardNameEQ(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldEQ(FieldAwardName, v))
}

// AwardNameNEQ applies the NEQ predicate on the "award_name" field.
func AwardNameNEQ(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldNEQ(FieldAwardName, v))
}

// AwardNameIn applies the In predicate on the "award_name" field.
func AwardNameIn(vs ...string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldIn(FieldAwardName, vs...))
}

// AwardNameNotIn applies the NotIn predicate on the "award_name" field.
func AwardNameNotIn(vs ...string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldNotIn(FieldAwardName, vs...))
}

// AwardNameGT applies the GT predicate on the "award_name" field.
func AwardNameGT(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldGT(FieldAwardName, v))
}

// AwardNameGTE applies the GTE predicate on the "award_name" field.
func AwardNameGTE(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldGTE(FieldAwardName, v))
}

// AwardNameLT applies the LT predicate on the "award_name" field.
func AwardNameLT(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldLT(FieldAwardName, v))
}

// AwardNameLTE applies the LTE predicate on the "award_name" field.
func AwardNameLTE(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldLTE(FieldAwardName, v))
}

// AwardNameContains applies the Contains predicate on the "award_name" field.
func AwardNameContains(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldContains(FieldAwardName, v))
}

// AwardNameHasPrefix applies the HasPrefix predicate on the "award_name" field.
func AwardNameHasPrefix(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldHasPrefix(FieldAwardName, v))
}

// AwardNameHasSuffix applies the HasSuffix predicate on the "award_name" field.
func AwardNameHasSuffix(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldHasSuffix(FieldAwardName, v))
}

// AwardNameEqualFold applies the EqualFold predicate on the "award_name" field.
func AwardNameEqualFold(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldEqualFold(FieldAwardName, v))
}

// AwardNameContainsFold applies the ContainsFold predicate on the "award_name" field.
func AwardNameContainsFold(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldContainsFold(FieldAwardName, v))
}

// AwardRateEQ applies the EQ predicate on the "award_rate" field.
func AwardRateEQ(v float64) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldEQ(FieldAwardRate, v))
}

// AwardRateNEQ applies the NEQ predicate on the "award_rate" field.
func AwardRateNEQ(v float64) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldNEQ(FieldAwardRate, v))
}

// AwardRateIn applies the In predicate on the "award_rate" field.
func AwardRateIn(vs ...float64) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldIn(FieldAwardRate, vs...))
}

// AwardRateNotIn applies the NotIn predicate on the "award_rate" field.
func AwardRateNotIn(vs ...float64) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldNotIn(FieldAwardRate, vs...))
}

// AwardRateGT applies the GT predicate on the "award_rate" field.
func AwardRateGT(v float64) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldGT(FieldAwardRate, v))
}

// AwardRateGTE applies the GTE predicate on the "award_rate" field.
func AwardRateGTE(v float64) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldGTE(FieldAwardRate, v))
}

// AwardRateLT applies the LT predicate on the "award_rate" field.
func AwardRateLT(v float64) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldLT(FieldAwardRate, v))
}

// AwardRateLTE applies the LTE predicate on the "award_rate" field.
func AwardRateLTE(v float64) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldLTE(FieldAwardRate, v))
}

// AwardCountEQ applies the EQ predicate on the "award_count" field.
func AwardCountEQ(v int32) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldEQ(FieldAwardCount, v))
}

// AwardCountNEQ applies the NEQ predicate on the "award_count" field.
func AwardCountNEQ(v int32) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldNEQ(FieldAwardCount, v))
}

// AwardCountIn applies the In predicate on the "award_count" field.
func AwardCountIn(vs ...int32) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldIn(FieldAwardCount, vs...))
}

// AwardCountNotIn applies the NotIn predicate on the "award_count" field.
func AwardCountNotIn(vs ...int32) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldNotIn(FieldAwardCount, vs...))
}

// AwardCountGT applies the GT predicate on the "award_count" field.
func AwardCountGT(v int32) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldGT(FieldAwardCount, v))
}

// AwardCountGTE applies the GTE predicate on the "award_count" field.
func AwardCountGTE(v int32) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldGTE(FieldAwardCount, v))
}

// AwardCountLT applies the LT predicate on the "award_count" field.
func AwardCountLT(v int32) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldLT(FieldAwardCount, v))
}

// AwardCountLTE applies the LTE predicate on the "award_count" field.
func AwardCountLTE(v int32) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldLTE(FieldAwardCount, v))
}

// RuleModelsEQ applies the EQ predicate on the "rule_models" field.
func RuleModelsEQ(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldEQ(FieldRuleModels, v))
}

// RuleModelsNEQ applies the NEQ predicate on the "rule_models" field.
func RuleModelsNEQ(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldNEQ(FieldRuleModels, v))
}

// RuleModelsIn applies the In predicate on the "rule_models" field.
func RuleModelsIn(vs ...string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldIn(FieldRuleModels, vs...))
}

// RuleModelsNotIn applies the NotIn predicate on the "rule_models" field.
func RuleModelsNotIn(vs ...string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldNotIn(FieldRuleModels, vs...))
}

// RuleModelsGT applies the GT predicate on the "rule_models" field.
func RuleModelsGT(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldGT(FieldRuleModels, v))
}

// RuleModelsGTE applies the GTE predicate on the "rule_models" field.
func RuleModelsGTE(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldGTE(FieldRuleModels, v))
}

// RuleModelsLT applies the LT predicate on the "rule_models" field.
func RuleModelsLT(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldLT(FieldRuleModels, v))
}

// RuleModelsLTE applies the LTE predicate on the "rule_models" field.
func RuleModelsLTE(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldLTE(FieldRuleModels, v))
}

// RuleModelsContains applies the Contains predicate on the "rule_models" field.
func RuleModelsContains(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldContains(FieldRuleModels, v))
}

// RuleModelsHasPrefix applies the HasPrefix predicate on the "rule_models" field.
func RuleModelsHasPrefix(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldHasPrefix(FieldRuleModels, v))
}

// RuleModelsHasSuffix applies the HasSuffix predicate on the "rule_models" field.
func RuleModelsHasSuffix(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldHasSuffix(FieldRuleModels, v))
}

// RuleModelsIsNil applies the IsNil predicate on the "rule_models" field.
func RuleModelsIsNil() predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldIsNull(FieldRuleModels))
}

// RuleModelsNotNil applies the NotNil predicate on the "rule_models" field.
func RuleModelsNotNil() predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldNotNull(FieldRuleModels))
}

// RuleModelsEqualFold applies the EqualFold predicate on the "rule_models" field.
func RuleModelsEqualFold(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldEqualFold(FieldRuleModels, v))
}

// RuleModelsContainsFold applies the ContainsFold predicate on the "rule_models" field.
func RuleModelsContainsFold(v string) predicate.StrategyAward {
	return predicate.StrategyAward(sql.FieldContainsFold(FieldRuleModels, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.StrategyAward) predicate.StrategyAward {
	return predicate.StrategyAward(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.StrategyAward) predicate.StrategyAward {
	return predicate.StrategyAward(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.StrategyAward) predicate.StrategyAward {
	return predicate.StrategyAward(sql.NotPredicates(p))
}
