FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o seckill-market ./cmd/seckill

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/seckill-market .
COPY --from=builder /app/configs ./configs
EXPOSE 18091
ENTRYPOINT ["./seckill-market"]
