FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o gateway ./cmd/gateway

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/gateway .
COPY --from=builder /app/configs ./configs
EXPOSE 8080
ENTRYPOINT ["./gateway"]
