FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o lottery-market ./cmd/lottery

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/lottery-market .
COPY --from=builder /app/configs ./configs
EXPOSE 18093
ENTRYPOINT ["./lottery-market"]
