// Code generated by ent, DO NOT EDIT.

package lotteryorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/marketing-platform/internal/lottery/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldEQ(FieldOrderID, v))
}

// ActivityID applies equality check predicate on the "activity_id" field. It's identical to ActivityIDEQ.
func ActivityID(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldEQ(FieldActivityID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldEQ(FieldUserID, v))
}

// AwardID applies equality check predicate on the "award_id" field. It's identical to AwardIDEQ.
func AwardID(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldEQ(FieldAwardID, v))
}

// AwardState applies equality check predicate on the "award_state" field. It's identical to AwardStateEQ.
func AwardState(v int32) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldEQ(FieldAwardState, v))
}

// AwardTime applies equality check predicate on the "award_time" field. It's identical to AwardTimeEQ.
func AwardTime(v time.Time) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldEQ(FieldAwardTime, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldNotNull(FieldUpdatedAt))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldNotIn(FieldOrderID, vs...))
}

// OrderIDGT applies the GT predicate on the "order_id" field.
func OrderIDGT(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldGT(FieldOrderID, v))
}

// OrderIDGTE applies the GTE predicate on the "order_id" field.
func OrderIDGTE(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldGTE(FieldOrderID, v))
}

// OrderIDLT applies the LT predicate on the "order_id" field.
func OrderIDLT(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldLT(FieldOrderID, v))
}

// OrderIDLTE applies the LTE predicate on the "order_id" field.
func OrderIDLTE(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldLTE(FieldOrderID, v))
}

// OrderIDContains applies the Contains predicate on the "order_id" field.
func OrderIDContains(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldContains(FieldOrderID, v))
}

// OrderIDHasPrefix applies the HasPrefix predicate on the "order_id" field.
func OrderIDHasPrefix(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldHasPrefix(FieldOrderID, v))
}

// OrderIDHasSuffix applies the HasSuffix predicate on the "order_id" field.
func OrderIDHasSuffix(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldHasSuffix(FieldOrderID, v))
}

// OrderIDEqualFold applies the EqualFold predicate on the "order_id" field.
func OrderIDEqualFold(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldEqualFold(FieldOrderID, v))
}

// OrderIDContainsFold applies the ContainsFold predicate on the "order_id" field.
func OrderIDContainsFold(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldContainsFold(FieldOrderID, v))
}

// ActivityIDEQ applies the EQ predicate on the "activity_id" field.
func ActivityIDEQ(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldEQ(FieldActivityID, v))
}

// ActivityIDNEQ applies the NEQ predicate on the "activity_id" field.
func ActivityIDNEQ(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldNEQ(FieldActivityID, v))
}

// ActivityIDIn applies the In predicate on the "activity_id" field.
func ActivityIDIn(vs ...string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldIn(FieldActivityID, vs...))
}

// ActivityIDNotIn applies the NotIn predicate on the "activity_id" field.
func ActivityIDNotIn(vs ...string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldNotIn(FieldActivityID, vs...))
}

// ActivityIDGT applies the GT predicate on the "activity_id" field.
func ActivityIDGT(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldGT(FieldActivityID, v))
}

// ActivityIDGTE applies the GTE predicate on the "activity_id" field.
func ActivityIDGTE(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldGTE(FieldActivityID, v))
}

// ActivityIDLT applies the LT predicate on the "activity_id" field.
func ActivityIDLT(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldLT(FieldActivityID, v))
}

// ActivityIDLTE applies the LTE predicate on the "activity_id" field.
func ActivityIDLTE(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldLTE(FieldActivityID, v))
}

// ActivityIDContains applies the Contains predicate on the "activity_id" field.
func ActivityIDContains(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldContains(FieldActivityID, v))
}

// ActivityIDHasPrefix applies the HasPrefix predicate on the "activity_id" field.
func ActivityIDHasPrefix(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldHasPrefix(FieldActivityID, v))
}

// ActivityIDHasSuffix applies the HasSuffix predicate on the "activity_id" field.
func ActivityIDHasSuffix(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldHasSuffix(FieldActivityID, v))
}

// ActivityIDEqualFold applies the EqualFold predicate on the "activity_id" field.
func ActivityIDEqualFold(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldEqualFold(FieldActivityID, v))
}

// ActivityIDContainsFold applies the ContainsFold predicate on the "activity_id" field.
func ActivityIDContainsFold(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldContainsFold(FieldActivityID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldLTE(FieldUserID, v))
}

// AwardIDEQ applies the EQ predicate on the "award_id" field.
func AwardIDEQ(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldEQ(FieldAwardID, v))
}

// AwardIDNEQ applies the NEQ predicate on the "award_id" field.
func AwardIDNEQ(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldNEQ(FieldAwardID, v))
}

// AwardIDIn applies the In predicate on the "award_id" field.
func AwardIDIn(vs ...string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldIn(FieldAwardID, vs...))
}

// AwardIDNotIn applies the NotIn predicate on the "award_id" field.
func AwardIDNotIn(vs ...string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldNotIn(FieldAwardID, vs...))
}

// AwardIDGT applies the GT predicate on the "award_id" field.
func AwardIDGT(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldGT(FieldAwardID, v))
}

// AwardIDGTE applies the GTE predicate on the "award_id" field.
func AwardIDGTE(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldGTE(FieldAwardID, v))
}

// AwardIDLT applies the LT predicate on the "award_id" field.
func AwardIDLT(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldLT(FieldAwardID, v))
}

// AwardIDLTE applies the LTE predicate on the "award_id" field.
func AwardIDLTE(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldLTE(FieldAwardID, v))
}

// AwardIDContains applies the Contains predicate on the "award_id" field.
func AwardIDContains(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldContains(FieldAwardID, v))
}

// AwardIDHasPrefix applies the HasPrefix predicate on the "award_id" field.
func AwardIDHasPrefix(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldHasPrefix(FieldAwardID, v))
}

// AwardIDHasSuffix applies the HasSuffix predicate on the "award_id" field.
func AwardIDHasSuffix(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldHasSuffix(FieldAwardID, v))
}

// AwardIDIsNil applies the IsNil predicate on the "award_id" field.
func AwardIDIsNil() predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldIsNull(FieldAwardID))
}

// AwardIDNotNil applies the NotNil predicate on the "award_id" field.
func AwardIDNotNil() predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldNotNull(FieldAwardID))
}

// AwardIDEqualFold applies the EqualFold predicate on the "award_id" field.
func AwardIDEqualFold(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldEqualFold(FieldAwardID, v))
}

// AwardIDContainsFold applies the ContainsFold predicate on the "award_id" field.
func AwardIDContainsFold(v string) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldContainsFold(FieldAwardID, v))
}

// AwardStateEQ applies the EQ predicate on the "award_state" field.
func AwardStateEQ(v int32) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldEQ(FieldAwardState, v))
}

// AwardStateNEQ applies the NEQ predicate on the "award_state" field.
func AwardStateNEQ(v int32) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldNEQ(FieldAwardState, v))
}

// AwardStateIn applies the In predicate on the "award_state" field.
func AwardStateIn(vs ...int32) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldIn(FieldAwardState, vs...))
}

// AwardStateNotIn applies the NotIn predicate on the "award_state" field.
func AwardStateNotIn(vs ...int32) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldNotIn(FieldAwardState, vs...))
}

// AwardStateGT applies the GT predicate on the "award_state" field.
func AwardStateGT(v int32) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldGT(FieldAwardState, v))
}

// AwardStateGTE applies the GTE predicate on the "award_state" field.
func AwardStateGTE(v int32) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldGTE(FieldAwardState, v))
}

// AwardStateLT applies the LT predicate on the "award_state" field.
func AwardStateLT(v int32) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldLT(FieldAwardState, v))
}

// AwardStateLTE applies the LTE predicate on the "award_state" field.
func AwardStateLTE(v int32) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldLTE(FieldAwardState, v))
}

// AwardTimeEQ applies the EQ predicate on the "award_time" field.
func AwardTimeEQ(v time.Time) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldEQ(FieldAwardTime, v))
}

// AwardTimeNEQ applies the NEQ predicate on the "award_time" field.
func AwardTimeNEQ(v time.Time) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldNEQ(FieldAwardTime, v))
}

// AwardTimeIn applies the In predicate on the "award_time" field.
func AwardTimeIn(vs ...time.Time) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldIn(FieldAwardTime, vs...))
}

// AwardTimeNotIn applies the NotIn predicate on the "award_time" field.
func AwardTimeNotIn(vs ...time.Time) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldNotIn(FieldAwardTime, vs...))
}

// AwardTimeGT applies the GT predicate on the "award_time" field.
func AwardTimeGT(v time.Time) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldGT(FieldAwardTime, v))
}

// AwardTimeGTE applies the GTE predicate on the "award_time" field.
func AwardTimeGTE(v time.Time) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldGTE(FieldAwardTime, v))
}

// AwardTimeLT applies the LT predicate on the "award_time" field.
func AwardTimeLT(v time.Time) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldLT(FieldAwardTime, v))
}

// AwardTimeLTE applies the LTE predicate on the "award_time" field.
func AwardTimeLTE(v time.Time) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldLTE(FieldAwardTime, v))
}

// AwardTimeIsNil applies the IsNil predicate on the "award_time" field.
func AwardTimeIsNil() predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldIsNull(FieldAwardTime))
}

// AwardTimeNotNil applies the NotNil predicate on the "award_time" field.
func AwardTimeNotNil() predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.FieldNotNull(FieldAwardTime))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LotteryOrder) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LotteryOrder) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LotteryOrder) predicate.LotteryOrder {
	return predicate.LotteryOrder(sql.NotPredicates(p))
}
