// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"github.com/marketing-platform/internal/conf"
	"github.com/marketing-platform/internal/gateway"
	"github.com/marketing-platform/internal/gateway/server"
	"log/slog"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, data *conf.Data, logger *slog.Logger) (*kratos.App, func(), error) {
	service := gateway.NewService()
	httpServer := server.NewHTTPServer(confServer, service)
	app := newApp(logger, httpServer)
	return app, func() {
	}, nil
}
