// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: api/lottery/v1/lottery.proto

package lotteryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LotteryService_QueryLotteryActivity_FullMethodName = "/lottery.v1.LotteryService/QueryLotteryActivity"
	LotteryService_QueryLotteryStrategy_FullMethodName = "/lottery.v1.LotteryService/QueryLotteryStrategy"
	LotteryService_Raffle_FullMethodName               = "/lottery.v1.LotteryService/Raffle"
	LotteryService_QueryUserRaffleOrder_FullMethodName = "/lottery.v1.LotteryService/QueryUserRaffleOrder"
)

// LotteryServiceClient is the client API for LotteryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 抽奖服务
type LotteryServiceClient interface {
	// 查询抽奖活动
	QueryLotteryActivity(ctx context.Context, in *QueryLotteryActivityReq, opts ...grpc.CallOption) (*QueryLotteryActivityResp, error)
	// 查询抽奖策略
	QueryLotteryStrategy(ctx context.Context, in *QueryLotteryStrategyReq, opts ...grpc.CallOption) (*QueryLotteryStrategyResp, error)
	// 执行抽奖
	Raffle(ctx context.Context, in *RaffleReq, opts ...grpc.CallOption) (*RaffleResp, error)
	// 查询用户抽奖记录
	QueryUserRaffleOrder(ctx context.Context, in *QueryUserRaffleOrderReq, opts ...grpc.CallOption) (*QueryUserRaffleOrderResp, error)
}

type lotteryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLotteryServiceClient(cc grpc.ClientConnInterface) LotteryServiceClient {
	return &lotteryServiceClient{cc}
}

func (c *lotteryServiceClient) QueryLotteryActivity(ctx context.Context, in *QueryLotteryActivityReq, opts ...grpc.CallOption) (*QueryLotteryActivityResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryLotteryActivityResp)
	err := c.cc.Invoke(ctx, LotteryService_QueryLotteryActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryServiceClient) QueryLotteryStrategy(ctx context.Context, in *QueryLotteryStrategyReq, opts ...grpc.CallOption) (*QueryLotteryStrategyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryLotteryStrategyResp)
	err := c.cc.Invoke(ctx, LotteryService_QueryLotteryStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryServiceClient) Raffle(ctx context.Context, in *RaffleReq, opts ...grpc.CallOption) (*RaffleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RaffleResp)
	err := c.cc.Invoke(ctx, LotteryService_Raffle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryServiceClient) QueryUserRaffleOrder(ctx context.Context, in *QueryUserRaffleOrderReq, opts ...grpc.CallOption) (*QueryUserRaffleOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryUserRaffleOrderResp)
	err := c.cc.Invoke(ctx, LotteryService_QueryUserRaffleOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LotteryServiceServer is the server API for LotteryService service.
// All implementations must embed UnimplementedLotteryServiceServer
// for forward compatibility.
//
// 抽奖服务
type LotteryServiceServer interface {
	// 查询抽奖活动
	QueryLotteryActivity(context.Context, *QueryLotteryActivityReq) (*QueryLotteryActivityResp, error)
	// 查询抽奖策略
	QueryLotteryStrategy(context.Context, *QueryLotteryStrategyReq) (*QueryLotteryStrategyResp, error)
	// 执行抽奖
	Raffle(context.Context, *RaffleReq) (*RaffleResp, error)
	// 查询用户抽奖记录
	QueryUserRaffleOrder(context.Context, *QueryUserRaffleOrderReq) (*QueryUserRaffleOrderResp, error)
	mustEmbedUnimplementedLotteryServiceServer()
}

// UnimplementedLotteryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLotteryServiceServer struct{}

func (UnimplementedLotteryServiceServer) QueryLotteryActivity(context.Context, *QueryLotteryActivityReq) (*QueryLotteryActivityResp, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryLotteryActivity not implemented")
}
func (UnimplementedLotteryServiceServer) QueryLotteryStrategy(context.Context, *QueryLotteryStrategyReq) (*QueryLotteryStrategyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryLotteryStrategy not implemented")
}
func (UnimplementedLotteryServiceServer) Raffle(context.Context, *RaffleReq) (*RaffleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Raffle not implemented")
}
func (UnimplementedLotteryServiceServer) QueryUserRaffleOrder(context.Context, *QueryUserRaffleOrderReq) (*QueryUserRaffleOrderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryUserRaffleOrder not implemented")
}
func (UnimplementedLotteryServiceServer) mustEmbedUnimplementedLotteryServiceServer() {}
func (UnimplementedLotteryServiceServer) testEmbeddedByValue()                        {}

// UnsafeLotteryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LotteryServiceServer will
// result in compilation errors.
type UnsafeLotteryServiceServer interface {
	mustEmbedUnimplementedLotteryServiceServer()
}

func RegisterLotteryServiceServer(s grpc.ServiceRegistrar, srv LotteryServiceServer) {
	// If the following call panics, it indicates UnimplementedLotteryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LotteryService_ServiceDesc, srv)
}

func _LotteryService_QueryLotteryActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLotteryActivityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServiceServer).QueryLotteryActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotteryService_QueryLotteryActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServiceServer).QueryLotteryActivity(ctx, req.(*QueryLotteryActivityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LotteryService_QueryLotteryStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLotteryStrategyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServiceServer).QueryLotteryStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotteryService_QueryLotteryStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServiceServer).QueryLotteryStrategy(ctx, req.(*QueryLotteryStrategyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LotteryService_Raffle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RaffleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServiceServer).Raffle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotteryService_Raffle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServiceServer).Raffle(ctx, req.(*RaffleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LotteryService_QueryUserRaffleOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserRaffleOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServiceServer).QueryUserRaffleOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotteryService_QueryUserRaffleOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServiceServer).QueryUserRaffleOrder(ctx, req.(*QueryUserRaffleOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

// LotteryService_ServiceDesc is the grpc.ServiceDesc for LotteryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LotteryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lottery.v1.LotteryService",
	HandlerType: (*LotteryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryLotteryActivity",
			Handler:    _LotteryService_QueryLotteryActivity_Handler,
		},
		{
			MethodName: "QueryLotteryStrategy",
			Handler:    _LotteryService_QueryLotteryStrategy_Handler,
		},
		{
			MethodName: "Raffle",
			Handler:    _LotteryService_Raffle_Handler,
		},
		{
			MethodName: "QueryUserRaffleOrder",
			Handler:    _LotteryService_QueryUserRaffleOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/lottery/v1/lottery.proto",
}
