// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"github.com/marketing-platform/internal/groupbuy/data/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/marketing-platform/internal/groupbuy/data/ent/groupbuyactivity"
	"github.com/marketing-platform/internal/groupbuy/data/ent/groupbuydiscount"
	"github.com/marketing-platform/internal/groupbuy/data/ent/groupbuyorder"
	"github.com/marketing-platform/internal/groupbuy/data/ent/groupbuyteam"
	"github.com/marketing-platform/internal/groupbuy/data/ent/notifytask"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// GroupBuyActivity is the client for interacting with the GroupBuyActivity builders.
	GroupBuyActivity *GroupBuyActivityClient
	// GroupBuyDiscount is the client for interacting with the GroupBuyDiscount builders.
	GroupBuyDiscount *GroupBuyDiscountClient
	// GroupBuyOrder is the client for interacting with the GroupBuyOrder builders.
	GroupBuyOrder *GroupBuyOrderClient
	// GroupBuyTeam is the client for interacting with the GroupBuyTeam builders.
	GroupBuyTeam *GroupBuyTeamClient
	// NotifyTask is the client for interacting with the NotifyTask builders.
	NotifyTask *NotifyTaskClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.GroupBuyActivity = NewGroupBuyActivityClient(c.config)
	c.GroupBuyDiscount = NewGroupBuyDiscountClient(c.config)
	c.GroupBuyOrder = NewGroupBuyOrderClient(c.config)
	c.GroupBuyTeam = NewGroupBuyTeamClient(c.config)
	c.NotifyTask = NewNotifyTaskClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		GroupBuyActivity: NewGroupBuyActivityClient(cfg),
		GroupBuyDiscount: NewGroupBuyDiscountClient(cfg),
		GroupBuyOrder:    NewGroupBuyOrderClient(cfg),
		GroupBuyTeam:     NewGroupBuyTeamClient(cfg),
		NotifyTask:       NewNotifyTaskClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		GroupBuyActivity: NewGroupBuyActivityClient(cfg),
		GroupBuyDiscount: NewGroupBuyDiscountClient(cfg),
		GroupBuyOrder:    NewGroupBuyOrderClient(cfg),
		GroupBuyTeam:     NewGroupBuyTeamClient(cfg),
		NotifyTask:       NewNotifyTaskClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		GroupBuyActivity.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.GroupBuyActivity.Use(hooks...)
	c.GroupBuyDiscount.Use(hooks...)
	c.GroupBuyOrder.Use(hooks...)
	c.GroupBuyTeam.Use(hooks...)
	c.NotifyTask.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.GroupBuyActivity.Intercept(interceptors...)
	c.GroupBuyDiscount.Intercept(interceptors...)
	c.GroupBuyOrder.Intercept(interceptors...)
	c.GroupBuyTeam.Intercept(interceptors...)
	c.NotifyTask.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *GroupBuyActivityMutation:
		return c.GroupBuyActivity.mutate(ctx, m)
	case *GroupBuyDiscountMutation:
		return c.GroupBuyDiscount.mutate(ctx, m)
	case *GroupBuyOrderMutation:
		return c.GroupBuyOrder.mutate(ctx, m)
	case *GroupBuyTeamMutation:
		return c.GroupBuyTeam.mutate(ctx, m)
	case *NotifyTaskMutation:
		return c.NotifyTask.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// GroupBuyActivityClient is a client for the GroupBuyActivity schema.
type GroupBuyActivityClient struct {
	config
}

// NewGroupBuyActivityClient returns a client for the GroupBuyActivity from the given config.
func NewGroupBuyActivityClient(c config) *GroupBuyActivityClient {
	return &GroupBuyActivityClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `groupbuyactivity.Hooks(f(g(h())))`.
func (c *GroupBuyActivityClient) Use(hooks ...Hook) {
	c.hooks.GroupBuyActivity = append(c.hooks.GroupBuyActivity, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `groupbuyactivity.Intercept(f(g(h())))`.
func (c *GroupBuyActivityClient) Intercept(interceptors ...Interceptor) {
	c.inters.GroupBuyActivity = append(c.inters.GroupBuyActivity, interceptors...)
}

// Create returns a builder for creating a GroupBuyActivity entity.
func (c *GroupBuyActivityClient) Create() *GroupBuyActivityCreate {
	mutation := newGroupBuyActivityMutation(c.config, OpCreate)
	return &GroupBuyActivityCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of GroupBuyActivity entities.
func (c *GroupBuyActivityClient) CreateBulk(builders ...*GroupBuyActivityCreate) *GroupBuyActivityCreateBulk {
	return &GroupBuyActivityCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *GroupBuyActivityClient) MapCreateBulk(slice any, setFunc func(*GroupBuyActivityCreate, int)) *GroupBuyActivityCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &GroupBuyActivityCreateBulk{err: fmt.Errorf("calling to GroupBuyActivityClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*GroupBuyActivityCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &GroupBuyActivityCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for GroupBuyActivity.
func (c *GroupBuyActivityClient) Update() *GroupBuyActivityUpdate {
	mutation := newGroupBuyActivityMutation(c.config, OpUpdate)
	return &GroupBuyActivityUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GroupBuyActivityClient) UpdateOne(_m *GroupBuyActivity) *GroupBuyActivityUpdateOne {
	mutation := newGroupBuyActivityMutation(c.config, OpUpdateOne, withGroupBuyActivity(_m))
	return &GroupBuyActivityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *GroupBuyActivityClient) UpdateOneID(id uuid.UUID) *GroupBuyActivityUpdateOne {
	mutation := newGroupBuyActivityMutation(c.config, OpUpdateOne, withGroupBuyActivityID(id))
	return &GroupBuyActivityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for GroupBuyActivity.
func (c *GroupBuyActivityClient) Delete() *GroupBuyActivityDelete {
	mutation := newGroupBuyActivityMutation(c.config, OpDelete)
	return &GroupBuyActivityDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *GroupBuyActivityClient) DeleteOne(_m *GroupBuyActivity) *GroupBuyActivityDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *GroupBuyActivityClient) DeleteOneID(id uuid.UUID) *GroupBuyActivityDeleteOne {
	builder := c.Delete().Where(groupbuyactivity.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &GroupBuyActivityDeleteOne{builder}
}

// Query returns a query builder for GroupBuyActivity.
func (c *GroupBuyActivityClient) Query() *GroupBuyActivityQuery {
	return &GroupBuyActivityQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeGroupBuyActivity},
		inters: c.Interceptors(),
	}
}

// Get returns a GroupBuyActivity entity by its id.
func (c *GroupBuyActivityClient) Get(ctx context.Context, id uuid.UUID) (*GroupBuyActivity, error) {
	return c.Query().Where(groupbuyactivity.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *GroupBuyActivityClient) GetX(ctx context.Context, id uuid.UUID) *GroupBuyActivity {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *GroupBuyActivityClient) Hooks() []Hook {
	return c.hooks.GroupBuyActivity
}

// Interceptors returns the client interceptors.
func (c *GroupBuyActivityClient) Interceptors() []Interceptor {
	return c.inters.GroupBuyActivity
}

func (c *GroupBuyActivityClient) mutate(ctx context.Context, m *GroupBuyActivityMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&GroupBuyActivityCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&GroupBuyActivityUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&GroupBuyActivityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&GroupBuyActivityDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown GroupBuyActivity mutation op: %q", m.Op())
	}
}

// GroupBuyDiscountClient is a client for the GroupBuyDiscount schema.
type GroupBuyDiscountClient struct {
	config
}

// NewGroupBuyDiscountClient returns a client for the GroupBuyDiscount from the given config.
func NewGroupBuyDiscountClient(c config) *GroupBuyDiscountClient {
	return &GroupBuyDiscountClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `groupbuydiscount.Hooks(f(g(h())))`.
func (c *GroupBuyDiscountClient) Use(hooks ...Hook) {
	c.hooks.GroupBuyDiscount = append(c.hooks.GroupBuyDiscount, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `groupbuydiscount.Intercept(f(g(h())))`.
func (c *GroupBuyDiscountClient) Intercept(interceptors ...Interceptor) {
	c.inters.GroupBuyDiscount = append(c.inters.GroupBuyDiscount, interceptors...)
}

// Create returns a builder for creating a GroupBuyDiscount entity.
func (c *GroupBuyDiscountClient) Create() *GroupBuyDiscountCreate {
	mutation := newGroupBuyDiscountMutation(c.config, OpCreate)
	return &GroupBuyDiscountCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of GroupBuyDiscount entities.
func (c *GroupBuyDiscountClient) CreateBulk(builders ...*GroupBuyDiscountCreate) *GroupBuyDiscountCreateBulk {
	return &GroupBuyDiscountCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *GroupBuyDiscountClient) MapCreateBulk(slice any, setFunc func(*GroupBuyDiscountCreate, int)) *GroupBuyDiscountCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &GroupBuyDiscountCreateBulk{err: fmt.Errorf("calling to GroupBuyDiscountClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*GroupBuyDiscountCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &GroupBuyDiscountCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for GroupBuyDiscount.
func (c *GroupBuyDiscountClient) Update() *GroupBuyDiscountUpdate {
	mutation := newGroupBuyDiscountMutation(c.config, OpUpdate)
	return &GroupBuyDiscountUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GroupBuyDiscountClient) UpdateOne(_m *GroupBuyDiscount) *GroupBuyDiscountUpdateOne {
	mutation := newGroupBuyDiscountMutation(c.config, OpUpdateOne, withGroupBuyDiscount(_m))
	return &GroupBuyDiscountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *GroupBuyDiscountClient) UpdateOneID(id uuid.UUID) *GroupBuyDiscountUpdateOne {
	mutation := newGroupBuyDiscountMutation(c.config, OpUpdateOne, withGroupBuyDiscountID(id))
	return &GroupBuyDiscountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for GroupBuyDiscount.
func (c *GroupBuyDiscountClient) Delete() *GroupBuyDiscountDelete {
	mutation := newGroupBuyDiscountMutation(c.config, OpDelete)
	return &GroupBuyDiscountDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *GroupBuyDiscountClient) DeleteOne(_m *GroupBuyDiscount) *GroupBuyDiscountDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *GroupBuyDiscountClient) DeleteOneID(id uuid.UUID) *GroupBuyDiscountDeleteOne {
	builder := c.Delete().Where(groupbuydiscount.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &GroupBuyDiscountDeleteOne{builder}
}

// Query returns a query builder for GroupBuyDiscount.
func (c *GroupBuyDiscountClient) Query() *GroupBuyDiscountQuery {
	return &GroupBuyDiscountQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeGroupBuyDiscount},
		inters: c.Interceptors(),
	}
}

// Get returns a GroupBuyDiscount entity by its id.
func (c *GroupBuyDiscountClient) Get(ctx context.Context, id uuid.UUID) (*GroupBuyDiscount, error) {
	return c.Query().Where(groupbuydiscount.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *GroupBuyDiscountClient) GetX(ctx context.Context, id uuid.UUID) *GroupBuyDiscount {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *GroupBuyDiscountClient) Hooks() []Hook {
	return c.hooks.GroupBuyDiscount
}

// Interceptors returns the client interceptors.
func (c *GroupBuyDiscountClient) Interceptors() []Interceptor {
	return c.inters.GroupBuyDiscount
}

func (c *GroupBuyDiscountClient) mutate(ctx context.Context, m *GroupBuyDiscountMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&GroupBuyDiscountCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&GroupBuyDiscountUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&GroupBuyDiscountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&GroupBuyDiscountDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown GroupBuyDiscount mutation op: %q", m.Op())
	}
}

// GroupBuyOrderClient is a client for the GroupBuyOrder schema.
type GroupBuyOrderClient struct {
	config
}

// NewGroupBuyOrderClient returns a client for the GroupBuyOrder from the given config.
func NewGroupBuyOrderClient(c config) *GroupBuyOrderClient {
	return &GroupBuyOrderClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `groupbuyorder.Hooks(f(g(h())))`.
func (c *GroupBuyOrderClient) Use(hooks ...Hook) {
	c.hooks.GroupBuyOrder = append(c.hooks.GroupBuyOrder, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `groupbuyorder.Intercept(f(g(h())))`.
func (c *GroupBuyOrderClient) Intercept(interceptors ...Interceptor) {
	c.inters.GroupBuyOrder = append(c.inters.GroupBuyOrder, interceptors...)
}

// Create returns a builder for creating a GroupBuyOrder entity.
func (c *GroupBuyOrderClient) Create() *GroupBuyOrderCreate {
	mutation := newGroupBuyOrderMutation(c.config, OpCreate)
	return &GroupBuyOrderCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of GroupBuyOrder entities.
func (c *GroupBuyOrderClient) CreateBulk(builders ...*GroupBuyOrderCreate) *GroupBuyOrderCreateBulk {
	return &GroupBuyOrderCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *GroupBuyOrderClient) MapCreateBulk(slice any, setFunc func(*GroupBuyOrderCreate, int)) *GroupBuyOrderCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &GroupBuyOrderCreateBulk{err: fmt.Errorf("calling to GroupBuyOrderClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*GroupBuyOrderCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &GroupBuyOrderCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for GroupBuyOrder.
func (c *GroupBuyOrderClient) Update() *GroupBuyOrderUpdate {
	mutation := newGroupBuyOrderMutation(c.config, OpUpdate)
	return &GroupBuyOrderUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GroupBuyOrderClient) UpdateOne(_m *GroupBuyOrder) *GroupBuyOrderUpdateOne {
	mutation := newGroupBuyOrderMutation(c.config, OpUpdateOne, withGroupBuyOrder(_m))
	return &GroupBuyOrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *GroupBuyOrderClient) UpdateOneID(id uuid.UUID) *GroupBuyOrderUpdateOne {
	mutation := newGroupBuyOrderMutation(c.config, OpUpdateOne, withGroupBuyOrderID(id))
	return &GroupBuyOrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for GroupBuyOrder.
func (c *GroupBuyOrderClient) Delete() *GroupBuyOrderDelete {
	mutation := newGroupBuyOrderMutation(c.config, OpDelete)
	return &GroupBuyOrderDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *GroupBuyOrderClient) DeleteOne(_m *GroupBuyOrder) *GroupBuyOrderDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *GroupBuyOrderClient) DeleteOneID(id uuid.UUID) *GroupBuyOrderDeleteOne {
	builder := c.Delete().Where(groupbuyorder.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &GroupBuyOrderDeleteOne{builder}
}

// Query returns a query builder for GroupBuyOrder.
func (c *GroupBuyOrderClient) Query() *GroupBuyOrderQuery {
	return &GroupBuyOrderQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeGroupBuyOrder},
		inters: c.Interceptors(),
	}
}

// Get returns a GroupBuyOrder entity by its id.
func (c *GroupBuyOrderClient) Get(ctx context.Context, id uuid.UUID) (*GroupBuyOrder, error) {
	return c.Query().Where(groupbuyorder.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *GroupBuyOrderClient) GetX(ctx context.Context, id uuid.UUID) *GroupBuyOrder {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *GroupBuyOrderClient) Hooks() []Hook {
	return c.hooks.GroupBuyOrder
}

// Interceptors returns the client interceptors.
func (c *GroupBuyOrderClient) Interceptors() []Interceptor {
	return c.inters.GroupBuyOrder
}

func (c *GroupBuyOrderClient) mutate(ctx context.Context, m *GroupBuyOrderMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&GroupBuyOrderCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&GroupBuyOrderUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&GroupBuyOrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&GroupBuyOrderDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown GroupBuyOrder mutation op: %q", m.Op())
	}
}

// GroupBuyTeamClient is a client for the GroupBuyTeam schema.
type GroupBuyTeamClient struct {
	config
}

// NewGroupBuyTeamClient returns a client for the GroupBuyTeam from the given config.
func NewGroupBuyTeamClient(c config) *GroupBuyTeamClient {
	return &GroupBuyTeamClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `groupbuyteam.Hooks(f(g(h())))`.
func (c *GroupBuyTeamClient) Use(hooks ...Hook) {
	c.hooks.GroupBuyTeam = append(c.hooks.GroupBuyTeam, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `groupbuyteam.Intercept(f(g(h())))`.
func (c *GroupBuyTeamClient) Intercept(interceptors ...Interceptor) {
	c.inters.GroupBuyTeam = append(c.inters.GroupBuyTeam, interceptors...)
}

// Create returns a builder for creating a GroupBuyTeam entity.
func (c *GroupBuyTeamClient) Create() *GroupBuyTeamCreate {
	mutation := newGroupBuyTeamMutation(c.config, OpCreate)
	return &GroupBuyTeamCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of GroupBuyTeam entities.
func (c *GroupBuyTeamClient) CreateBulk(builders ...*GroupBuyTeamCreate) *GroupBuyTeamCreateBulk {
	return &GroupBuyTeamCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *GroupBuyTeamClient) MapCreateBulk(slice any, setFunc func(*GroupBuyTeamCreate, int)) *GroupBuyTeamCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &GroupBuyTeamCreateBulk{err: fmt.Errorf("calling to GroupBuyTeamClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*GroupBuyTeamCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &GroupBuyTeamCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for GroupBuyTeam.
func (c *GroupBuyTeamClient) Update() *GroupBuyTeamUpdate {
	mutation := newGroupBuyTeamMutation(c.config, OpUpdate)
	return &GroupBuyTeamUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GroupBuyTeamClient) UpdateOne(_m *GroupBuyTeam) *GroupBuyTeamUpdateOne {
	mutation := newGroupBuyTeamMutation(c.config, OpUpdateOne, withGroupBuyTeam(_m))
	return &GroupBuyTeamUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *GroupBuyTeamClient) UpdateOneID(id uuid.UUID) *GroupBuyTeamUpdateOne {
	mutation := newGroupBuyTeamMutation(c.config, OpUpdateOne, withGroupBuyTeamID(id))
	return &GroupBuyTeamUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for GroupBuyTeam.
func (c *GroupBuyTeamClient) Delete() *GroupBuyTeamDelete {
	mutation := newGroupBuyTeamMutation(c.config, OpDelete)
	return &GroupBuyTeamDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *GroupBuyTeamClient) DeleteOne(_m *GroupBuyTeam) *GroupBuyTeamDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *GroupBuyTeamClient) DeleteOneID(id uuid.UUID) *GroupBuyTeamDeleteOne {
	builder := c.Delete().Where(groupbuyteam.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &GroupBuyTeamDeleteOne{builder}
}

// Query returns a query builder for GroupBuyTeam.
func (c *GroupBuyTeamClient) Query() *GroupBuyTeamQuery {
	return &GroupBuyTeamQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeGroupBuyTeam},
		inters: c.Interceptors(),
	}
}

// Get returns a GroupBuyTeam entity by its id.
func (c *GroupBuyTeamClient) Get(ctx context.Context, id uuid.UUID) (*GroupBuyTeam, error) {
	return c.Query().Where(groupbuyteam.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *GroupBuyTeamClient) GetX(ctx context.Context, id uuid.UUID) *GroupBuyTeam {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *GroupBuyTeamClient) Hooks() []Hook {
	return c.hooks.GroupBuyTeam
}

// Interceptors returns the client interceptors.
func (c *GroupBuyTeamClient) Interceptors() []Interceptor {
	return c.inters.GroupBuyTeam
}

func (c *GroupBuyTeamClient) mutate(ctx context.Context, m *GroupBuyTeamMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&GroupBuyTeamCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&GroupBuyTeamUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&GroupBuyTeamUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&GroupBuyTeamDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown GroupBuyTeam mutation op: %q", m.Op())
	}
}

// NotifyTaskClient is a client for the NotifyTask schema.
type NotifyTaskClient struct {
	config
}

// NewNotifyTaskClient returns a client for the NotifyTask from the given config.
func NewNotifyTaskClient(c config) *NotifyTaskClient {
	return &NotifyTaskClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `notifytask.Hooks(f(g(h())))`.
func (c *NotifyTaskClient) Use(hooks ...Hook) {
	c.hooks.NotifyTask = append(c.hooks.NotifyTask, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `notifytask.Intercept(f(g(h())))`.
func (c *NotifyTaskClient) Intercept(interceptors ...Interceptor) {
	c.inters.NotifyTask = append(c.inters.NotifyTask, interceptors...)
}

// Create returns a builder for creating a NotifyTask entity.
func (c *NotifyTaskClient) Create() *NotifyTaskCreate {
	mutation := newNotifyTaskMutation(c.config, OpCreate)
	return &NotifyTaskCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of NotifyTask entities.
func (c *NotifyTaskClient) CreateBulk(builders ...*NotifyTaskCreate) *NotifyTaskCreateBulk {
	return &NotifyTaskCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *NotifyTaskClient) MapCreateBulk(slice any, setFunc func(*NotifyTaskCreate, int)) *NotifyTaskCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &NotifyTaskCreateBulk{err: fmt.Errorf("calling to NotifyTaskClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*NotifyTaskCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &NotifyTaskCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for NotifyTask.
func (c *NotifyTaskClient) Update() *NotifyTaskUpdate {
	mutation := newNotifyTaskMutation(c.config, OpUpdate)
	return &NotifyTaskUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *NotifyTaskClient) UpdateOne(_m *NotifyTask) *NotifyTaskUpdateOne {
	mutation := newNotifyTaskMutation(c.config, OpUpdateOne, withNotifyTask(_m))
	return &NotifyTaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *NotifyTaskClient) UpdateOneID(id uuid.UUID) *NotifyTaskUpdateOne {
	mutation := newNotifyTaskMutation(c.config, OpUpdateOne, withNotifyTaskID(id))
	return &NotifyTaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for NotifyTask.
func (c *NotifyTaskClient) Delete() *NotifyTaskDelete {
	mutation := newNotifyTaskMutation(c.config, OpDelete)
	return &NotifyTaskDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *NotifyTaskClient) DeleteOne(_m *NotifyTask) *NotifyTaskDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *NotifyTaskClient) DeleteOneID(id uuid.UUID) *NotifyTaskDeleteOne {
	builder := c.Delete().Where(notifytask.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &NotifyTaskDeleteOne{builder}
}

// Query returns a query builder for NotifyTask.
func (c *NotifyTaskClient) Query() *NotifyTaskQuery {
	return &NotifyTaskQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeNotifyTask},
		inters: c.Interceptors(),
	}
}

// Get returns a NotifyTask entity by its id.
func (c *NotifyTaskClient) Get(ctx context.Context, id uuid.UUID) (*NotifyTask, error) {
	return c.Query().Where(notifytask.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *NotifyTaskClient) GetX(ctx context.Context, id uuid.UUID) *NotifyTask {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *NotifyTaskClient) Hooks() []Hook {
	return c.hooks.NotifyTask
}

// Interceptors returns the client interceptors.
func (c *NotifyTaskClient) Interceptors() []Interceptor {
	return c.inters.NotifyTask
}

func (c *NotifyTaskClient) mutate(ctx context.Context, m *NotifyTaskMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&NotifyTaskCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&NotifyTaskUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&NotifyTaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&NotifyTaskDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown NotifyTask mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		GroupBuyActivity, GroupBuyDiscount, GroupBuyOrder, GroupBuyTeam,
		NotifyTask []ent.Hook
	}
	inters struct {
		GroupBuyActivity, GroupBuyDiscount, GroupBuyOrder, GroupBuyTeam,
		NotifyTask []ent.Interceptor
	}
)
