// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/marketing-platform/internal/groupbuy/data/ent/groupbuydiscount"
)

// GroupBuyDiscountCreate is the builder for creating a GroupBuyDiscount entity.
type GroupBuyDiscountCreate struct {
	config
	mutation *GroupBuyDiscountMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *GroupBuyDiscountCreate) SetCreatedAt(v time.Time) *GroupBuyDiscountCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GroupBuyDiscountCreate) SetNillableCreatedAt(v *time.Time) *GroupBuyDiscountCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GroupBuyDiscountCreate) SetUpdatedAt(v time.Time) *GroupBuyDiscountCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GroupBuyDiscountCreate) SetNillableUpdatedAt(v *time.Time) *GroupBuyDiscountCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDiscountID sets the "discount_id" field.
func (_c *GroupBuyDiscountCreate) SetDiscountID(v string) *GroupBuyDiscountCreate {
	_c.mutation.SetDiscountID(v)
	return _c
}

// SetMarketPlan sets the "market_plan" field.
func (_c *GroupBuyDiscountCreate) SetMarketPlan(v string) *GroupBuyDiscountCreate {
	_c.mutation.SetMarketPlan(v)
	return _c
}

// SetMarketExpr sets the "market_expr" field.
func (_c *GroupBuyDiscountCreate) SetMarketExpr(v string) *GroupBuyDiscountCreate {
	_c.mutation.SetMarketExpr(v)
	return _c
}

// SetID sets the "id" field.
func (_c *GroupBuyDiscountCreate) SetID(v uuid.UUID) *GroupBuyDiscountCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *GroupBuyDiscountCreate) SetNillableID(v *uuid.UUID) *GroupBuyDiscountCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the GroupBuyDiscountMutation object of the builder.
func (_c *GroupBuyDiscountCreate) Mutation() *GroupBuyDiscountMutation {
	return _c.mutation
}

// Save creates the GroupBuyDiscount in the database.
func (_c *GroupBuyDiscountCreate) Save(ctx context.Context) (*GroupBuyDiscount, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GroupBuyDiscountCreate) SaveX(ctx context.Context) *GroupBuyDiscount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupBuyDiscountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupBuyDiscountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GroupBuyDiscountCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := groupbuydiscount.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GroupBuyDiscountCreate) check() error {
	if _, ok := _c.mutation.DiscountID(); !ok {
		return &ValidationError{Name: "discount_id", err: errors.New(`ent: missing required field "GroupBuyDiscount.discount_id"`)}
	}
	if v, ok := _c.mutation.DiscountID(); ok {
		if err := groupbuydiscount.DiscountIDValidator(v); err != nil {
			return &ValidationError{Name: "discount_id", err: fmt.Errorf(`ent: validator failed for field "GroupBuyDiscount.discount_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MarketPlan(); !ok {
		return &ValidationError{Name: "market_plan", err: errors.New(`ent: missing required field "GroupBuyDiscount.market_plan"`)}
	}
	if v, ok := _c.mutation.MarketPlan(); ok {
		if err := groupbuydiscount.MarketPlanValidator(v); err != nil {
			return &ValidationError{Name: "market_plan", err: fmt.Errorf(`ent: validator failed for field "GroupBuyDiscount.market_plan": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MarketExpr(); !ok {
		return &ValidationError{Name: "market_expr", err: errors.New(`ent: missing required field "GroupBuyDiscount.market_expr"`)}
	}
	if v, ok := _c.mutation.MarketExpr(); ok {
		if err := groupbuydiscount.MarketExprValidator(v); err != nil {
			return &ValidationError{Name: "market_expr", err: fmt.Errorf(`ent: validator failed for field "GroupBuyDiscount.market_expr": %w`, err)}
		}
	}
	return nil
}

func (_c *GroupBuyDiscountCreate) sqlSave(ctx context.Context) (*GroupBuyDiscount, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GroupBuyDiscountCreate) createSpec() (*GroupBuyDiscount, *sqlgraph.CreateSpec) {
	var (
		_node = &GroupBuyDiscount{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(groupbuydiscount.Table, sqlgraph.NewFieldSpec(groupbuydiscount.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(groupbuydiscount.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(groupbuydiscount.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DiscountID(); ok {
		_spec.SetField(groupbuydiscount.FieldDiscountID, field.TypeString, value)
		_node.DiscountID = value
	}
	if value, ok := _c.mutation.MarketPlan(); ok {
		_spec.SetField(groupbuydiscount.FieldMarketPlan, field.TypeString, value)
		_node.MarketPlan = value
	}
	if value, ok := _c.mutation.MarketExpr(); ok {
		_spec.SetField(groupbuydiscount.FieldMarketExpr, field.TypeString, value)
		_node.MarketExpr = value
	}
	return _node, _spec
}

// GroupBuyDiscountCreateBulk is the builder for creating many GroupBuyDiscount entities in bulk.
type GroupBuyDiscountCreateBulk struct {
	config
	err      error
	builders []*GroupBuyDiscountCreate
}

// Save creates the GroupBuyDiscount entities in the database.
func (_c *GroupBuyDiscountCreateBulk) Save(ctx context.Context) ([]*GroupBuyDiscount, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GroupBuyDiscount, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupBuyDiscountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GroupBuyDiscountCreateBulk) SaveX(ctx context.Context) []*GroupBuyDiscount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupBuyDiscountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupBuyDiscountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
