// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/marketing-platform/internal/groupbuy/data/ent/groupbuyteam"
	"github.com/marketing-platform/internal/groupbuy/data/ent/predicate"
)

// GroupBuyTeamDelete is the builder for deleting a GroupBuyTeam entity.
type GroupBuyTeamDelete struct {
	config
	hooks    []Hook
	mutation *GroupBuyTeamMutation
}

// Where appends a list predicates to the GroupBuyTeamDelete builder.
func (_d *GroupBuyTeamDelete) Where(ps ...predicate.GroupBuyTeam) *GroupBuyTeamDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GroupBuyTeamDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GroupBuyTeamDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GroupBuyTeamDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(groupbuyteam.Table, sqlgraph.NewFieldSpec(groupbuyteam.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GroupBuyTeamDeleteOne is the builder for deleting a single GroupBuyTeam entity.
type GroupBuyTeamDeleteOne struct {
	_d *GroupBuyTeamDelete
}

// Where appends a list predicates to the GroupBuyTeamDelete builder.
func (_d *GroupBuyTeamDeleteOne) Where(ps ...predicate.GroupBuyTeam) *GroupBuyTeamDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GroupBuyTeamDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{groupbuyteam.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GroupBuyTeamDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
