// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/marketing-platform/internal/groupbuy/data/ent/groupbuydiscount"
	"github.com/marketing-platform/internal/groupbuy/data/ent/predicate"
)

// GroupBuyDiscountUpdate is the builder for updating GroupBuyDiscount entities.
type GroupBuyDiscountUpdate struct {
	config
	hooks    []Hook
	mutation *GroupBuyDiscountMutation
}

// Where appends a list predicates to the GroupBuyDiscountUpdate builder.
func (_u *GroupBuyDiscountUpdate) Where(ps ...predicate.GroupBuyDiscount) *GroupBuyDiscountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *GroupBuyDiscountUpdate) SetCreatedAt(v time.Time) *GroupBuyDiscountUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *GroupBuyDiscountUpdate) SetNillableCreatedAt(v *time.Time) *GroupBuyDiscountUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *GroupBuyDiscountUpdate) ClearCreatedAt() *GroupBuyDiscountUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GroupBuyDiscountUpdate) SetUpdatedAt(v time.Time) *GroupBuyDiscountUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *GroupBuyDiscountUpdate) SetNillableUpdatedAt(v *time.Time) *GroupBuyDiscountUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *GroupBuyDiscountUpdate) ClearUpdatedAt() *GroupBuyDiscountUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDiscountID sets the "discount_id" field.
func (_u *GroupBuyDiscountUpdate) SetDiscountID(v string) *GroupBuyDiscountUpdate {
	_u.mutation.SetDiscountID(v)
	return _u
}

// SetNillableDiscountID sets the "discount_id" field if the given value is not nil.
func (_u *GroupBuyDiscountUpdate) SetNillableDiscountID(v *string) *GroupBuyDiscountUpdate {
	if v != nil {
		_u.SetDiscountID(*v)
	}
	return _u
}

// SetMarketPlan sets the "market_plan" field.
func (_u *GroupBuyDiscountUpdate) SetMarketPlan(v string) *GroupBuyDiscountUpdate {
	_u.mutation.SetMarketPlan(v)
	return _u
}

// SetNillableMarketPlan sets the "market_plan" field if the given value is not nil.
func (_u *GroupBuyDiscountUpdate) SetNillableMarketPlan(v *string) *GroupBuyDiscountUpdate {
	if v != nil {
		_u.SetMarketPlan(*v)
	}
	return _u
}

// SetMarketExpr sets the "market_expr" field.
func (_u *GroupBuyDiscountUpdate) SetMarketExpr(v string) *GroupBuyDiscountUpdate {
	_u.mutation.SetMarketExpr(v)
	return _u
}

// SetNillableMarketExpr sets the "market_expr" field if the given value is not nil.
func (_u *GroupBuyDiscountUpdate) SetNillableMarketExpr(v *string) *GroupBuyDiscountUpdate {
	if v != nil {
		_u.SetMarketExpr(*v)
	}
	return _u
}

// Mutation returns the GroupBuyDiscountMutation object of the builder.
func (_u *GroupBuyDiscountUpdate) Mutation() *GroupBuyDiscountMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GroupBuyDiscountUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupBuyDiscountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GroupBuyDiscountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupBuyDiscountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupBuyDiscountUpdate) check() error {
	if v, ok := _u.mutation.DiscountID(); ok {
		if err := groupbuydiscount.DiscountIDValidator(v); err != nil {
			return &ValidationError{Name: "discount_id", err: fmt.Errorf(`ent: validator failed for field "GroupBuyDiscount.discount_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MarketPlan(); ok {
		if err := groupbuydiscount.MarketPlanValidator(v); err != nil {
			return &ValidationError{Name: "market_plan", err: fmt.Errorf(`ent: validator failed for field "GroupBuyDiscount.market_plan": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MarketExpr(); ok {
		if err := groupbuydiscount.MarketExprValidator(v); err != nil {
			return &ValidationError{Name: "market_expr", err: fmt.Errorf(`ent: validator failed for field "GroupBuyDiscount.market_expr": %w`, err)}
		}
	}
	return nil
}

func (_u *GroupBuyDiscountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(groupbuydiscount.Table, groupbuydiscount.Columns, sqlgraph.NewFieldSpec(groupbuydiscount.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(groupbuydiscount.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(groupbuydiscount.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(groupbuydiscount.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(groupbuydiscount.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DiscountID(); ok {
		_spec.SetField(groupbuydiscount.FieldDiscountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.MarketPlan(); ok {
		_spec.SetField(groupbuydiscount.FieldMarketPlan, field.TypeString, value)
	}
	if value, ok := _u.mutation.MarketExpr(); ok {
		_spec.SetField(groupbuydiscount.FieldMarketExpr, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groupbuydiscount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GroupBuyDiscountUpdateOne is the builder for updating a single GroupBuyDiscount entity.
type GroupBuyDiscountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GroupBuyDiscountMutation
}

// SetCreatedAt sets the "created_at" field.
func (_u *GroupBuyDiscountUpdateOne) SetCreatedAt(v time.Time) *GroupBuyDiscountUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *GroupBuyDiscountUpdateOne) SetNillableCreatedAt(v *time.Time) *GroupBuyDiscountUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *GroupBuyDiscountUpdateOne) ClearCreatedAt() *GroupBuyDiscountUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GroupBuyDiscountUpdateOne) SetUpdatedAt(v time.Time) *GroupBuyDiscountUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *GroupBuyDiscountUpdateOne) SetNillableUpdatedAt(v *time.Time) *GroupBuyDiscountUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *GroupBuyDiscountUpdateOne) ClearUpdatedAt() *GroupBuyDiscountUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDiscountID sets the "discount_id" field.
func (_u *GroupBuyDiscountUpdateOne) SetDiscountID(v string) *GroupBuyDiscountUpdateOne {
	_u.mutation.SetDiscountID(v)
	return _u
}

// SetNillableDiscountID sets the "discount_id" field if the given value is not nil.
func (_u *GroupBuyDiscountUpdateOne) SetNillableDiscountID(v *string) *GroupBuyDiscountUpdateOne {
	if v != nil {
		_u.SetDiscountID(*v)
	}
	return _u
}

// SetMarketPlan sets the "market_plan" field.
func (_u *GroupBuyDiscountUpdateOne) SetMarketPlan(v string) *GroupBuyDiscountUpdateOne {
	_u.mutation.SetMarketPlan(v)
	return _u
}

// SetNillableMarketPlan sets the "market_plan" field if the given value is not nil.
func (_u *GroupBuyDiscountUpdateOne) SetNillableMarketPlan(v *string) *GroupBuyDiscountUpdateOne {
	if v != nil {
		_u.SetMarketPlan(*v)
	}
	return _u
}

// SetMarketExpr sets the "market_expr" field.
func (_u *GroupBuyDiscountUpdateOne) SetMarketExpr(v string) *GroupBuyDiscountUpdateOne {
	_u.mutation.SetMarketExpr(v)
	return _u
}

// SetNillableMarketExpr sets the "market_expr" field if the given value is not nil.
func (_u *GroupBuyDiscountUpdateOne) SetNillableMarketExpr(v *string) *GroupBuyDiscountUpdateOne {
	if v != nil {
		_u.SetMarketExpr(*v)
	}
	return _u
}

// Mutation returns the GroupBuyDiscountMutation object of the builder.
func (_u *GroupBuyDiscountUpdateOne) Mutation() *GroupBuyDiscountMutation {
	return _u.mutation
}

// Where appends a list predicates to the GroupBuyDiscountUpdate builder.
func (_u *GroupBuyDiscountUpdateOne) Where(ps ...predicate.GroupBuyDiscount) *GroupBuyDiscountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GroupBuyDiscountUpdateOne) Select(field string, fields ...string) *GroupBuyDiscountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GroupBuyDiscount entity.
func (_u *GroupBuyDiscountUpdateOne) Save(ctx context.Context) (*GroupBuyDiscount, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupBuyDiscountUpdateOne) SaveX(ctx context.Context) *GroupBuyDiscount {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GroupBuyDiscountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupBuyDiscountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupBuyDiscountUpdateOne) check() error {
	if v, ok := _u.mutation.DiscountID(); ok {
		if err := groupbuydiscount.DiscountIDValidator(v); err != nil {
			return &ValidationError{Name: "discount_id", err: fmt.Errorf(`ent: validator failed for field "GroupBuyDiscount.discount_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MarketPlan(); ok {
		if err := groupbuydiscount.MarketPlanValidator(v); err != nil {
			return &ValidationError{Name: "market_plan", err: fmt.Errorf(`ent: validator failed for field "GroupBuyDiscount.market_plan": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MarketExpr(); ok {
		if err := groupbuydiscount.MarketExprValidator(v); err != nil {
			return &ValidationError{Name: "market_expr", err: fmt.Errorf(`ent: validator failed for field "GroupBuyDiscount.market_expr": %w`, err)}
		}
	}
	return nil
}

func (_u *GroupBuyDiscountUpdateOne) sqlSave(ctx context.Context) (_node *GroupBuyDiscount, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(groupbuydiscount.Table, groupbuydiscount.Columns, sqlgraph.NewFieldSpec(groupbuydiscount.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GroupBuyDiscount.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, groupbuydiscount.FieldID)
		for _, f := range fields {
			if !groupbuydiscount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != groupbuydiscount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(groupbuydiscount.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(groupbuydiscount.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(groupbuydiscount.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(groupbuydiscount.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DiscountID(); ok {
		_spec.SetField(groupbuydiscount.FieldDiscountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.MarketPlan(); ok {
		_spec.SetField(groupbuydiscount.FieldMarketPlan, field.TypeString, value)
	}
	if value, ok := _u.mutation.MarketExpr(); ok {
		_spec.SetField(groupbuydiscount.FieldMarketExpr, field.TypeString, value)
	}
	_node = &GroupBuyDiscount{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groupbuydiscount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
