// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/marketing-platform/internal/groupbuy/data/ent/groupbuyorder"
)

// GroupBuyOrderCreate is the builder for creating a GroupBuyOrder entity.
type GroupBuyOrderCreate struct {
	config
	mutation *GroupBuyOrderMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *GroupBuyOrderCreate) SetCreatedAt(v time.Time) *GroupBuyOrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GroupBuyOrderCreate) SetNillableCreatedAt(v *time.Time) *GroupBuyOrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GroupBuyOrderCreate) SetUpdatedAt(v time.Time) *GroupBuyOrderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GroupBuyOrderCreate) SetNillableUpdatedAt(v *time.Time) *GroupBuyOrderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetOrderID sets the "order_id" field.
func (_c *GroupBuyOrderCreate) SetOrderID(v string) *GroupBuyOrderCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetTeamID sets the "team_id" field.
func (_c *GroupBuyOrderCreate) SetTeamID(v string) *GroupBuyOrderCreate {
	_c.mutation.SetTeamID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *GroupBuyOrderCreate) SetUserID(v int64) *GroupBuyOrderCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetActivityID sets the "activity_id" field.
func (_c *GroupBuyOrderCreate) SetActivityID(v string) *GroupBuyOrderCreate {
	_c.mutation.SetActivityID(v)
	return _c
}

// SetBizID sets the "biz_id" field.
func (_c *GroupBuyOrderCreate) SetBizID(v string) *GroupBuyOrderCreate {
	_c.mutation.SetBizID(v)
	return _c
}

// SetOrderState sets the "order_state" field.
func (_c *GroupBuyOrderCreate) SetOrderState(v int32) *GroupBuyOrderCreate {
	_c.mutation.SetOrderState(v)
	return _c
}

// SetNillableOrderState sets the "order_state" field if the given value is not nil.
func (_c *GroupBuyOrderCreate) SetNillableOrderState(v *int32) *GroupBuyOrderCreate {
	if v != nil {
		_c.SetOrderState(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *GroupBuyOrderCreate) SetID(v uuid.UUID) *GroupBuyOrderCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *GroupBuyOrderCreate) SetNillableID(v *uuid.UUID) *GroupBuyOrderCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the GroupBuyOrderMutation object of the builder.
func (_c *GroupBuyOrderCreate) Mutation() *GroupBuyOrderMutation {
	return _c.mutation
}

// Save creates the GroupBuyOrder in the database.
func (_c *GroupBuyOrderCreate) Save(ctx context.Context) (*GroupBuyOrder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GroupBuyOrderCreate) SaveX(ctx context.Context) *GroupBuyOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupBuyOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupBuyOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GroupBuyOrderCreate) defaults() {
	if _, ok := _c.mutation.OrderState(); !ok {
		v := groupbuyorder.DefaultOrderState
		_c.mutation.SetOrderState(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := groupbuyorder.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GroupBuyOrderCreate) check() error {
	if _, ok := _c.mutation.OrderID(); !ok {
		return &ValidationError{Name: "order_id", err: errors.New(`ent: missing required field "GroupBuyOrder.order_id"`)}
	}
	if v, ok := _c.mutation.OrderID(); ok {
		if err := groupbuyorder.OrderIDValidator(v); err != nil {
			return &ValidationError{Name: "order_id", err: fmt.Errorf(`ent: validator failed for field "GroupBuyOrder.order_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TeamID(); !ok {
		return &ValidationError{Name: "team_id", err: errors.New(`ent: missing required field "GroupBuyOrder.team_id"`)}
	}
	if v, ok := _c.mutation.TeamID(); ok {
		if err := groupbuyorder.TeamIDValidator(v); err != nil {
			return &ValidationError{Name: "team_id", err: fmt.Errorf(`ent: validator failed for field "GroupBuyOrder.team_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "GroupBuyOrder.user_id"`)}
	}
	if _, ok := _c.mutation.ActivityID(); !ok {
		return &ValidationError{Name: "activity_id", err: errors.New(`ent: missing required field "GroupBuyOrder.activity_id"`)}
	}
	if v, ok := _c.mutation.ActivityID(); ok {
		if err := groupbuyorder.ActivityIDValidator(v); err != nil {
			return &ValidationError{Name: "activity_id", err: fmt.Errorf(`ent: validator failed for field "GroupBuyOrder.activity_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BizID(); !ok {
		return &ValidationError{Name: "biz_id", err: errors.New(`ent: missing required field "GroupBuyOrder.biz_id"`)}
	}
	if v, ok := _c.mutation.BizID(); ok {
		if err := groupbuyorder.BizIDValidator(v); err != nil {
			return &ValidationError{Name: "biz_id", err: fmt.Errorf(`ent: validator failed for field "GroupBuyOrder.biz_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OrderState(); !ok {
		return &ValidationError{Name: "order_state", err: errors.New(`ent: missing required field "GroupBuyOrder.order_state"`)}
	}
	return nil
}

func (_c *GroupBuyOrderCreate) sqlSave(ctx context.Context) (*GroupBuyOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GroupBuyOrderCreate) createSpec() (*GroupBuyOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &GroupBuyOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(groupbuyorder.Table, sqlgraph.NewFieldSpec(groupbuyorder.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(groupbuyorder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(groupbuyorder.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.OrderID(); ok {
		_spec.SetField(groupbuyorder.FieldOrderID, field.TypeString, value)
		_node.OrderID = value
	}
	if value, ok := _c.mutation.TeamID(); ok {
		_spec.SetField(groupbuyorder.FieldTeamID, field.TypeString, value)
		_node.TeamID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(groupbuyorder.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.ActivityID(); ok {
		_spec.SetField(groupbuyorder.FieldActivityID, field.TypeString, value)
		_node.ActivityID = value
	}
	if value, ok := _c.mutation.BizID(); ok {
		_spec.SetField(groupbuyorder.FieldBizID, field.TypeString, value)
		_node.BizID = value
	}
	if value, ok := _c.mutation.OrderState(); ok {
		_spec.SetField(groupbuyorder.FieldOrderState, field.TypeInt32, value)
		_node.OrderState = value
	}
	return _node, _spec
}

// GroupBuyOrderCreateBulk is the builder for creating many GroupBuyOrder entities in bulk.
type GroupBuyOrderCreateBulk struct {
	config
	err      error
	builders []*GroupBuyOrderCreate
}

// Save creates the GroupBuyOrder entities in the database.
func (_c *GroupBuyOrderCreateBulk) Save(ctx context.Context) ([]*GroupBuyOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GroupBuyOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupBuyOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GroupBuyOrderCreateBulk) SaveX(ctx context.Context) []*GroupBuyOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupBuyOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupBuyOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
