// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/marketing-platform/internal/groupbuy/data/ent/groupbuyteam"
)

// GroupBuyTeamCreate is the builder for creating a GroupBuyTeam entity.
type GroupBuyTeamCreate struct {
	config
	mutation *GroupBuyTeamMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *GroupBuyTeamCreate) SetCreatedAt(v time.Time) *GroupBuyTeamCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GroupBuyTeamCreate) SetNillableCreatedAt(v *time.Time) *GroupBuyTeamCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GroupBuyTeamCreate) SetUpdatedAt(v time.Time) *GroupBuyTeamCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GroupBuyTeamCreate) SetNillableUpdatedAt(v *time.Time) *GroupBuyTeamCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTeamID sets the "team_id" field.
func (_c *GroupBuyTeamCreate) SetTeamID(v string) *GroupBuyTeamCreate {
	_c.mutation.SetTeamID(v)
	return _c
}

// SetActivityID sets the "activity_id" field.
func (_c *GroupBuyTeamCreate) SetActivityID(v string) *GroupBuyTeamCreate {
	_c.mutation.SetActivityID(v)
	return _c
}

// SetTargetCount sets the "target_count" field.
func (_c *GroupBuyTeamCreate) SetTargetCount(v int32) *GroupBuyTeamCreate {
	_c.mutation.SetTargetCount(v)
	return _c
}

// SetNillableTargetCount sets the "target_count" field if the given value is not nil.
func (_c *GroupBuyTeamCreate) SetNillableTargetCount(v *int32) *GroupBuyTeamCreate {
	if v != nil {
		_c.SetTargetCount(*v)
	}
	return _c
}

// SetCompleteCount sets the "complete_count" field.
func (_c *GroupBuyTeamCreate) SetCompleteCount(v int32) *GroupBuyTeamCreate {
	_c.mutation.SetCompleteCount(v)
	return _c
}

// SetNillableCompleteCount sets the "complete_count" field if the given value is not nil.
func (_c *GroupBuyTeamCreate) SetNillableCompleteCount(v *int32) *GroupBuyTeamCreate {
	if v != nil {
		_c.SetCompleteCount(*v)
	}
	return _c
}

// SetLockCount sets the "lock_count" field.
func (_c *GroupBuyTeamCreate) SetLockCount(v int32) *GroupBuyTeamCreate {
	_c.mutation.SetLockCount(v)
	return _c
}

// SetNillableLockCount sets the "lock_count" field if the given value is not nil.
func (_c *GroupBuyTeamCreate) SetNillableLockCount(v *int32) *GroupBuyTeamCreate {
	if v != nil {
		_c.SetLockCount(*v)
	}
	return _c
}

// SetTeamState sets the "team_state" field.
func (_c *GroupBuyTeamCreate) SetTeamState(v int32) *GroupBuyTeamCreate {
	_c.mutation.SetTeamState(v)
	return _c
}

// SetNillableTeamState sets the "team_state" field if the given value is not nil.
func (_c *GroupBuyTeamCreate) SetNillableTeamState(v *int32) *GroupBuyTeamCreate {
	if v != nil {
		_c.SetTeamState(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *GroupBuyTeamCreate) SetID(v uuid.UUID) *GroupBuyTeamCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *GroupBuyTeamCreate) SetNillableID(v *uuid.UUID) *GroupBuyTeamCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the GroupBuyTeamMutation object of the builder.
func (_c *GroupBuyTeamCreate) Mutation() *GroupBuyTeamMutation {
	return _c.mutation
}

// Save creates the GroupBuyTeam in the database.
func (_c *GroupBuyTeamCreate) Save(ctx context.Context) (*GroupBuyTeam, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GroupBuyTeamCreate) SaveX(ctx context.Context) *GroupBuyTeam {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupBuyTeamCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupBuyTeamCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GroupBuyTeamCreate) defaults() {
	if _, ok := _c.mutation.TargetCount(); !ok {
		v := groupbuyteam.DefaultTargetCount
		_c.mutation.SetTargetCount(v)
	}
	if _, ok := _c.mutation.CompleteCount(); !ok {
		v := groupbuyteam.DefaultCompleteCount
		_c.mutation.SetCompleteCount(v)
	}
	if _, ok := _c.mutation.LockCount(); !ok {
		v := groupbuyteam.DefaultLockCount
		_c.mutation.SetLockCount(v)
	}
	if _, ok := _c.mutation.TeamState(); !ok {
		v := groupbuyteam.DefaultTeamState
		_c.mutation.SetTeamState(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := groupbuyteam.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GroupBuyTeamCreate) check() error {
	if _, ok := _c.mutation.TeamID(); !ok {
		return &ValidationError{Name: "team_id", err: errors.New(`ent: missing required field "GroupBuyTeam.team_id"`)}
	}
	if v, ok := _c.mutation.TeamID(); ok {
		if err := groupbuyteam.TeamIDValidator(v); err != nil {
			return &ValidationError{Name: "team_id", err: fmt.Errorf(`ent: validator failed for field "GroupBuyTeam.team_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActivityID(); !ok {
		return &ValidationError{Name: "activity_id", err: errors.New(`ent: missing required field "GroupBuyTeam.activity_id"`)}
	}
	if v, ok := _c.mutation.ActivityID(); ok {
		if err := groupbuyteam.ActivityIDValidator(v); err != nil {
			return &ValidationError{Name: "activity_id", err: fmt.Errorf(`ent: validator failed for field "GroupBuyTeam.activity_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TargetCount(); !ok {
		return &ValidationError{Name: "target_count", err: errors.New(`ent: missing required field "GroupBuyTeam.target_count"`)}
	}
	if _, ok := _c.mutation.CompleteCount(); !ok {
		return &ValidationError{Name: "complete_count", err: errors.New(`ent: missing required field "GroupBuyTeam.complete_count"`)}
	}
	if _, ok := _c.mutation.LockCount(); !ok {
		return &ValidationError{Name: "lock_count", err: errors.New(`ent: missing required field "GroupBuyTeam.lock_count"`)}
	}
	if _, ok := _c.mutation.TeamState(); !ok {
		return &ValidationError{Name: "team_state", err: errors.New(`ent: missing required field "GroupBuyTeam.team_state"`)}
	}
	return nil
}

func (_c *GroupBuyTeamCreate) sqlSave(ctx context.Context) (*GroupBuyTeam, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GroupBuyTeamCreate) createSpec() (*GroupBuyTeam, *sqlgraph.CreateSpec) {
	var (
		_node = &GroupBuyTeam{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(groupbuyteam.Table, sqlgraph.NewFieldSpec(groupbuyteam.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(groupbuyteam.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(groupbuyteam.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.TeamID(); ok {
		_spec.SetField(groupbuyteam.FieldTeamID, field.TypeString, value)
		_node.TeamID = value
	}
	if value, ok := _c.mutation.ActivityID(); ok {
		_spec.SetField(groupbuyteam.FieldActivityID, field.TypeString, value)
		_node.ActivityID = value
	}
	if value, ok := _c.mutation.TargetCount(); ok {
		_spec.SetField(groupbuyteam.FieldTargetCount, field.TypeInt32, value)
		_node.TargetCount = value
	}
	if value, ok := _c.mutation.CompleteCount(); ok {
		_spec.SetField(groupbuyteam.FieldCompleteCount, field.TypeInt32, value)
		_node.CompleteCount = value
	}
	if value, ok := _c.mutation.LockCount(); ok {
		_spec.SetField(groupbuyteam.FieldLockCount, field.TypeInt32, value)
		_node.LockCount = value
	}
	if value, ok := _c.mutation.TeamState(); ok {
		_spec.SetField(groupbuyteam.FieldTeamState, field.TypeInt32, value)
		_node.TeamState = value
	}
	return _node, _spec
}

// GroupBuyTeamCreateBulk is the builder for creating many GroupBuyTeam entities in bulk.
type GroupBuyTeamCreateBulk struct {
	config
	err      error
	builders []*GroupBuyTeamCreate
}

// Save creates the GroupBuyTeam entities in the database.
func (_c *GroupBuyTeamCreateBulk) Save(ctx context.Context) ([]*GroupBuyTeam, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GroupBuyTeam, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupBuyTeamMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GroupBuyTeamCreateBulk) SaveX(ctx context.Context) []*GroupBuyTeam {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupBuyTeamCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupBuyTeamCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
