// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/marketing-platform/internal/groupbuy/data/ent/groupbuyactivity"
)

// GroupBuyActivity is the model entity for the GroupBuyActivity schema.
type GroupBuyActivity struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// ActivityID holds the value of the "activity_id" field.
	ActivityID string `json:"activity_id,omitempty"`
	// ActivityName holds the value of the "activity_name" field.
	ActivityName string `json:"activity_name,omitempty"`
	// DiscountID holds the value of the "discount_id" field.
	DiscountID string `json:"discount_id,omitempty"`
	// GroupType holds the value of the "group_type" field.
	GroupType int32 `json:"group_type,omitempty"`
	// TargetCount holds the value of the "target_count" field.
	TargetCount int32 `json:"target_count,omitempty"`
	// ValidTime holds the value of the "valid_time" field.
	ValidTime int32 `json:"valid_time,omitempty"`
	// TagID holds the value of the "tag_id" field.
	TagID *string `json:"tag_id,omitempty"`
	// ActivityState holds the value of the "activity_state" field.
	ActivityState int32 `json:"activity_state,omitempty"`
	selectValues  sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GroupBuyActivity) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case groupbuyactivity.FieldGroupType, groupbuyactivity.FieldTargetCount, groupbuyactivity.FieldValidTime, groupbuyactivity.FieldActivityState:
			values[i] = new(sql.NullInt64)
		case groupbuyactivity.FieldActivityID, groupbuyactivity.FieldActivityName, groupbuyactivity.FieldDiscountID, groupbuyactivity.FieldTagID:
			values[i] = new(sql.NullString)
		case groupbuyactivity.FieldCreatedAt, groupbuyactivity.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case groupbuyactivity.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GroupBuyActivity fields.
func (_m *GroupBuyActivity) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case groupbuyactivity.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case groupbuyactivity.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case groupbuyactivity.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case groupbuyactivity.FieldActivityID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field activity_id", values[i])
			} else if value.Valid {
				_m.ActivityID = value.String
			}
		case groupbuyactivity.FieldActivityName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field activity_name", values[i])
			} else if value.Valid {
				_m.ActivityName = value.String
			}
		case groupbuyactivity.FieldDiscountID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field discount_id", values[i])
			} else if value.Valid {
				_m.DiscountID = value.String
			}
		case groupbuyactivity.FieldGroupType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_type", values[i])
			} else if value.Valid {
				_m.GroupType = int32(value.Int64)
			}
		case groupbuyactivity.FieldTargetCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field target_count", values[i])
			} else if value.Valid {
				_m.TargetCount = int32(value.Int64)
			}
		case groupbuyactivity.FieldValidTime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field valid_time", values[i])
			} else if value.Valid {
				_m.ValidTime = int32(value.Int64)
			}
		case groupbuyactivity.FieldTagID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tag_id", values[i])
			} else if value.Valid {
				_m.TagID = new(string)
				*_m.TagID = value.String
			}
		case groupbuyactivity.FieldActivityState:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field activity_state", values[i])
			} else if value.Valid {
				_m.ActivityState = int32(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GroupBuyActivity.
// This includes values selected through modifiers, order, etc.
func (_m *GroupBuyActivity) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this GroupBuyActivity.
// Note that you need to call GroupBuyActivity.Unwrap() before calling this method if this GroupBuyActivity
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GroupBuyActivity) Update() *GroupBuyActivityUpdateOne {
	return NewGroupBuyActivityClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GroupBuyActivity entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GroupBuyActivity) Unwrap() *GroupBuyActivity {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GroupBuyActivity is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GroupBuyActivity) String() string {
	var builder strings.Builder
	builder.WriteString("GroupBuyActivity(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("activity_id=")
	builder.WriteString(_m.ActivityID)
	builder.WriteString(", ")
	builder.WriteString("activity_name=")
	builder.WriteString(_m.ActivityName)
	builder.WriteString(", ")
	builder.WriteString("discount_id=")
	builder.WriteString(_m.DiscountID)
	builder.WriteString(", ")
	builder.WriteString("group_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupType))
	builder.WriteString(", ")
	builder.WriteString("target_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetCount))
	builder.WriteString(", ")
	builder.WriteString("valid_time=")
	builder.WriteString(fmt.Sprintf("%v", _m.ValidTime))
	builder.WriteString(", ")
	if v := _m.TagID; v != nil {
		builder.WriteString("tag_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("activity_state=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActivityState))
	builder.WriteByte(')')
	return builder.String()
}

// GroupBuyActivities is a parsable slice of GroupBuyActivity.
type GroupBuyActivities []*GroupBuyActivity
