// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/marketing-platform/internal/groupbuy/data/ent/groupbuyactivity"
	"github.com/marketing-platform/internal/groupbuy/data/ent/predicate"
)

// GroupBuyActivityUpdate is the builder for updating GroupBuyActivity entities.
type GroupBuyActivityUpdate struct {
	config
	hooks    []Hook
	mutation *GroupBuyActivityMutation
}

// Where appends a list predicates to the GroupBuyActivityUpdate builder.
func (_u *GroupBuyActivityUpdate) Where(ps ...predicate.GroupBuyActivity) *GroupBuyActivityUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *GroupBuyActivityUpdate) SetCreatedAt(v time.Time) *GroupBuyActivityUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *GroupBuyActivityUpdate) SetNillableCreatedAt(v *time.Time) *GroupBuyActivityUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *GroupBuyActivityUpdate) ClearCreatedAt() *GroupBuyActivityUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GroupBuyActivityUpdate) SetUpdatedAt(v time.Time) *GroupBuyActivityUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *GroupBuyActivityUpdate) SetNillableUpdatedAt(v *time.Time) *GroupBuyActivityUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *GroupBuyActivityUpdate) ClearUpdatedAt() *GroupBuyActivityUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetActivityID sets the "activity_id" field.
func (_u *GroupBuyActivityUpdate) SetActivityID(v string) *GroupBuyActivityUpdate {
	_u.mutation.SetActivityID(v)
	return _u
}

// SetNillableActivityID sets the "activity_id" field if the given value is not nil.
func (_u *GroupBuyActivityUpdate) SetNillableActivityID(v *string) *GroupBuyActivityUpdate {
	if v != nil {
		_u.SetActivityID(*v)
	}
	return _u
}

// SetActivityName sets the "activity_name" field.
func (_u *GroupBuyActivityUpdate) SetActivityName(v string) *GroupBuyActivityUpdate {
	_u.mutation.SetActivityName(v)
	return _u
}

// SetNillableActivityName sets the "activity_name" field if the given value is not nil.
func (_u *GroupBuyActivityUpdate) SetNillableActivityName(v *string) *GroupBuyActivityUpdate {
	if v != nil {
		_u.SetActivityName(*v)
	}
	return _u
}

// SetDiscountID sets the "discount_id" field.
func (_u *GroupBuyActivityUpdate) SetDiscountID(v string) *GroupBuyActivityUpdate {
	_u.mutation.SetDiscountID(v)
	return _u
}

// SetNillableDiscountID sets the "discount_id" field if the given value is not nil.
func (_u *GroupBuyActivityUpdate) SetNillableDiscountID(v *string) *GroupBuyActivityUpdate {
	if v != nil {
		_u.SetDiscountID(*v)
	}
	return _u
}

// SetGroupType sets the "group_type" field.
func (_u *GroupBuyActivityUpdate) SetGroupType(v int32) *GroupBuyActivityUpdate {
	_u.mutation.ResetGroupType()
	_u.mutation.SetGroupType(v)
	return _u
}

// SetNillableGroupType sets the "group_type" field if the given value is not nil.
func (_u *GroupBuyActivityUpdate) SetNillableGroupType(v *int32) *GroupBuyActivityUpdate {
	if v != nil {
		_u.SetGroupType(*v)
	}
	return _u
}

// AddGroupType adds value to the "group_type" field.
func (_u *GroupBuyActivityUpdate) AddGroupType(v int32) *GroupBuyActivityUpdate {
	_u.mutation.AddGroupType(v)
	return _u
}

// SetTargetCount sets the "target_count" field.
func (_u *GroupBuyActivityUpdate) SetTargetCount(v int32) *GroupBuyActivityUpdate {
	_u.mutation.ResetTargetCount()
	_u.mutation.SetTargetCount(v)
	return _u
}

// SetNillableTargetCount sets the "target_count" field if the given value is not nil.
func (_u *GroupBuyActivityUpdate) SetNillableTargetCount(v *int32) *GroupBuyActivityUpdate {
	if v != nil {
		_u.SetTargetCount(*v)
	}
	return _u
}

// AddTargetCount adds value to the "target_count" field.
func (_u *GroupBuyActivityUpdate) AddTargetCount(v int32) *GroupBuyActivityUpdate {
	_u.mutation.AddTargetCount(v)
	return _u
}

// SetValidTime sets the "valid_time" field.
func (_u *GroupBuyActivityUpdate) SetValidTime(v int32) *GroupBuyActivityUpdate {
	_u.mutation.ResetValidTime()
	_u.mutation.SetValidTime(v)
	return _u
}

// SetNillableValidTime sets the "valid_time" field if the given value is not nil.
func (_u *GroupBuyActivityUpdate) SetNillableValidTime(v *int32) *GroupBuyActivityUpdate {
	if v != nil {
		_u.SetValidTime(*v)
	}
	return _u
}

// AddValidTime adds value to the "valid_time" field.
func (_u *GroupBuyActivityUpdate) AddValidTime(v int32) *GroupBuyActivityUpdate {
	_u.mutation.AddValidTime(v)
	return _u
}

// SetTagID sets the "tag_id" field.
func (_u *GroupBuyActivityUpdate) SetTagID(v string) *GroupBuyActivityUpdate {
	_u.mutation.SetTagID(v)
	return _u
}

// SetNillableTagID sets the "tag_id" field if the given value is not nil.
func (_u *GroupBuyActivityUpdate) SetNillableTagID(v *string) *GroupBuyActivityUpdate {
	if v != nil {
		_u.SetTagID(*v)
	}
	return _u
}

// ClearTagID clears the value of the "tag_id" field.
func (_u *GroupBuyActivityUpdate) ClearTagID() *GroupBuyActivityUpdate {
	_u.mutation.ClearTagID()
	return _u
}

// SetActivityState sets the "activity_state" field.
func (_u *GroupBuyActivityUpdate) SetActivityState(v int32) *GroupBuyActivityUpdate {
	_u.mutation.ResetActivityState()
	_u.mutation.SetActivityState(v)
	return _u
}

// SetNillableActivityState sets the "activity_state" field if the given value is not nil.
func (_u *GroupBuyActivityUpdate) SetNillableActivityState(v *int32) *GroupBuyActivityUpdate {
	if v != nil {
		_u.SetActivityState(*v)
	}
	return _u
}

// AddActivityState adds value to the "activity_state" field.
func (_u *GroupBuyActivityUpdate) AddActivityState(v int32) *GroupBuyActivityUpdate {
	_u.mutation.AddActivityState(v)
	return _u
}

// Mutation returns the GroupBuyActivityMutation object of the builder.
func (_u *GroupBuyActivityUpdate) Mutation() *GroupBuyActivityMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GroupBuyActivityUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupBuyActivityUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GroupBuyActivityUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupBuyActivityUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupBuyActivityUpdate) check() error {
	if v, ok := _u.mutation.ActivityID(); ok {
		if err := groupbuyactivity.ActivityIDValidator(v); err != nil {
			return &ValidationError{Name: "activity_id", err: fmt.Errorf(`ent: validator failed for field "GroupBuyActivity.activity_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActivityName(); ok {
		if err := groupbuyactivity.ActivityNameValidator(v); err != nil {
			return &ValidationError{Name: "activity_name", err: fmt.Errorf(`ent: validator failed for field "GroupBuyActivity.activity_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DiscountID(); ok {
		if err := groupbuyactivity.DiscountIDValidator(v); err != nil {
			return &ValidationError{Name: "discount_id", err: fmt.Errorf(`ent: validator failed for field "GroupBuyActivity.discount_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TagID(); ok {
		if err := groupbuyactivity.TagIDValidator(v); err != nil {
			return &ValidationError{Name: "tag_id", err: fmt.Errorf(`ent: validator failed for field "GroupBuyActivity.tag_id": %w`, err)}
		}
	}
	return nil
}

func (_u *GroupBuyActivityUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(groupbuyactivity.Table, groupbuyactivity.Columns, sqlgraph.NewFieldSpec(groupbuyactivity.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(groupbuyactivity.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(groupbuyactivity.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(groupbuyactivity.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(groupbuyactivity.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ActivityID(); ok {
		_spec.SetField(groupbuyactivity.FieldActivityID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActivityName(); ok {
		_spec.SetField(groupbuyactivity.FieldActivityName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DiscountID(); ok {
		_spec.SetField(groupbuyactivity.FieldDiscountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GroupType(); ok {
		_spec.SetField(groupbuyactivity.FieldGroupType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedGroupType(); ok {
		_spec.AddField(groupbuyactivity.FieldGroupType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.TargetCount(); ok {
		_spec.SetField(groupbuyactivity.FieldTargetCount, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedTargetCount(); ok {
		_spec.AddField(groupbuyactivity.FieldTargetCount, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.ValidTime(); ok {
		_spec.SetField(groupbuyactivity.FieldValidTime, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedValidTime(); ok {
		_spec.AddField(groupbuyactivity.FieldValidTime, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.TagID(); ok {
		_spec.SetField(groupbuyactivity.FieldTagID, field.TypeString, value)
	}
	if _u.mutation.TagIDCleared() {
		_spec.ClearField(groupbuyactivity.FieldTagID, field.TypeString)
	}
	if value, ok := _u.mutation.ActivityState(); ok {
		_spec.SetField(groupbuyactivity.FieldActivityState, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedActivityState(); ok {
		_spec.AddField(groupbuyactivity.FieldActivityState, field.TypeInt32, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groupbuyactivity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GroupBuyActivityUpdateOne is the builder for updating a single GroupBuyActivity entity.
type GroupBuyActivityUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GroupBuyActivityMutation
}

// SetCreatedAt sets the "created_at" field.
func (_u *GroupBuyActivityUpdateOne) SetCreatedAt(v time.Time) *GroupBuyActivityUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *GroupBuyActivityUpdateOne) SetNillableCreatedAt(v *time.Time) *GroupBuyActivityUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *GroupBuyActivityUpdateOne) ClearCreatedAt() *GroupBuyActivityUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GroupBuyActivityUpdateOne) SetUpdatedAt(v time.Time) *GroupBuyActivityUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *GroupBuyActivityUpdateOne) SetNillableUpdatedAt(v *time.Time) *GroupBuyActivityUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *GroupBuyActivityUpdateOne) ClearUpdatedAt() *GroupBuyActivityUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetActivityID sets the "activity_id" field.
func (_u *GroupBuyActivityUpdateOne) SetActivityID(v string) *GroupBuyActivityUpdateOne {
	_u.mutation.SetActivityID(v)
	return _u
}

// SetNillableActivityID sets the "activity_id" field if the given value is not nil.
func (_u *GroupBuyActivityUpdateOne) SetNillableActivityID(v *string) *GroupBuyActivityUpdateOne {
	if v != nil {
		_u.SetActivityID(*v)
	}
	return _u
}

// SetActivityName sets the "activity_name" field.
func (_u *GroupBuyActivityUpdateOne) SetActivityName(v string) *GroupBuyActivityUpdateOne {
	_u.mutation.SetActivityName(v)
	return _u
}

// SetNillableActivityName sets the "activity_name" field if the given value is not nil.
func (_u *GroupBuyActivityUpdateOne) SetNillableActivityName(v *string) *GroupBuyActivityUpdateOne {
	if v != nil {
		_u.SetActivityName(*v)
	}
	return _u
}

// SetDiscountID sets the "discount_id" field.
func (_u *GroupBuyActivityUpdateOne) SetDiscountID(v string) *GroupBuyActivityUpdateOne {
	_u.mutation.SetDiscountID(v)
	return _u
}

// SetNillableDiscountID sets the "discount_id" field if the given value is not nil.
func (_u *GroupBuyActivityUpdateOne) SetNillableDiscountID(v *string) *GroupBuyActivityUpdateOne {
	if v != nil {
		_u.SetDiscountID(*v)
	}
	return _u
}

// SetGroupType sets the "group_type" field.
func (_u *GroupBuyActivityUpdateOne) SetGroupType(v int32) *GroupBuyActivityUpdateOne {
	_u.mutation.ResetGroupType()
	_u.mutation.SetGroupType(v)
	return _u
}

// SetNillableGroupType sets the "group_type" field if the given value is not nil.
func (_u *GroupBuyActivityUpdateOne) SetNillableGroupType(v *int32) *GroupBuyActivityUpdateOne {
	if v != nil {
		_u.SetGroupType(*v)
	}
	return _u
}

// AddGroupType adds value to the "group_type" field.
func (_u *GroupBuyActivityUpdateOne) AddGroupType(v int32) *GroupBuyActivityUpdateOne {
	_u.mutation.AddGroupType(v)
	return _u
}

// SetTargetCount sets the "target_count" field.
func (_u *GroupBuyActivityUpdateOne) SetTargetCount(v int32) *GroupBuyActivityUpdateOne {
	_u.mutation.ResetTargetCount()
	_u.mutation.SetTargetCount(v)
	return _u
}

// SetNillableTargetCount sets the "target_count" field if the given value is not nil.
func (_u *GroupBuyActivityUpdateOne) SetNillableTargetCount(v *int32) *GroupBuyActivityUpdateOne {
	if v != nil {
		_u.SetTargetCount(*v)
	}
	return _u
}

// AddTargetCount adds value to the "target_count" field.
func (_u *GroupBuyActivityUpdateOne) AddTargetCount(v int32) *GroupBuyActivityUpdateOne {
	_u.mutation.AddTargetCount(v)
	return _u
}

// SetValidTime sets the "valid_time" field.
func (_u *GroupBuyActivityUpdateOne) SetValidTime(v int32) *GroupBuyActivityUpdateOne {
	_u.mutation.ResetValidTime()
	_u.mutation.SetValidTime(v)
	return _u
}

// SetNillableValidTime sets the "valid_time" field if the given value is not nil.
func (_u *GroupBuyActivityUpdateOne) SetNillableValidTime(v *int32) *GroupBuyActivityUpdateOne {
	if v != nil {
		_u.SetValidTime(*v)
	}
	return _u
}

// AddValidTime adds value to the "valid_time" field.
func (_u *GroupBuyActivityUpdateOne) AddValidTime(v int32) *GroupBuyActivityUpdateOne {
	_u.mutation.AddValidTime(v)
	return _u
}

// SetTagID sets the "tag_id" field.
func (_u *GroupBuyActivityUpdateOne) SetTagID(v string) *GroupBuyActivityUpdateOne {
	_u.mutation.SetTagID(v)
	return _u
}

// SetNillableTagID sets the "tag_id" field if the given value is not nil.
func (_u *GroupBuyActivityUpdateOne) SetNillableTagID(v *string) *GroupBuyActivityUpdateOne {
	if v != nil {
		_u.SetTagID(*v)
	}
	return _u
}

// ClearTagID clears the value of the "tag_id" field.
func (_u *GroupBuyActivityUpdateOne) ClearTagID() *GroupBuyActivityUpdateOne {
	_u.mutation.ClearTagID()
	return _u
}

// SetActivityState sets the "activity_state" field.
func (_u *GroupBuyActivityUpdateOne) SetActivityState(v int32) *GroupBuyActivityUpdateOne {
	_u.mutation.ResetActivityState()
	_u.mutation.SetActivityState(v)
	return _u
}

// SetNillableActivityState sets the "activity_state" field if the given value is not nil.
func (_u *GroupBuyActivityUpdateOne) SetNillableActivityState(v *int32) *GroupBuyActivityUpdateOne {
	if v != nil {
		_u.SetActivityState(*v)
	}
	return _u
}

// AddActivityState adds value to the "activity_state" field.
func (_u *GroupBuyActivityUpdateOne) AddActivityState(v int32) *GroupBuyActivityUpdateOne {
	_u.mutation.AddActivityState(v)
	return _u
}

// Mutation returns the GroupBuyActivityMutation object of the builder.
func (_u *GroupBuyActivityUpdateOne) Mutation() *GroupBuyActivityMutation {
	return _u.mutation
}

// Where appends a list predicates to the GroupBuyActivityUpdate builder.
func (_u *GroupBuyActivityUpdateOne) Where(ps ...predicate.GroupBuyActivity) *GroupBuyActivityUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GroupBuyActivityUpdateOne) Select(field string, fields ...string) *GroupBuyActivityUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GroupBuyActivity entity.
func (_u *GroupBuyActivityUpdateOne) Save(ctx context.Context) (*GroupBuyActivity, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupBuyActivityUpdateOne) SaveX(ctx context.Context) *GroupBuyActivity {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GroupBuyActivityUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupBuyActivityUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupBuyActivityUpdateOne) check() error {
	if v, ok := _u.mutation.ActivityID(); ok {
		if err := groupbuyactivity.ActivityIDValidator(v); err != nil {
			return &ValidationError{Name: "activity_id", err: fmt.Errorf(`ent: validator failed for field "GroupBuyActivity.activity_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActivityName(); ok {
		if err := groupbuyactivity.ActivityNameValidator(v); err != nil {
			return &ValidationError{Name: "activity_name", err: fmt.Errorf(`ent: validator failed for field "GroupBuyActivity.activity_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DiscountID(); ok {
		if err := groupbuyactivity.DiscountIDValidator(v); err != nil {
			return &ValidationError{Name: "discount_id", err: fmt.Errorf(`ent: validator failed for field "GroupBuyActivity.discount_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TagID(); ok {
		if err := groupbuyactivity.TagIDValidator(v); err != nil {
			return &ValidationError{Name: "tag_id", err: fmt.Errorf(`ent: validator failed for field "GroupBuyActivity.tag_id": %w`, err)}
		}
	}
	return nil
}

func (_u *GroupBuyActivityUpdateOne) sqlSave(ctx context.Context) (_node *GroupBuyActivity, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(groupbuyactivity.Table, groupbuyactivity.Columns, sqlgraph.NewFieldSpec(groupbuyactivity.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GroupBuyActivity.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, groupbuyactivity.FieldID)
		for _, f := range fields {
			if !groupbuyactivity.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != groupbuyactivity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(groupbuyactivity.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(groupbuyactivity.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(groupbuyactivity.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(groupbuyactivity.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ActivityID(); ok {
		_spec.SetField(groupbuyactivity.FieldActivityID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActivityName(); ok {
		_spec.SetField(groupbuyactivity.FieldActivityName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DiscountID(); ok {
		_spec.SetField(groupbuyactivity.FieldDiscountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GroupType(); ok {
		_spec.SetField(groupbuyactivity.FieldGroupType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedGroupType(); ok {
		_spec.AddField(groupbuyactivity.FieldGroupType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.TargetCount(); ok {
		_spec.SetField(groupbuyactivity.FieldTargetCount, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedTargetCount(); ok {
		_spec.AddField(groupbuyactivity.FieldTargetCount, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.ValidTime(); ok {
		_spec.SetField(groupbuyactivity.FieldValidTime, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedValidTime(); ok {
		_spec.AddField(groupbuyactivity.FieldValidTime, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.TagID(); ok {
		_spec.SetField(groupbuyactivity.FieldTagID, field.TypeString, value)
	}
	if _u.mutation.TagIDCleared() {
		_spec.ClearField(groupbuyactivity.FieldTagID, field.TypeString)
	}
	if value, ok := _u.mutation.ActivityState(); ok {
		_spec.SetField(groupbuyactivity.FieldActivityState, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedActivityState(); ok {
		_spec.AddField(groupbuyactivity.FieldActivityState, field.TypeInt32, value)
	}
	_node = &GroupBuyActivity{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groupbuyactivity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
