// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/marketing-platform/internal/groupbuy/data/ent/notifytask"
)

// NotifyTask is the model entity for the NotifyTask schema.
type NotifyTask struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// TaskID holds the value of the "task_id" field.
	TaskID string `json:"task_id,omitempty"`
	// NotifyType holds the value of the "notify_type" field.
	NotifyType string `json:"notify_type,omitempty"`
	// NotifyStatus holds the value of the "notify_status" field.
	NotifyStatus int32 `json:"notify_status,omitempty"`
	// NotifyURL holds the value of the "notify_url" field.
	NotifyURL *string `json:"notify_url,omitempty"`
	// NotifyData holds the value of the "notify_data" field.
	NotifyData *string `json:"notify_data,omitempty"`
	// UUID holds the value of the "uuid" field.
	UUID string `json:"uuid,omitempty"`
	// RetryCount holds the value of the "retry_count" field.
	RetryCount int32 `json:"retry_count,omitempty"`
	// MaxRetry holds the value of the "max_retry" field.
	MaxRetry int32 `json:"max_retry,omitempty"`
	// NextTime holds the value of the "next_time" field.
	NextTime     int64 `json:"next_time,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NotifyTask) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case notifytask.FieldNotifyStatus, notifytask.FieldRetryCount, notifytask.FieldMaxRetry, notifytask.FieldNextTime:
			values[i] = new(sql.NullInt64)
		case notifytask.FieldTaskID, notifytask.FieldNotifyType, notifytask.FieldNotifyURL, notifytask.FieldNotifyData, notifytask.FieldUUID:
			values[i] = new(sql.NullString)
		case notifytask.FieldCreatedAt, notifytask.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case notifytask.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NotifyTask fields.
func (_m *NotifyTask) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case notifytask.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case notifytask.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case notifytask.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case notifytask.FieldTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value.Valid {
				_m.TaskID = value.String
			}
		case notifytask.FieldNotifyType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notify_type", values[i])
			} else if value.Valid {
				_m.NotifyType = value.String
			}
		case notifytask.FieldNotifyStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field notify_status", values[i])
			} else if value.Valid {
				_m.NotifyStatus = int32(value.Int64)
			}
		case notifytask.FieldNotifyURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notify_url", values[i])
			} else if value.Valid {
				_m.NotifyURL = new(string)
				*_m.NotifyURL = value.String
			}
		case notifytask.FieldNotifyData:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notify_data", values[i])
			} else if value.Valid {
				_m.NotifyData = new(string)
				*_m.NotifyData = value.String
			}
		case notifytask.FieldUUID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field uuid", values[i])
			} else if value.Valid {
				_m.UUID = value.String
			}
		case notifytask.FieldRetryCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retry_count", values[i])
			} else if value.Valid {
				_m.RetryCount = int32(value.Int64)
			}
		case notifytask.FieldMaxRetry:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_retry", values[i])
			} else if value.Valid {
				_m.MaxRetry = int32(value.Int64)
			}
		case notifytask.FieldNextTime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field next_time", values[i])
			} else if value.Valid {
				_m.NextTime = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NotifyTask.
// This includes values selected through modifiers, order, etc.
func (_m *NotifyTask) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this NotifyTask.
// Note that you need to call NotifyTask.Unwrap() before calling this method if this NotifyTask
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *NotifyTask) Update() *NotifyTaskUpdateOne {
	return NewNotifyTaskClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the NotifyTask entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *NotifyTask) Unwrap() *NotifyTask {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: NotifyTask is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *NotifyTask) String() string {
	var builder strings.Builder
	builder.WriteString("NotifyTask(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("task_id=")
	builder.WriteString(_m.TaskID)
	builder.WriteString(", ")
	builder.WriteString("notify_type=")
	builder.WriteString(_m.NotifyType)
	builder.WriteString(", ")
	builder.WriteString("notify_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.NotifyStatus))
	builder.WriteString(", ")
	if v := _m.NotifyURL; v != nil {
		builder.WriteString("notify_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.NotifyData; v != nil {
		builder.WriteString("notify_data=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("uuid=")
	builder.WriteString(_m.UUID)
	builder.WriteString(", ")
	builder.WriteString("retry_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RetryCount))
	builder.WriteString(", ")
	builder.WriteString("max_retry=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxRetry))
	builder.WriteString(", ")
	builder.WriteString("next_time=")
	builder.WriteString(fmt.Sprintf("%v", _m.NextTime))
	builder.WriteByte(')')
	return builder.String()
}

// NotifyTasks is a parsable slice of NotifyTask.
type NotifyTasks []*NotifyTask
