// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/marketing-platform/internal/groupbuy/data/ent/notifytask"
)

// NotifyTaskCreate is the builder for creating a NotifyTask entity.
type NotifyTaskCreate struct {
	config
	mutation *NotifyTaskMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *NotifyTaskCreate) SetCreatedAt(v time.Time) *NotifyTaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NotifyTaskCreate) SetNillableCreatedAt(v *time.Time) *NotifyTaskCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *NotifyTaskCreate) SetUpdatedAt(v time.Time) *NotifyTaskCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *NotifyTaskCreate) SetNillableUpdatedAt(v *time.Time) *NotifyTaskCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTaskID sets the "task_id" field.
func (_c *NotifyTaskCreate) SetTaskID(v string) *NotifyTaskCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetNotifyType sets the "notify_type" field.
func (_c *NotifyTaskCreate) SetNotifyType(v string) *NotifyTaskCreate {
	_c.mutation.SetNotifyType(v)
	return _c
}

// SetNotifyStatus sets the "notify_status" field.
func (_c *NotifyTaskCreate) SetNotifyStatus(v int32) *NotifyTaskCreate {
	_c.mutation.SetNotifyStatus(v)
	return _c
}

// SetNillableNotifyStatus sets the "notify_status" field if the given value is not nil.
func (_c *NotifyTaskCreate) SetNillableNotifyStatus(v *int32) *NotifyTaskCreate {
	if v != nil {
		_c.SetNotifyStatus(*v)
	}
	return _c
}

// SetNotifyURL sets the "notify_url" field.
func (_c *NotifyTaskCreate) SetNotifyURL(v string) *NotifyTaskCreate {
	_c.mutation.SetNotifyURL(v)
	return _c
}

// SetNillableNotifyURL sets the "notify_url" field if the given value is not nil.
func (_c *NotifyTaskCreate) SetNillableNotifyURL(v *string) *NotifyTaskCreate {
	if v != nil {
		_c.SetNotifyURL(*v)
	}
	return _c
}

// SetNotifyData sets the "notify_data" field.
func (_c *NotifyTaskCreate) SetNotifyData(v string) *NotifyTaskCreate {
	_c.mutation.SetNotifyData(v)
	return _c
}

// SetNillableNotifyData sets the "notify_data" field if the given value is not nil.
func (_c *NotifyTaskCreate) SetNillableNotifyData(v *string) *NotifyTaskCreate {
	if v != nil {
		_c.SetNotifyData(*v)
	}
	return _c
}

// SetUUID sets the "uuid" field.
func (_c *NotifyTaskCreate) SetUUID(v string) *NotifyTaskCreate {
	_c.mutation.SetUUID(v)
	return _c
}

// SetRetryCount sets the "retry_count" field.
func (_c *NotifyTaskCreate) SetRetryCount(v int32) *NotifyTaskCreate {
	_c.mutation.SetRetryCount(v)
	return _c
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_c *NotifyTaskCreate) SetNillableRetryCount(v *int32) *NotifyTaskCreate {
	if v != nil {
		_c.SetRetryCount(*v)
	}
	return _c
}

// SetMaxRetry sets the "max_retry" field.
func (_c *NotifyTaskCreate) SetMaxRetry(v int32) *NotifyTaskCreate {
	_c.mutation.SetMaxRetry(v)
	return _c
}

// SetNillableMaxRetry sets the "max_retry" field if the given value is not nil.
func (_c *NotifyTaskCreate) SetNillableMaxRetry(v *int32) *NotifyTaskCreate {
	if v != nil {
		_c.SetMaxRetry(*v)
	}
	return _c
}

// SetNextTime sets the "next_time" field.
func (_c *NotifyTaskCreate) SetNextTime(v int64) *NotifyTaskCreate {
	_c.mutation.SetNextTime(v)
	return _c
}

// SetNillableNextTime sets the "next_time" field if the given value is not nil.
func (_c *NotifyTaskCreate) SetNillableNextTime(v *int64) *NotifyTaskCreate {
	if v != nil {
		_c.SetNextTime(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *NotifyTaskCreate) SetID(v uuid.UUID) *NotifyTaskCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *NotifyTaskCreate) SetNillableID(v *uuid.UUID) *NotifyTaskCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the NotifyTaskMutation object of the builder.
func (_c *NotifyTaskCreate) Mutation() *NotifyTaskMutation {
	return _c.mutation
}

// Save creates the NotifyTask in the database.
func (_c *NotifyTaskCreate) Save(ctx context.Context) (*NotifyTask, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NotifyTaskCreate) SaveX(ctx context.Context) *NotifyTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotifyTaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotifyTaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NotifyTaskCreate) defaults() {
	if _, ok := _c.mutation.NotifyStatus(); !ok {
		v := notifytask.DefaultNotifyStatus
		_c.mutation.SetNotifyStatus(v)
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		v := notifytask.DefaultRetryCount
		_c.mutation.SetRetryCount(v)
	}
	if _, ok := _c.mutation.MaxRetry(); !ok {
		v := notifytask.DefaultMaxRetry
		_c.mutation.SetMaxRetry(v)
	}
	if _, ok := _c.mutation.NextTime(); !ok {
		v := notifytask.DefaultNextTime
		_c.mutation.SetNextTime(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := notifytask.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NotifyTaskCreate) check() error {
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "NotifyTask.task_id"`)}
	}
	if v, ok := _c.mutation.TaskID(); ok {
		if err := notifytask.TaskIDValidator(v); err != nil {
			return &ValidationError{Name: "task_id", err: fmt.Errorf(`ent: validator failed for field "NotifyTask.task_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NotifyType(); !ok {
		return &ValidationError{Name: "notify_type", err: errors.New(`ent: missing required field "NotifyTask.notify_type"`)}
	}
	if v, ok := _c.mutation.NotifyType(); ok {
		if err := notifytask.NotifyTypeValidator(v); err != nil {
			return &ValidationError{Name: "notify_type", err: fmt.Errorf(`ent: validator failed for field "NotifyTask.notify_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NotifyStatus(); !ok {
		return &ValidationError{Name: "notify_status", err: errors.New(`ent: missing required field "NotifyTask.notify_status"`)}
	}
	if v, ok := _c.mutation.NotifyURL(); ok {
		if err := notifytask.NotifyURLValidator(v); err != nil {
			return &ValidationError{Name: "notify_url", err: fmt.Errorf(`ent: validator failed for field "NotifyTask.notify_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UUID(); !ok {
		return &ValidationError{Name: "uuid", err: errors.New(`ent: missing required field "NotifyTask.uuid"`)}
	}
	if v, ok := _c.mutation.UUID(); ok {
		if err := notifytask.UUIDValidator(v); err != nil {
			return &ValidationError{Name: "uuid", err: fmt.Errorf(`ent: validator failed for field "NotifyTask.uuid": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		return &ValidationError{Name: "retry_count", err: errors.New(`ent: missing required field "NotifyTask.retry_count"`)}
	}
	if _, ok := _c.mutation.MaxRetry(); !ok {
		return &ValidationError{Name: "max_retry", err: errors.New(`ent: missing required field "NotifyTask.max_retry"`)}
	}
	if _, ok := _c.mutation.NextTime(); !ok {
		return &ValidationError{Name: "next_time", err: errors.New(`ent: missing required field "NotifyTask.next_time"`)}
	}
	return nil
}

func (_c *NotifyTaskCreate) sqlSave(ctx context.Context) (*NotifyTask, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NotifyTaskCreate) createSpec() (*NotifyTask, *sqlgraph.CreateSpec) {
	var (
		_node = &NotifyTask{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(notifytask.Table, sqlgraph.NewFieldSpec(notifytask.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(notifytask.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(notifytask.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.TaskID(); ok {
		_spec.SetField(notifytask.FieldTaskID, field.TypeString, value)
		_node.TaskID = value
	}
	if value, ok := _c.mutation.NotifyType(); ok {
		_spec.SetField(notifytask.FieldNotifyType, field.TypeString, value)
		_node.NotifyType = value
	}
	if value, ok := _c.mutation.NotifyStatus(); ok {
		_spec.SetField(notifytask.FieldNotifyStatus, field.TypeInt32, value)
		_node.NotifyStatus = value
	}
	if value, ok := _c.mutation.NotifyURL(); ok {
		_spec.SetField(notifytask.FieldNotifyURL, field.TypeString, value)
		_node.NotifyURL = &value
	}
	if value, ok := _c.mutation.NotifyData(); ok {
		_spec.SetField(notifytask.FieldNotifyData, field.TypeString, value)
		_node.NotifyData = &value
	}
	if value, ok := _c.mutation.UUID(); ok {
		_spec.SetField(notifytask.FieldUUID, field.TypeString, value)
		_node.UUID = value
	}
	if value, ok := _c.mutation.RetryCount(); ok {
		_spec.SetField(notifytask.FieldRetryCount, field.TypeInt32, value)
		_node.RetryCount = value
	}
	if value, ok := _c.mutation.MaxRetry(); ok {
		_spec.SetField(notifytask.FieldMaxRetry, field.TypeInt32, value)
		_node.MaxRetry = value
	}
	if value, ok := _c.mutation.NextTime(); ok {
		_spec.SetField(notifytask.FieldNextTime, field.TypeInt64, value)
		_node.NextTime = value
	}
	return _node, _spec
}

// NotifyTaskCreateBulk is the builder for creating many NotifyTask entities in bulk.
type NotifyTaskCreateBulk struct {
	config
	err      error
	builders []*NotifyTaskCreate
}

// Save creates the NotifyTask entities in the database.
func (_c *NotifyTaskCreateBulk) Save(ctx context.Context) ([]*NotifyTask, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NotifyTask, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotifyTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NotifyTaskCreateBulk) SaveX(ctx context.Context) []*NotifyTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotifyTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotifyTaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
