// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: api/seckill/v1/seckill.proto

package seckillv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuerySeckillActivityReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    string                 `protobuf:"bytes,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySeckillActivityReq) Reset() {
	*x = QuerySeckillActivityReq{}
	mi := &file_api_seckill_v1_seckill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySeckillActivityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySeckillActivityReq) ProtoMessage() {}

func (x *QuerySeckillActivityReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_seckill_v1_seckill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySeckillActivityReq.ProtoReflect.Descriptor instead.
func (*QuerySeckillActivityReq) Descriptor() ([]byte, []int) {
	return file_api_seckill_v1_seckill_proto_rawDescGZIP(), []int{0}
}

func (x *QuerySeckillActivityReq) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

type QuerySeckillActivityResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    string                 `protobuf:"bytes,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	ActivityName  string                 `protobuf:"bytes,2,opt,name=activity_name,json=activityName,proto3" json:"activity_name,omitempty"`
	SkuId         string                 `protobuf:"bytes,3,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	LimitCount    int32                  `protobuf:"varint,5,opt,name=limit_count,json=limitCount,proto3" json:"limit_count,omitempty"`
	ActivityState int32                  `protobuf:"varint,6,opt,name=activity_state,json=activityState,proto3" json:"activity_state,omitempty"`
	StartTime     string                 `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySeckillActivityResp) Reset() {
	*x = QuerySeckillActivityResp{}
	mi := &file_api_seckill_v1_seckill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySeckillActivityResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySeckillActivityResp) ProtoMessage() {}

func (x *QuerySeckillActivityResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_seckill_v1_seckill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySeckillActivityResp.ProtoReflect.Descriptor instead.
func (*QuerySeckillActivityResp) Descriptor() ([]byte, []int) {
	return file_api_seckill_v1_seckill_proto_rawDescGZIP(), []int{1}
}

func (x *QuerySeckillActivityResp) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *QuerySeckillActivityResp) GetActivityName() string {
	if x != nil {
		return x.ActivityName
	}
	return ""
}

func (x *QuerySeckillActivityResp) GetSkuId() string {
	if x != nil {
		return x.SkuId
	}
	return ""
}

func (x *QuerySeckillActivityResp) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *QuerySeckillActivityResp) GetLimitCount() int32 {
	if x != nil {
		return x.LimitCount
	}
	return 0
}

func (x *QuerySeckillActivityResp) GetActivityState() int32 {
	if x != nil {
		return x.ActivityState
	}
	return 0
}

func (x *QuerySeckillActivityResp) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *QuerySeckillActivityResp) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type CreateSeckillOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    string                 `protobuf:"bytes,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSeckillOrderReq) Reset() {
	*x = CreateSeckillOrderReq{}
	mi := &file_api_seckill_v1_seckill_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSeckillOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSeckillOrderReq) ProtoMessage() {}

func (x *CreateSeckillOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_seckill_v1_seckill_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSeckillOrderReq.ProtoReflect.Descriptor instead.
func (*CreateSeckillOrderReq) Descriptor() ([]byte, []int) {
	return file_api_seckill_v1_seckill_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSeckillOrderReq) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *CreateSeckillOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateSeckillOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ActivityId    string                 `protobuf:"bytes,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	OrderState    int32                  `protobuf:"varint,3,opt,name=order_state,json=orderState,proto3" json:"order_state,omitempty"`
	OrderTime     string                 `protobuf:"bytes,4,opt,name=order_time,json=orderTime,proto3" json:"order_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSeckillOrderResp) Reset() {
	*x = CreateSeckillOrderResp{}
	mi := &file_api_seckill_v1_seckill_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSeckillOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSeckillOrderResp) ProtoMessage() {}

func (x *CreateSeckillOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_seckill_v1_seckill_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSeckillOrderResp.ProtoReflect.Descriptor instead.
func (*CreateSeckillOrderResp) Descriptor() ([]byte, []int) {
	return file_api_seckill_v1_seckill_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSeckillOrderResp) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateSeckillOrderResp) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *CreateSeckillOrderResp) GetOrderState() int32 {
	if x != nil {
		return x.OrderState
	}
	return 0
}

func (x *CreateSeckillOrderResp) GetOrderTime() string {
	if x != nil {
		return x.OrderTime
	}
	return ""
}

type QuerySeckillOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySeckillOrderReq) Reset() {
	*x = QuerySeckillOrderReq{}
	mi := &file_api_seckill_v1_seckill_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySeckillOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySeckillOrderReq) ProtoMessage() {}

func (x *QuerySeckillOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_seckill_v1_seckill_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySeckillOrderReq.ProtoReflect.Descriptor instead.
func (*QuerySeckillOrderReq) Descriptor() ([]byte, []int) {
	return file_api_seckill_v1_seckill_proto_rawDescGZIP(), []int{4}
}

func (x *QuerySeckillOrderReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *QuerySeckillOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type QuerySeckillOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ActivityId    string                 `protobuf:"bytes,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SkuId         string                 `protobuf:"bytes,4,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	OrderState    int32                  `protobuf:"varint,5,opt,name=order_state,json=orderState,proto3" json:"order_state,omitempty"`
	OrderTime     string                 `protobuf:"bytes,6,opt,name=order_time,json=orderTime,proto3" json:"order_time,omitempty"`
	PayTime       string                 `protobuf:"bytes,7,opt,name=pay_time,json=payTime,proto3" json:"pay_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySeckillOrderResp) Reset() {
	*x = QuerySeckillOrderResp{}
	mi := &file_api_seckill_v1_seckill_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySeckillOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySeckillOrderResp) ProtoMessage() {}

func (x *QuerySeckillOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_seckill_v1_seckill_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySeckillOrderResp.ProtoReflect.Descriptor instead.
func (*QuerySeckillOrderResp) Descriptor() ([]byte, []int) {
	return file_api_seckill_v1_seckill_proto_rawDescGZIP(), []int{5}
}

func (x *QuerySeckillOrderResp) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *QuerySeckillOrderResp) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *QuerySeckillOrderResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *QuerySeckillOrderResp) GetSkuId() string {
	if x != nil {
		return x.SkuId
	}
	return ""
}

func (x *QuerySeckillOrderResp) GetOrderState() int32 {
	if x != nil {
		return x.OrderState
	}
	return 0
}

func (x *QuerySeckillOrderResp) GetOrderTime() string {
	if x != nil {
		return x.OrderTime
	}
	return ""
}

func (x *QuerySeckillOrderResp) GetPayTime() string {
	if x != nil {
		return x.PayTime
	}
	return ""
}

var File_api_seckill_v1_seckill_proto protoreflect.FileDescriptor

const file_api_seckill_v1_seckill_proto_rawDesc = "" +
	"\n" +
	"\x1capi/seckill/v1/seckill.proto\x12\n" +
	"seckill.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\"?\n" +
	"\x17QuerySeckillActivityReq\x12$\n" +
	"\vactivity_id\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"activityId\"\x9a\x02\n" +
	"\x18QuerySeckillActivityResp\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\tR\n" +
	"activityId\x12#\n" +
	"\ractivity_name\x18\x02 \x01(\tR\factivityName\x12\x15\n" +
	"\x06sku_id\x18\x03 \x01(\tR\x05skuId\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\x12\x1f\n" +
	"\vlimit_count\x18\x05 \x01(\x05R\n" +
	"limitCount\x12%\n" +
	"\x0eactivity_state\x18\x06 \x01(\x05R\ractivityState\x12\x1d\n" +
	"\n" +
	"start_time\x18\a \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\b \x01(\tR\aendTime\"[\n" +
	"\x15CreateSeckillOrderReq\x12$\n" +
	"\vactivity_id\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"activityId\x12\x1c\n" +
	"\auser_id\x18\x02 \x01(\x03B\x03\xe0A\x02R\x06userId\"\x94\x01\n" +
	"\x16CreateSeckillOrderResp\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\tR\n" +
	"activityId\x12\x1f\n" +
	"\vorder_state\x18\x03 \x01(\x05R\n" +
	"orderState\x12\x1d\n" +
	"\n" +
	"order_time\x18\x04 \x01(\tR\torderTime\"O\n" +
	"\x14QuerySeckillOrderReq\x12\x1e\n" +
	"\border_id\x18\x01 \x01(\tB\x03\xe0A\x02R\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\xde\x01\n" +
	"\x15QuerySeckillOrderResp\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\tR\n" +
	"activityId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x15\n" +
	"\x06sku_id\x18\x04 \x01(\tR\x05skuId\x12\x1f\n" +
	"\vorder_state\x18\x05 \x01(\x05R\n" +
	"orderState\x12\x1d\n" +
	"\n" +
	"order_time\x18\x06 \x01(\tR\torderTime\x12\x19\n" +
	"\bpay_time\x18\a \x01(\tR\apayTime2\xa2\x03\n" +
	"\x0eSeckillService\x12\x89\x01\n" +
	"\x14QuerySeckillActivity\x12#.seckill.v1.QuerySeckillActivityReq\x1a$.seckill.v1.QuerySeckillActivityResp\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/v1/seckill/activity/query\x12\x84\x01\n" +
	"\x12CreateSeckillOrder\x12!.seckill.v1.CreateSeckillOrderReq\x1a\".seckill.v1.CreateSeckillOrderResp\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/v1/seckill/order/create\x12}\n" +
	"\x11QuerySeckillOrder\x12 .seckill.v1.QuerySeckillOrderReq\x1a!.seckill.v1.QuerySeckillOrderResp\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/seckill/order/queryB8Z6github.com/marketing-platform/api/seckill/v1;seckillv1b\x06proto3"

var (
	file_api_seckill_v1_seckill_proto_rawDescOnce sync.Once
	file_api_seckill_v1_seckill_proto_rawDescData []byte
)

func file_api_seckill_v1_seckill_proto_rawDescGZIP() []byte {
	file_api_seckill_v1_seckill_proto_rawDescOnce.Do(func() {
		file_api_seckill_v1_seckill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_seckill_v1_seckill_proto_rawDesc), len(file_api_seckill_v1_seckill_proto_rawDesc)))
	})
	return file_api_seckill_v1_seckill_proto_rawDescData
}

var file_api_seckill_v1_seckill_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_seckill_v1_seckill_proto_goTypes = []any{
	(*QuerySeckillActivityReq)(nil),  // 0: seckill.v1.QuerySeckillActivityReq
	(*QuerySeckillActivityResp)(nil), // 1: seckill.v1.QuerySeckillActivityResp
	(*CreateSeckillOrderReq)(nil),    // 2: seckill.v1.CreateSeckillOrderReq
	(*CreateSeckillOrderResp)(nil),   // 3: seckill.v1.CreateSeckillOrderResp
	(*QuerySeckillOrderReq)(nil),     // 4: seckill.v1.QuerySeckillOrderReq
	(*QuerySeckillOrderResp)(nil),    // 5: seckill.v1.QuerySeckillOrderResp
}
var file_api_seckill_v1_seckill_proto_depIdxs = []int32{
	0, // 0: seckill.v1.SeckillService.QuerySeckillActivity:input_type -> seckill.v1.QuerySeckillActivityReq
	2, // 1: seckill.v1.SeckillService.CreateSeckillOrder:input_type -> seckill.v1.CreateSeckillOrderReq
	4, // 2: seckill.v1.SeckillService.QuerySeckillOrder:input_type -> seckill.v1.QuerySeckillOrderReq
	1, // 3: seckill.v1.SeckillService.QuerySeckillActivity:output_type -> seckill.v1.QuerySeckillActivityResp
	3, // 4: seckill.v1.SeckillService.CreateSeckillOrder:output_type -> seckill.v1.CreateSeckillOrderResp
	5, // 5: seckill.v1.SeckillService.QuerySeckillOrder:output_type -> seckill.v1.QuerySeckillOrderResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_seckill_v1_seckill_proto_init() }
func file_api_seckill_v1_seckill_proto_init() {
	if File_api_seckill_v1_seckill_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_seckill_v1_seckill_proto_rawDesc), len(file_api_seckill_v1_seckill_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_seckill_v1_seckill_proto_goTypes,
		DependencyIndexes: file_api_seckill_v1_seckill_proto_depIdxs,
		MessageInfos:      file_api_seckill_v1_seckill_proto_msgTypes,
	}.Build()
	File_api_seckill_v1_seckill_proto = out.File
	file_api_seckill_v1_seckill_proto_goTypes = nil
	file_api_seckill_v1_seckill_proto_depIdxs = nil
}
