// Code generated by ent, DO NOT EDIT.

package lotterystrategy

import (
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the lotterystrategy type in the database.
	Label = "lottery_strategy"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldStrategyID holds the string denoting the strategy_id field in the database.
	FieldStrategyID = "strategy_id"
	// FieldRuleModels holds the string denoting the rule_models field in the database.
	FieldRuleModels = "rule_models"
	// Table holds the table name of the lotterystrategy in the database.
	Table = "lottery_strategies"
)

// Columns holds all SQL columns for lotterystrategy fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldStrategyID,
	FieldRuleModels,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// StrategyIDValidator is a validator for the "strategy_id" field. It is called by the builders before save.
	StrategyIDValidator func(string) error
	// RuleModelsValidator is a validator for the "rule_models" field. It is called by the builders before save.
	RuleModelsValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the LotteryStrategy queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByStrategyID orders the results by the strategy_id field.
func ByStrategyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStrategyID, opts...).ToFunc()
}

// ByRuleModels orders the results by the rule_models field.
func ByRuleModels(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuleModels, opts...).ToFunc()
}
