// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// LotteryActivitiesColumns holds the columns for the "lottery_activities" table.
	LotteryActivitiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "activity_id", Type: field.TypeString, Unique: true, Size: 32},
		{Name: "activity_name", Type: field.TypeString, Size: 64},
		{Name: "strategy_id", Type: field.TypeString, Size: 32},
		{Name: "activity_state", Type: field.TypeInt32, Default: 0},
	}
	// LotteryActivitiesTable holds the schema information for the "lottery_activities" table.
	LotteryActivitiesTable = &schema.Table{
		Name:       "lottery_activities",
		Columns:    LotteryActivitiesColumns,
		PrimaryKey: []*schema.Column{LotteryActivitiesColumns[0]},
	}
	// LotteryOrdersColumns holds the columns for the "lottery_orders" table.
	LotteryOrdersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "order_id", Type: field.TypeString, Unique: true, Size: 32},
		{Name: "activity_id", Type: field.TypeString, Size: 32},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "award_id", Type: field.TypeString, Nullable: true, Size: 32},
		{Name: "award_state", Type: field.TypeInt32, Default: 0},
		{Name: "award_time", Type: field.TypeTime, Nullable: true},
	}
	// LotteryOrdersTable holds the schema information for the "lottery_orders" table.
	LotteryOrdersTable = &schema.Table{
		Name:       "lottery_orders",
		Columns:    LotteryOrdersColumns,
		PrimaryKey: []*schema.Column{LotteryOrdersColumns[0]},
	}
	// LotteryStrategiesColumns holds the columns for the "lottery_strategies" table.
	LotteryStrategiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "strategy_id", Type: field.TypeString, Unique: true, Size: 32},
		{Name: "rule_models", Type: field.TypeString, Nullable: true, Size: 256},
	}
	// LotteryStrategiesTable holds the schema information for the "lottery_strategies" table.
	LotteryStrategiesTable = &schema.Table{
		Name:       "lottery_strategies",
		Columns:    LotteryStrategiesColumns,
		PrimaryKey: []*schema.Column{LotteryStrategiesColumns[0]},
	}
	// StrategyAwardsColumns holds the columns for the "strategy_awards" table.
	StrategyAwardsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "strategy_id", Type: field.TypeString, Size: 32},
		{Name: "award_id", Type: field.TypeString, Size: 32},
		{Name: "award_name", Type: field.TypeString, Size: 64},
		{Name: "award_rate", Type: field.TypeFloat64},
		{Name: "award_count", Type: field.TypeInt32, Default: 0},
		{Name: "rule_models", Type: field.TypeString, Nullable: true, Size: 256},
	}
	// StrategyAwardsTable holds the schema information for the "strategy_awards" table.
	StrategyAwardsTable = &schema.Table{
		Name:       "strategy_awards",
		Columns:    StrategyAwardsColumns,
		PrimaryKey: []*schema.Column{StrategyAwardsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		LotteryActivitiesTable,
		LotteryOrdersTable,
		LotteryStrategiesTable,
		StrategyAwardsTable,
	}
)

func init() {
}
