// Code generated by ent, DO NOT EDIT.

package seckillactivity

import (
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the seckillactivity type in the database.
	Label = "seckill_activity"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldActivityID holds the string denoting the activity_id field in the database.
	FieldActivityID = "activity_id"
	// FieldActivityName holds the string denoting the activity_name field in the database.
	FieldActivityName = "activity_name"
	// FieldSkuID holds the string denoting the sku_id field in the database.
	FieldSkuID = "sku_id"
	// FieldTotalCount holds the string denoting the total_count field in the database.
	FieldTotalCount = "total_count"
	// FieldLimitCount holds the string denoting the limit_count field in the database.
	FieldLimitCount = "limit_count"
	// FieldActivityState holds the string denoting the activity_state field in the database.
	FieldActivityState = "activity_state"
	// FieldStartTime holds the string denoting the start_time field in the database.
	FieldStartTime = "start_time"
	// FieldEndTime holds the string denoting the end_time field in the database.
	FieldEndTime = "end_time"
	// Table holds the table name of the seckillactivity in the database.
	Table = "seckill_activities"
)

// Columns holds all SQL columns for seckillactivity fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldActivityID,
	FieldActivityName,
	FieldSkuID,
	FieldTotalCount,
	FieldLimitCount,
	FieldActivityState,
	FieldStartTime,
	FieldEndTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ActivityIDValidator is a validator for the "activity_id" field. It is called by the builders before save.
	ActivityIDValidator func(string) error
	// ActivityNameValidator is a validator for the "activity_name" field. It is called by the builders before save.
	ActivityNameValidator func(string) error
	// SkuIDValidator is a validator for the "sku_id" field. It is called by the builders before save.
	SkuIDValidator func(string) error
	// DefaultTotalCount holds the default value on creation for the "total_count" field.
	DefaultTotalCount int32
	// DefaultLimitCount holds the default value on creation for the "limit_count" field.
	DefaultLimitCount int32
	// DefaultActivityState holds the default value on creation for the "activity_state" field.
	DefaultActivityState int32
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the SeckillActivity queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByActivityID orders the results by the activity_id field.
func ByActivityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActivityID, opts...).ToFunc()
}

// ByActivityName orders the results by the activity_name field.
func ByActivityName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActivityName, opts...).ToFunc()
}

// BySkuID orders the results by the sku_id field.
func BySkuID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkuID, opts...).ToFunc()
}

// ByTotalCount orders the results by the total_count field.
func ByTotalCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalCount, opts...).ToFunc()
}

// ByLimitCount orders the results by the limit_count field.
func ByLimitCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLimitCount, opts...).ToFunc()
}

// ByActivityState orders the results by the activity_state field.
func ByActivityState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActivityState, opts...).ToFunc()
}

// ByStartTime orders the results by the start_time field.
func ByStartTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartTime, opts...).ToFunc()
}

// ByEndTime orders the results by the end_time field.
func ByEndTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndTime, opts...).ToFunc()
}
