// Code generated by ent, DO NOT EDIT.

package seckillactivity

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/marketing-platform/internal/seckill/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldEQ(FieldUpdatedAt, v))
}

// ActivityID applies equality check predicate on the "activity_id" field. It's identical to ActivityIDEQ.
func ActivityID(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldEQ(FieldActivityID, v))
}

// ActivityName applies equality check predicate on the "activity_name" field. It's identical to ActivityNameEQ.
func ActivityName(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldEQ(FieldActivityName, v))
}

// SkuID applies equality check predicate on the "sku_id" field. It's identical to SkuIDEQ.
func SkuID(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldEQ(FieldSkuID, v))
}

// TotalCount applies equality check predicate on the "total_count" field. It's identical to TotalCountEQ.
func TotalCount(v int32) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldEQ(FieldTotalCount, v))
}

// LimitCount applies equality check predicate on the "limit_count" field. It's identical to LimitCountEQ.
func LimitCount(v int32) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldEQ(FieldLimitCount, v))
}

// ActivityState applies equality check predicate on the "activity_state" field. It's identical to ActivityStateEQ.
func ActivityState(v int32) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldEQ(FieldActivityState, v))
}

// StartTime applies equality check predicate on the "start_time" field. It's identical to StartTimeEQ.
func StartTime(v time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldEQ(FieldStartTime, v))
}

// EndTime applies equality check predicate on the "end_time" field. It's identical to EndTimeEQ.
func EndTime(v time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldEQ(FieldEndTime, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldNotNull(FieldUpdatedAt))
}

// ActivityIDEQ applies the EQ predicate on the "activity_id" field.
func ActivityIDEQ(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldEQ(FieldActivityID, v))
}

// ActivityIDNEQ applies the NEQ predicate on the "activity_id" field.
func ActivityIDNEQ(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldNEQ(FieldActivityID, v))
}

// ActivityIDIn applies the In predicate on the "activity_id" field.
func ActivityIDIn(vs ...string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldIn(FieldActivityID, vs...))
}

// ActivityIDNotIn applies the NotIn predicate on the "activity_id" field.
func ActivityIDNotIn(vs ...string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldNotIn(FieldActivityID, vs...))
}

// ActivityIDGT applies the GT predicate on the "activity_id" field.
func ActivityIDGT(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldGT(FieldActivityID, v))
}

// ActivityIDGTE applies the GTE predicate on the "activity_id" field.
func ActivityIDGTE(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldGTE(FieldActivityID, v))
}

// ActivityIDLT applies the LT predicate on the "activity_id" field.
func ActivityIDLT(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldLT(FieldActivityID, v))
}

// ActivityIDLTE applies the LTE predicate on the "activity_id" field.
func ActivityIDLTE(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldLTE(FieldActivityID, v))
}

// ActivityIDContains applies the Contains predicate on the "activity_id" field.
func ActivityIDContains(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldContains(FieldActivityID, v))
}

// ActivityIDHasPrefix applies the HasPrefix predicate on the "activity_id" field.
func ActivityIDHasPrefix(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldHasPrefix(FieldActivityID, v))
}

// ActivityIDHasSuffix applies the HasSuffix predicate on the "activity_id" field.
func ActivityIDHasSuffix(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldHasSuffix(FieldActivityID, v))
}

// ActivityIDEqualFold applies the EqualFold predicate on the "activity_id" field.
func ActivityIDEqualFold(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldEqualFold(FieldActivityID, v))
}

// ActivityIDContainsFold applies the ContainsFold predicate on the "activity_id" field.
func ActivityIDContainsFold(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldContainsFold(FieldActivityID, v))
}

// ActivityNameEQ applies the EQ predicate on the "activity_name" field.
func ActivityNameEQ(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldEQ(FieldActivityName, v))
}

// ActivityNameNEQ applies the NEQ predicate on the "activity_name" field.
func ActivityNameNEQ(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldNEQ(FieldActivityName, v))
}

// ActivityNameIn applies the In predicate on the "activity_name" field.
func ActivityNameIn(vs ...string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldIn(FieldActivityName, vs...))
}

// ActivityNameNotIn applies the NotIn predicate on the "activity_name" field.
func ActivityNameNotIn(vs ...string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldNotIn(FieldActivityName, vs...))
}

// ActivityNameGT applies the GT predicate on the "activity_name" field.
func ActivityNameGT(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldGT(FieldActivityName, v))
}

// ActivityNameGTE applies the GTE predicate on the "activity_name" field.
func ActivityNameGTE(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldGTE(FieldActivityName, v))
}

// ActivityNameLT applies the LT predicate on the "activity_name" field.
func ActivityNameLT(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldLT(FieldActivityName, v))
}

// ActivityNameLTE applies the LTE predicate on the "activity_name" field.
func ActivityNameLTE(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldLTE(FieldActivityName, v))
}

// ActivityNameContains applies the Contains predicate on the "activity_name" field.
func ActivityNameContains(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldContains(FieldActivityName, v))
}

// ActivityNameHasPrefix applies the HasPrefix predicate on the "activity_name" field.
func ActivityNameHasPrefix(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldHasPrefix(FieldActivityName, v))
}

// ActivityNameHasSuffix applies the HasSuffix predicate on the "activity_name" field.
func ActivityNameHasSuffix(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldHasSuffix(FieldActivityName, v))
}

// ActivityNameEqualFold applies the EqualFold predicate on the "activity_name" field.
func ActivityNameEqualFold(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldEqualFold(FieldActivityName, v))
}

// ActivityNameContainsFold applies the ContainsFold predicate on the "activity_name" field.
func ActivityNameContainsFold(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldContainsFold(FieldActivityName, v))
}

// SkuIDEQ applies the EQ predicate on the "sku_id" field.
func SkuIDEQ(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldEQ(FieldSkuID, v))
}

// SkuIDNEQ applies the NEQ predicate on the "sku_id" field.
func SkuIDNEQ(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldNEQ(FieldSkuID, v))
}

// SkuIDIn applies the In predicate on the "sku_id" field.
func SkuIDIn(vs ...string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldIn(FieldSkuID, vs...))
}

// SkuIDNotIn applies the NotIn predicate on the "sku_id" field.
func SkuIDNotIn(vs ...string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldNotIn(FieldSkuID, vs...))
}

// SkuIDGT applies the GT predicate on the "sku_id" field.
func SkuIDGT(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldGT(FieldSkuID, v))
}

// SkuIDGTE applies the GTE predicate on the "sku_id" field.
func SkuIDGTE(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldGTE(FieldSkuID, v))
}

// SkuIDLT applies the LT predicate on the "sku_id" field.
func SkuIDLT(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldLT(FieldSkuID, v))
}

// SkuIDLTE applies the LTE predicate on the "sku_id" field.
func SkuIDLTE(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldLTE(FieldSkuID, v))
}

// SkuIDContains applies the Contains predicate on the "sku_id" field.
func SkuIDContains(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldContains(FieldSkuID, v))
}

// SkuIDHasPrefix applies the HasPrefix predicate on the "sku_id" field.
func SkuIDHasPrefix(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldHasPrefix(FieldSkuID, v))
}

// SkuIDHasSuffix applies the HasSuffix predicate on the "sku_id" field.
func SkuIDHasSuffix(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldHasSuffix(FieldSkuID, v))
}

// SkuIDEqualFold applies the EqualFold predicate on the "sku_id" field.
func SkuIDEqualFold(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldEqualFold(FieldSkuID, v))
}

// SkuIDContainsFold applies the ContainsFold predicate on the "sku_id" field.
func SkuIDContainsFold(v string) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldContainsFold(FieldSkuID, v))
}

// TotalCountEQ applies the EQ predicate on the "total_count" field.
func TotalCountEQ(v int32) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldEQ(FieldTotalCount, v))
}

// TotalCountNEQ applies the NEQ predicate on the "total_count" field.
func TotalCountNEQ(v int32) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldNEQ(FieldTotalCount, v))
}

// TotalCountIn applies the In predicate on the "total_count" field.
func TotalCountIn(vs ...int32) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldIn(FieldTotalCount, vs...))
}

// TotalCountNotIn applies the NotIn predicate on the "total_count" field.
func TotalCountNotIn(vs ...int32) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldNotIn(FieldTotalCount, vs...))
}

// TotalCountGT applies the GT predicate on the "total_count" field.
func TotalCountGT(v int32) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldGT(FieldTotalCount, v))
}

// TotalCountGTE applies the GTE predicate on the "total_count" field.
func TotalCountGTE(v int32) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldGTE(FieldTotalCount, v))
}

// TotalCountLT applies the LT predicate on the "total_count" field.
func TotalCountLT(v int32) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldLT(FieldTotalCount, v))
}

// TotalCountLTE applies the LTE predicate on the "total_count" field.
func TotalCountLTE(v int32) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldLTE(FieldTotalCount, v))
}

// LimitCountEQ applies the EQ predicate on the "limit_count" field.
func LimitCountEQ(v int32) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldEQ(FieldLimitCount, v))
}

// LimitCountNEQ applies the NEQ predicate on the "limit_count" field.
func LimitCountNEQ(v int32) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldNEQ(FieldLimitCount, v))
}

// LimitCountIn applies the In predicate on the "limit_count" field.
func LimitCountIn(vs ...int32) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldIn(FieldLimitCount, vs...))
}

// LimitCountNotIn applies the NotIn predicate on the "limit_count" field.
func LimitCountNotIn(vs ...int32) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldNotIn(FieldLimitCount, vs...))
}

// LimitCountGT applies the GT predicate on the "limit_count" field.
func LimitCountGT(v int32) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldGT(FieldLimitCount, v))
}

// LimitCountGTE applies the GTE predicate on the "limit_count" field.
func LimitCountGTE(v int32) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldGTE(FieldLimitCount, v))
}

// LimitCountLT applies the LT predicate on the "limit_count" field.
func LimitCountLT(v int32) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldLT(FieldLimitCount, v))
}

// LimitCountLTE applies the LTE predicate on the "limit_count" field.
func LimitCountLTE(v int32) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldLTE(FieldLimitCount, v))
}

// ActivityStateEQ applies the EQ predicate on the "activity_state" field.
func ActivityStateEQ(v int32) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldEQ(FieldActivityState, v))
}

// ActivityStateNEQ applies the NEQ predicate on the "activity_state" field.
func ActivityStateNEQ(v int32) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldNEQ(FieldActivityState, v))
}

// ActivityStateIn applies the In predicate on the "activity_state" field.
func ActivityStateIn(vs ...int32) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldIn(FieldActivityState, vs...))
}

// ActivityStateNotIn applies the NotIn predicate on the "activity_state" field.
func ActivityStateNotIn(vs ...int32) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldNotIn(FieldActivityState, vs...))
}

// ActivityStateGT applies the GT predicate on the "activity_state" field.
func ActivityStateGT(v int32) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldGT(FieldActivityState, v))
}

// ActivityStateGTE applies the GTE predicate on the "activity_state" field.
func ActivityStateGTE(v int32) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldGTE(FieldActivityState, v))
}

// ActivityStateLT applies the LT predicate on the "activity_state" field.
func ActivityStateLT(v int32) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldLT(FieldActivityState, v))
}

// ActivityStateLTE applies the LTE predicate on the "activity_state" field.
func ActivityStateLTE(v int32) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldLTE(FieldActivityState, v))
}

// StartTimeEQ applies the EQ predicate on the "start_time" field.
func StartTimeEQ(v time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldEQ(FieldStartTime, v))
}

// StartTimeNEQ applies the NEQ predicate on the "start_time" field.
func StartTimeNEQ(v time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldNEQ(FieldStartTime, v))
}

// StartTimeIn applies the In predicate on the "start_time" field.
func StartTimeIn(vs ...time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldIn(FieldStartTime, vs...))
}

// StartTimeNotIn applies the NotIn predicate on the "start_time" field.
func StartTimeNotIn(vs ...time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldNotIn(FieldStartTime, vs...))
}

// StartTimeGT applies the GT predicate on the "start_time" field.
func StartTimeGT(v time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldGT(FieldStartTime, v))
}

// StartTimeGTE applies the GTE predicate on the "start_time" field.
func StartTimeGTE(v time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldGTE(FieldStartTime, v))
}

// StartTimeLT applies the LT predicate on the "start_time" field.
func StartTimeLT(v time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldLT(FieldStartTime, v))
}

// StartTimeLTE applies the LTE predicate on the "start_time" field.
func StartTimeLTE(v time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldLTE(FieldStartTime, v))
}

// EndTimeEQ applies the EQ predicate on the "end_time" field.
func EndTimeEQ(v time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldEQ(FieldEndTime, v))
}

// EndTimeNEQ applies the NEQ predicate on the "end_time" field.
func EndTimeNEQ(v time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldNEQ(FieldEndTime, v))
}

// EndTimeIn applies the In predicate on the "end_time" field.
func EndTimeIn(vs ...time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldIn(FieldEndTime, vs...))
}

// EndTimeNotIn applies the NotIn predicate on the "end_time" field.
func EndTimeNotIn(vs ...time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldNotIn(FieldEndTime, vs...))
}

// EndTimeGT applies the GT predicate on the "end_time" field.
func EndTimeGT(v time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldGT(FieldEndTime, v))
}

// EndTimeGTE applies the GTE predicate on the "end_time" field.
func EndTimeGTE(v time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldGTE(FieldEndTime, v))
}

// EndTimeLT applies the LT predicate on the "end_time" field.
func EndTimeLT(v time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldLT(FieldEndTime, v))
}

// EndTimeLTE applies the LTE predicate on the "end_time" field.
func EndTimeLTE(v time.Time) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.FieldLTE(FieldEndTime, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SeckillActivity) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SeckillActivity) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SeckillActivity) predicate.SeckillActivity {
	return predicate.SeckillActivity(sql.NotPredicates(p))
}
