// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"

	"github.com/marketing-platform/internal/lottery/biz"
	"github.com/marketing-platform/internal/lottery/data"
	"github.com/marketing-platform/internal/lottery/server"
	"github.com/marketing-platform/internal/lottery/service"
)

func InitializeLotteryServer() (*server.LotteryServer, func(), error) {
	// Init MySQL
	db, err := sql.Open("mysql", "root:root@tcp(127.0.0.1:3306)/marketing_lottery?charset=utf8mb4&parseTime=True&loc=Local")
	if err != nil {
		return nil, nil, err
	}

	dataLayer := data.NewData(db, nil)

	activityRepo := data.NewActivityRepo(dataLayer)
	strategyRepo := data.NewStrategyRepo(dataLayer)
	orderRepo := data.NewOrderRepo(dataLayer)

	raffleSvc := biz.NewRaffleService(activityRepo, strategyRepo, orderRepo)
	svc := service.NewLotteryService(raffleSvc)
	lotteryServer := server.NewLotteryServer(svc)

	cleanup := func() {
		dataLayer.Close()
	}

	return lotteryServer, cleanup, nil
}
