// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"github.com/marketing-platform/internal/lottery/data/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/marketing-platform/internal/lottery/data/ent/lotteryactivity"
	"github.com/marketing-platform/internal/lottery/data/ent/lotteryorder"
	"github.com/marketing-platform/internal/lottery/data/ent/lotterystrategy"
	"github.com/marketing-platform/internal/lottery/data/ent/strategyaward"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// LotteryActivity is the client for interacting with the LotteryActivity builders.
	LotteryActivity *LotteryActivityClient
	// LotteryOrder is the client for interacting with the LotteryOrder builders.
	LotteryOrder *LotteryOrderClient
	// LotteryStrategy is the client for interacting with the LotteryStrategy builders.
	LotteryStrategy *LotteryStrategyClient
	// StrategyAward is the client for interacting with the StrategyAward builders.
	StrategyAward *StrategyAwardClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.LotteryActivity = NewLotteryActivityClient(c.config)
	c.LotteryOrder = NewLotteryOrderClient(c.config)
	c.LotteryStrategy = NewLotteryStrategyClient(c.config)
	c.StrategyAward = NewStrategyAwardClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		LotteryActivity: NewLotteryActivityClient(cfg),
		LotteryOrder:    NewLotteryOrderClient(cfg),
		LotteryStrategy: NewLotteryStrategyClient(cfg),
		StrategyAward:   NewStrategyAwardClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		LotteryActivity: NewLotteryActivityClient(cfg),
		LotteryOrder:    NewLotteryOrderClient(cfg),
		LotteryStrategy: NewLotteryStrategyClient(cfg),
		StrategyAward:   NewStrategyAwardClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		LotteryActivity.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.LotteryActivity.Use(hooks...)
	c.LotteryOrder.Use(hooks...)
	c.LotteryStrategy.Use(hooks...)
	c.StrategyAward.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.LotteryActivity.Intercept(interceptors...)
	c.LotteryOrder.Intercept(interceptors...)
	c.LotteryStrategy.Intercept(interceptors...)
	c.StrategyAward.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *LotteryActivityMutation:
		return c.LotteryActivity.mutate(ctx, m)
	case *LotteryOrderMutation:
		return c.LotteryOrder.mutate(ctx, m)
	case *LotteryStrategyMutation:
		return c.LotteryStrategy.mutate(ctx, m)
	case *StrategyAwardMutation:
		return c.StrategyAward.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// LotteryActivityClient is a client for the LotteryActivity schema.
type LotteryActivityClient struct {
	config
}

// NewLotteryActivityClient returns a client for the LotteryActivity from the given config.
func NewLotteryActivityClient(c config) *LotteryActivityClient {
	return &LotteryActivityClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `lotteryactivity.Hooks(f(g(h())))`.
func (c *LotteryActivityClient) Use(hooks ...Hook) {
	c.hooks.LotteryActivity = append(c.hooks.LotteryActivity, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `lotteryactivity.Intercept(f(g(h())))`.
func (c *LotteryActivityClient) Intercept(interceptors ...Interceptor) {
	c.inters.LotteryActivity = append(c.inters.LotteryActivity, interceptors...)
}

// Create returns a builder for creating a LotteryActivity entity.
func (c *LotteryActivityClient) Create() *LotteryActivityCreate {
	mutation := newLotteryActivityMutation(c.config, OpCreate)
	return &LotteryActivityCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of LotteryActivity entities.
func (c *LotteryActivityClient) CreateBulk(builders ...*LotteryActivityCreate) *LotteryActivityCreateBulk {
	return &LotteryActivityCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *LotteryActivityClient) MapCreateBulk(slice any, setFunc func(*LotteryActivityCreate, int)) *LotteryActivityCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &LotteryActivityCreateBulk{err: fmt.Errorf("calling to LotteryActivityClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*LotteryActivityCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &LotteryActivityCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for LotteryActivity.
func (c *LotteryActivityClient) Update() *LotteryActivityUpdate {
	mutation := newLotteryActivityMutation(c.config, OpUpdate)
	return &LotteryActivityUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *LotteryActivityClient) UpdateOne(_m *LotteryActivity) *LotteryActivityUpdateOne {
	mutation := newLotteryActivityMutation(c.config, OpUpdateOne, withLotteryActivity(_m))
	return &LotteryActivityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *LotteryActivityClient) UpdateOneID(id uuid.UUID) *LotteryActivityUpdateOne {
	mutation := newLotteryActivityMutation(c.config, OpUpdateOne, withLotteryActivityID(id))
	return &LotteryActivityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for LotteryActivity.
func (c *LotteryActivityClient) Delete() *LotteryActivityDelete {
	mutation := newLotteryActivityMutation(c.config, OpDelete)
	return &LotteryActivityDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *LotteryActivityClient) DeleteOne(_m *LotteryActivity) *LotteryActivityDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *LotteryActivityClient) DeleteOneID(id uuid.UUID) *LotteryActivityDeleteOne {
	builder := c.Delete().Where(lotteryactivity.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &LotteryActivityDeleteOne{builder}
}

// Query returns a query builder for LotteryActivity.
func (c *LotteryActivityClient) Query() *LotteryActivityQuery {
	return &LotteryActivityQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeLotteryActivity},
		inters: c.Interceptors(),
	}
}

// Get returns a LotteryActivity entity by its id.
func (c *LotteryActivityClient) Get(ctx context.Context, id uuid.UUID) (*LotteryActivity, error) {
	return c.Query().Where(lotteryactivity.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *LotteryActivityClient) GetX(ctx context.Context, id uuid.UUID) *LotteryActivity {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *LotteryActivityClient) Hooks() []Hook {
	return c.hooks.LotteryActivity
}

// Interceptors returns the client interceptors.
func (c *LotteryActivityClient) Interceptors() []Interceptor {
	return c.inters.LotteryActivity
}

func (c *LotteryActivityClient) mutate(ctx context.Context, m *LotteryActivityMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&LotteryActivityCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&LotteryActivityUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&LotteryActivityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&LotteryActivityDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown LotteryActivity mutation op: %q", m.Op())
	}
}

// LotteryOrderClient is a client for the LotteryOrder schema.
type LotteryOrderClient struct {
	config
}

// NewLotteryOrderClient returns a client for the LotteryOrder from the given config.
func NewLotteryOrderClient(c config) *LotteryOrderClient {
	return &LotteryOrderClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `lotteryorder.Hooks(f(g(h())))`.
func (c *LotteryOrderClient) Use(hooks ...Hook) {
	c.hooks.LotteryOrder = append(c.hooks.LotteryOrder, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `lotteryorder.Intercept(f(g(h())))`.
func (c *LotteryOrderClient) Intercept(interceptors ...Interceptor) {
	c.inters.LotteryOrder = append(c.inters.LotteryOrder, interceptors...)
}

// Create returns a builder for creating a LotteryOrder entity.
func (c *LotteryOrderClient) Create() *LotteryOrderCreate {
	mutation := newLotteryOrderMutation(c.config, OpCreate)
	return &LotteryOrderCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of LotteryOrder entities.
func (c *LotteryOrderClient) CreateBulk(builders ...*LotteryOrderCreate) *LotteryOrderCreateBulk {
	return &LotteryOrderCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *LotteryOrderClient) MapCreateBulk(slice any, setFunc func(*LotteryOrderCreate, int)) *LotteryOrderCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &LotteryOrderCreateBulk{err: fmt.Errorf("calling to LotteryOrderClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*LotteryOrderCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &LotteryOrderCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for LotteryOrder.
func (c *LotteryOrderClient) Update() *LotteryOrderUpdate {
	mutation := newLotteryOrderMutation(c.config, OpUpdate)
	return &LotteryOrderUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *LotteryOrderClient) UpdateOne(_m *LotteryOrder) *LotteryOrderUpdateOne {
	mutation := newLotteryOrderMutation(c.config, OpUpdateOne, withLotteryOrder(_m))
	return &LotteryOrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *LotteryOrderClient) UpdateOneID(id uuid.UUID) *LotteryOrderUpdateOne {
	mutation := newLotteryOrderMutation(c.config, OpUpdateOne, withLotteryOrderID(id))
	return &LotteryOrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for LotteryOrder.
func (c *LotteryOrderClient) Delete() *LotteryOrderDelete {
	mutation := newLotteryOrderMutation(c.config, OpDelete)
	return &LotteryOrderDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *LotteryOrderClient) DeleteOne(_m *LotteryOrder) *LotteryOrderDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *LotteryOrderClient) DeleteOneID(id uuid.UUID) *LotteryOrderDeleteOne {
	builder := c.Delete().Where(lotteryorder.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &LotteryOrderDeleteOne{builder}
}

// Query returns a query builder for LotteryOrder.
func (c *LotteryOrderClient) Query() *LotteryOrderQuery {
	return &LotteryOrderQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeLotteryOrder},
		inters: c.Interceptors(),
	}
}

// Get returns a LotteryOrder entity by its id.
func (c *LotteryOrderClient) Get(ctx context.Context, id uuid.UUID) (*LotteryOrder, error) {
	return c.Query().Where(lotteryorder.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *LotteryOrderClient) GetX(ctx context.Context, id uuid.UUID) *LotteryOrder {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *LotteryOrderClient) Hooks() []Hook {
	return c.hooks.LotteryOrder
}

// Interceptors returns the client interceptors.
func (c *LotteryOrderClient) Interceptors() []Interceptor {
	return c.inters.LotteryOrder
}

func (c *LotteryOrderClient) mutate(ctx context.Context, m *LotteryOrderMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&LotteryOrderCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&LotteryOrderUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&LotteryOrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&LotteryOrderDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown LotteryOrder mutation op: %q", m.Op())
	}
}

// LotteryStrategyClient is a client for the LotteryStrategy schema.
type LotteryStrategyClient struct {
	config
}

// NewLotteryStrategyClient returns a client for the LotteryStrategy from the given config.
func NewLotteryStrategyClient(c config) *LotteryStrategyClient {
	return &LotteryStrategyClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `lotterystrategy.Hooks(f(g(h())))`.
func (c *LotteryStrategyClient) Use(hooks ...Hook) {
	c.hooks.LotteryStrategy = append(c.hooks.LotteryStrategy, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `lotterystrategy.Intercept(f(g(h())))`.
func (c *LotteryStrategyClient) Intercept(interceptors ...Interceptor) {
	c.inters.LotteryStrategy = append(c.inters.LotteryStrategy, interceptors...)
}

// Create returns a builder for creating a LotteryStrategy entity.
func (c *LotteryStrategyClient) Create() *LotteryStrategyCreate {
	mutation := newLotteryStrategyMutation(c.config, OpCreate)
	return &LotteryStrategyCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of LotteryStrategy entities.
func (c *LotteryStrategyClient) CreateBulk(builders ...*LotteryStrategyCreate) *LotteryStrategyCreateBulk {
	return &LotteryStrategyCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *LotteryStrategyClient) MapCreateBulk(slice any, setFunc func(*LotteryStrategyCreate, int)) *LotteryStrategyCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &LotteryStrategyCreateBulk{err: fmt.Errorf("calling to LotteryStrategyClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*LotteryStrategyCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &LotteryStrategyCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for LotteryStrategy.
func (c *LotteryStrategyClient) Update() *LotteryStrategyUpdate {
	mutation := newLotteryStrategyMutation(c.config, OpUpdate)
	return &LotteryStrategyUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *LotteryStrategyClient) UpdateOne(_m *LotteryStrategy) *LotteryStrategyUpdateOne {
	mutation := newLotteryStrategyMutation(c.config, OpUpdateOne, withLotteryStrategy(_m))
	return &LotteryStrategyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *LotteryStrategyClient) UpdateOneID(id uuid.UUID) *LotteryStrategyUpdateOne {
	mutation := newLotteryStrategyMutation(c.config, OpUpdateOne, withLotteryStrategyID(id))
	return &LotteryStrategyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for LotteryStrategy.
func (c *LotteryStrategyClient) Delete() *LotteryStrategyDelete {
	mutation := newLotteryStrategyMutation(c.config, OpDelete)
	return &LotteryStrategyDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *LotteryStrategyClient) DeleteOne(_m *LotteryStrategy) *LotteryStrategyDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *LotteryStrategyClient) DeleteOneID(id uuid.UUID) *LotteryStrategyDeleteOne {
	builder := c.Delete().Where(lotterystrategy.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &LotteryStrategyDeleteOne{builder}
}

// Query returns a query builder for LotteryStrategy.
func (c *LotteryStrategyClient) Query() *LotteryStrategyQuery {
	return &LotteryStrategyQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeLotteryStrategy},
		inters: c.Interceptors(),
	}
}

// Get returns a LotteryStrategy entity by its id.
func (c *LotteryStrategyClient) Get(ctx context.Context, id uuid.UUID) (*LotteryStrategy, error) {
	return c.Query().Where(lotterystrategy.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *LotteryStrategyClient) GetX(ctx context.Context, id uuid.UUID) *LotteryStrategy {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *LotteryStrategyClient) Hooks() []Hook {
	return c.hooks.LotteryStrategy
}

// Interceptors returns the client interceptors.
func (c *LotteryStrategyClient) Interceptors() []Interceptor {
	return c.inters.LotteryStrategy
}

func (c *LotteryStrategyClient) mutate(ctx context.Context, m *LotteryStrategyMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&LotteryStrategyCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&LotteryStrategyUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&LotteryStrategyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&LotteryStrategyDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown LotteryStrategy mutation op: %q", m.Op())
	}
}

// StrategyAwardClient is a client for the StrategyAward schema.
type StrategyAwardClient struct {
	config
}

// NewStrategyAwardClient returns a client for the StrategyAward from the given config.
func NewStrategyAwardClient(c config) *StrategyAwardClient {
	return &StrategyAwardClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `strategyaward.Hooks(f(g(h())))`.
func (c *StrategyAwardClient) Use(hooks ...Hook) {
	c.hooks.StrategyAward = append(c.hooks.StrategyAward, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `strategyaward.Intercept(f(g(h())))`.
func (c *StrategyAwardClient) Intercept(interceptors ...Interceptor) {
	c.inters.StrategyAward = append(c.inters.StrategyAward, interceptors...)
}

// Create returns a builder for creating a StrategyAward entity.
func (c *StrategyAwardClient) Create() *StrategyAwardCreate {
	mutation := newStrategyAwardMutation(c.config, OpCreate)
	return &StrategyAwardCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of StrategyAward entities.
func (c *StrategyAwardClient) CreateBulk(builders ...*StrategyAwardCreate) *StrategyAwardCreateBulk {
	return &StrategyAwardCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *StrategyAwardClient) MapCreateBulk(slice any, setFunc func(*StrategyAwardCreate, int)) *StrategyAwardCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &StrategyAwardCreateBulk{err: fmt.Errorf("calling to StrategyAwardClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*StrategyAwardCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &StrategyAwardCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for StrategyAward.
func (c *StrategyAwardClient) Update() *StrategyAwardUpdate {
	mutation := newStrategyAwardMutation(c.config, OpUpdate)
	return &StrategyAwardUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *StrategyAwardClient) UpdateOne(_m *StrategyAward) *StrategyAwardUpdateOne {
	mutation := newStrategyAwardMutation(c.config, OpUpdateOne, withStrategyAward(_m))
	return &StrategyAwardUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *StrategyAwardClient) UpdateOneID(id uuid.UUID) *StrategyAwardUpdateOne {
	mutation := newStrategyAwardMutation(c.config, OpUpdateOne, withStrategyAwardID(id))
	return &StrategyAwardUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for StrategyAward.
func (c *StrategyAwardClient) Delete() *StrategyAwardDelete {
	mutation := newStrategyAwardMutation(c.config, OpDelete)
	return &StrategyAwardDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *StrategyAwardClient) DeleteOne(_m *StrategyAward) *StrategyAwardDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *StrategyAwardClient) DeleteOneID(id uuid.UUID) *StrategyAwardDeleteOne {
	builder := c.Delete().Where(strategyaward.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &StrategyAwardDeleteOne{builder}
}

// Query returns a query builder for StrategyAward.
func (c *StrategyAwardClient) Query() *StrategyAwardQuery {
	return &StrategyAwardQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeStrategyAward},
		inters: c.Interceptors(),
	}
}

// Get returns a StrategyAward entity by its id.
func (c *StrategyAwardClient) Get(ctx context.Context, id uuid.UUID) (*StrategyAward, error) {
	return c.Query().Where(strategyaward.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *StrategyAwardClient) GetX(ctx context.Context, id uuid.UUID) *StrategyAward {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *StrategyAwardClient) Hooks() []Hook {
	return c.hooks.StrategyAward
}

// Interceptors returns the client interceptors.
func (c *StrategyAwardClient) Interceptors() []Interceptor {
	return c.inters.StrategyAward
}

func (c *StrategyAwardClient) mutate(ctx context.Context, m *StrategyAwardMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&StrategyAwardCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&StrategyAwardUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&StrategyAwardUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&StrategyAwardDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown StrategyAward mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		LotteryActivity, LotteryOrder, LotteryStrategy, StrategyAward []ent.Hook
	}
	inters struct {
		LotteryActivity, LotteryOrder, LotteryStrategy, StrategyAward []ent.Interceptor
	}
)
