// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/marketing-platform/internal/lottery/data/ent/lotteryactivity"
)

// LotteryActivityCreate is the builder for creating a LotteryActivity entity.
type LotteryActivityCreate struct {
	config
	mutation *LotteryActivityMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *LotteryActivityCreate) SetCreatedAt(v time.Time) *LotteryActivityCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LotteryActivityCreate) SetNillableCreatedAt(v *time.Time) *LotteryActivityCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LotteryActivityCreate) SetUpdatedAt(v time.Time) *LotteryActivityCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LotteryActivityCreate) SetNillableUpdatedAt(v *time.Time) *LotteryActivityCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetActivityID sets the "activity_id" field.
func (_c *LotteryActivityCreate) SetActivityID(v string) *LotteryActivityCreate {
	_c.mutation.SetActivityID(v)
	return _c
}

// SetActivityName sets the "activity_name" field.
func (_c *LotteryActivityCreate) SetActivityName(v string) *LotteryActivityCreate {
	_c.mutation.SetActivityName(v)
	return _c
}

// SetStrategyID sets the "strategy_id" field.
func (_c *LotteryActivityCreate) SetStrategyID(v string) *LotteryActivityCreate {
	_c.mutation.SetStrategyID(v)
	return _c
}

// SetActivityState sets the "activity_state" field.
func (_c *LotteryActivityCreate) SetActivityState(v int32) *LotteryActivityCreate {
	_c.mutation.SetActivityState(v)
	return _c
}

// SetNillableActivityState sets the "activity_state" field if the given value is not nil.
func (_c *LotteryActivityCreate) SetNillableActivityState(v *int32) *LotteryActivityCreate {
	if v != nil {
		_c.SetActivityState(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LotteryActivityCreate) SetID(v uuid.UUID) *LotteryActivityCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *LotteryActivityCreate) SetNillableID(v *uuid.UUID) *LotteryActivityCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the LotteryActivityMutation object of the builder.
func (_c *LotteryActivityCreate) Mutation() *LotteryActivityMutation {
	return _c.mutation
}

// Save creates the LotteryActivity in the database.
func (_c *LotteryActivityCreate) Save(ctx context.Context) (*LotteryActivity, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LotteryActivityCreate) SaveX(ctx context.Context) *LotteryActivity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryActivityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryActivityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LotteryActivityCreate) defaults() {
	if _, ok := _c.mutation.ActivityState(); !ok {
		v := lotteryactivity.DefaultActivityState
		_c.mutation.SetActivityState(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := lotteryactivity.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LotteryActivityCreate) check() error {
	if _, ok := _c.mutation.ActivityID(); !ok {
		return &ValidationError{Name: "activity_id", err: errors.New(`ent: missing required field "LotteryActivity.activity_id"`)}
	}
	if v, ok := _c.mutation.ActivityID(); ok {
		if err := lotteryactivity.ActivityIDValidator(v); err != nil {
			return &ValidationError{Name: "activity_id", err: fmt.Errorf(`ent: validator failed for field "LotteryActivity.activity_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActivityName(); !ok {
		return &ValidationError{Name: "activity_name", err: errors.New(`ent: missing required field "LotteryActivity.activity_name"`)}
	}
	if v, ok := _c.mutation.ActivityName(); ok {
		if err := lotteryactivity.ActivityNameValidator(v); err != nil {
			return &ValidationError{Name: "activity_name", err: fmt.Errorf(`ent: validator failed for field "LotteryActivity.activity_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StrategyID(); !ok {
		return &ValidationError{Name: "strategy_id", err: errors.New(`ent: missing required field "LotteryActivity.strategy_id"`)}
	}
	if v, ok := _c.mutation.StrategyID(); ok {
		if err := lotteryactivity.StrategyIDValidator(v); err != nil {
			return &ValidationError{Name: "strategy_id", err: fmt.Errorf(`ent: validator failed for field "LotteryActivity.strategy_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActivityState(); !ok {
		return &ValidationError{Name: "activity_state", err: errors.New(`ent: missing required field "LotteryActivity.activity_state"`)}
	}
	return nil
}

func (_c *LotteryActivityCreate) sqlSave(ctx context.Context) (*LotteryActivity, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LotteryActivityCreate) createSpec() (*LotteryActivity, *sqlgraph.CreateSpec) {
	var (
		_node = &LotteryActivity{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(lotteryactivity.Table, sqlgraph.NewFieldSpec(lotteryactivity.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(lotteryactivity.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(lotteryactivity.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.ActivityID(); ok {
		_spec.SetField(lotteryactivity.FieldActivityID, field.TypeString, value)
		_node.ActivityID = value
	}
	if value, ok := _c.mutation.ActivityName(); ok {
		_spec.SetField(lotteryactivity.FieldActivityName, field.TypeString, value)
		_node.ActivityName = value
	}
	if value, ok := _c.mutation.StrategyID(); ok {
		_spec.SetField(lotteryactivity.FieldStrategyID, field.TypeString, value)
		_node.StrategyID = value
	}
	if value, ok := _c.mutation.ActivityState(); ok {
		_spec.SetField(lotteryactivity.FieldActivityState, field.TypeInt32, value)
		_node.ActivityState = value
	}
	return _node, _spec
}

// LotteryActivityCreateBulk is the builder for creating many LotteryActivity entities in bulk.
type LotteryActivityCreateBulk struct {
	config
	err      error
	builders []*LotteryActivityCreate
}

// Save creates the LotteryActivity entities in the database.
func (_c *LotteryActivityCreateBulk) Save(ctx context.Context) ([]*LotteryActivity, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LotteryActivity, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LotteryActivityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LotteryActivityCreateBulk) SaveX(ctx context.Context) []*LotteryActivity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryActivityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryActivityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
