// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/marketing-platform/internal/lottery/data/ent/lotterystrategy"
)

// LotteryStrategyCreate is the builder for creating a LotteryStrategy entity.
type LotteryStrategyCreate struct {
	config
	mutation *LotteryStrategyMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *LotteryStrategyCreate) SetCreatedAt(v time.Time) *LotteryStrategyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LotteryStrategyCreate) SetNillableCreatedAt(v *time.Time) *LotteryStrategyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LotteryStrategyCreate) SetUpdatedAt(v time.Time) *LotteryStrategyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LotteryStrategyCreate) SetNillableUpdatedAt(v *time.Time) *LotteryStrategyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetStrategyID sets the "strategy_id" field.
func (_c *LotteryStrategyCreate) SetStrategyID(v string) *LotteryStrategyCreate {
	_c.mutation.SetStrategyID(v)
	return _c
}

// SetRuleModels sets the "rule_models" field.
func (_c *LotteryStrategyCreate) SetRuleModels(v string) *LotteryStrategyCreate {
	_c.mutation.SetRuleModels(v)
	return _c
}

// SetNillableRuleModels sets the "rule_models" field if the given value is not nil.
func (_c *LotteryStrategyCreate) SetNillableRuleModels(v *string) *LotteryStrategyCreate {
	if v != nil {
		_c.SetRuleModels(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LotteryStrategyCreate) SetID(v uuid.UUID) *LotteryStrategyCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *LotteryStrategyCreate) SetNillableID(v *uuid.UUID) *LotteryStrategyCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the LotteryStrategyMutation object of the builder.
func (_c *LotteryStrategyCreate) Mutation() *LotteryStrategyMutation {
	return _c.mutation
}

// Save creates the LotteryStrategy in the database.
func (_c *LotteryStrategyCreate) Save(ctx context.Context) (*LotteryStrategy, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LotteryStrategyCreate) SaveX(ctx context.Context) *LotteryStrategy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryStrategyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryStrategyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LotteryStrategyCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := lotterystrategy.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LotteryStrategyCreate) check() error {
	if _, ok := _c.mutation.StrategyID(); !ok {
		return &ValidationError{Name: "strategy_id", err: errors.New(`ent: missing required field "LotteryStrategy.strategy_id"`)}
	}
	if v, ok := _c.mutation.StrategyID(); ok {
		if err := lotterystrategy.StrategyIDValidator(v); err != nil {
			return &ValidationError{Name: "strategy_id", err: fmt.Errorf(`ent: validator failed for field "LotteryStrategy.strategy_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RuleModels(); ok {
		if err := lotterystrategy.RuleModelsValidator(v); err != nil {
			return &ValidationError{Name: "rule_models", err: fmt.Errorf(`ent: validator failed for field "LotteryStrategy.rule_models": %w`, err)}
		}
	}
	return nil
}

func (_c *LotteryStrategyCreate) sqlSave(ctx context.Context) (*LotteryStrategy, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LotteryStrategyCreate) createSpec() (*LotteryStrategy, *sqlgraph.CreateSpec) {
	var (
		_node = &LotteryStrategy{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(lotterystrategy.Table, sqlgraph.NewFieldSpec(lotterystrategy.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(lotterystrategy.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(lotterystrategy.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.StrategyID(); ok {
		_spec.SetField(lotterystrategy.FieldStrategyID, field.TypeString, value)
		_node.StrategyID = value
	}
	if value, ok := _c.mutation.RuleModels(); ok {
		_spec.SetField(lotterystrategy.FieldRuleModels, field.TypeString, value)
		_node.RuleModels = &value
	}
	return _node, _spec
}

// LotteryStrategyCreateBulk is the builder for creating many LotteryStrategy entities in bulk.
type LotteryStrategyCreateBulk struct {
	config
	err      error
	builders []*LotteryStrategyCreate
}

// Save creates the LotteryStrategy entities in the database.
func (_c *LotteryStrategyCreateBulk) Save(ctx context.Context) ([]*LotteryStrategy, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LotteryStrategy, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LotteryStrategyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LotteryStrategyCreateBulk) SaveX(ctx context.Context) []*LotteryStrategy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryStrategyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryStrategyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
