// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/marketing-platform/internal/lottery/data/ent/lotterystrategy"
	"github.com/marketing-platform/internal/lottery/data/ent/predicate"
)

// LotteryStrategyUpdate is the builder for updating LotteryStrategy entities.
type LotteryStrategyUpdate struct {
	config
	hooks    []Hook
	mutation *LotteryStrategyMutation
}

// Where appends a list predicates to the LotteryStrategyUpdate builder.
func (_u *LotteryStrategyUpdate) Where(ps ...predicate.LotteryStrategy) *LotteryStrategyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *LotteryStrategyUpdate) SetCreatedAt(v time.Time) *LotteryStrategyUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *LotteryStrategyUpdate) SetNillableCreatedAt(v *time.Time) *LotteryStrategyUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *LotteryStrategyUpdate) ClearCreatedAt() *LotteryStrategyUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LotteryStrategyUpdate) SetUpdatedAt(v time.Time) *LotteryStrategyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *LotteryStrategyUpdate) SetNillableUpdatedAt(v *time.Time) *LotteryStrategyUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *LotteryStrategyUpdate) ClearUpdatedAt() *LotteryStrategyUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetStrategyID sets the "strategy_id" field.
func (_u *LotteryStrategyUpdate) SetStrategyID(v string) *LotteryStrategyUpdate {
	_u.mutation.SetStrategyID(v)
	return _u
}

// SetNillableStrategyID sets the "strategy_id" field if the given value is not nil.
func (_u *LotteryStrategyUpdate) SetNillableStrategyID(v *string) *LotteryStrategyUpdate {
	if v != nil {
		_u.SetStrategyID(*v)
	}
	return _u
}

// SetRuleModels sets the "rule_models" field.
func (_u *LotteryStrategyUpdate) SetRuleModels(v string) *LotteryStrategyUpdate {
	_u.mutation.SetRuleModels(v)
	return _u
}

// SetNillableRuleModels sets the "rule_models" field if the given value is not nil.
func (_u *LotteryStrategyUpdate) SetNillableRuleModels(v *string) *LotteryStrategyUpdate {
	if v != nil {
		_u.SetRuleModels(*v)
	}
	return _u
}

// ClearRuleModels clears the value of the "rule_models" field.
func (_u *LotteryStrategyUpdate) ClearRuleModels() *LotteryStrategyUpdate {
	_u.mutation.ClearRuleModels()
	return _u
}

// Mutation returns the LotteryStrategyMutation object of the builder.
func (_u *LotteryStrategyUpdate) Mutation() *LotteryStrategyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LotteryStrategyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryStrategyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LotteryStrategyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryStrategyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LotteryStrategyUpdate) check() error {
	if v, ok := _u.mutation.StrategyID(); ok {
		if err := lotterystrategy.StrategyIDValidator(v); err != nil {
			return &ValidationError{Name: "strategy_id", err: fmt.Errorf(`ent: validator failed for field "LotteryStrategy.strategy_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RuleModels(); ok {
		if err := lotterystrategy.RuleModelsValidator(v); err != nil {
			return &ValidationError{Name: "rule_models", err: fmt.Errorf(`ent: validator failed for field "LotteryStrategy.rule_models": %w`, err)}
		}
	}
	return nil
}

func (_u *LotteryStrategyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lotterystrategy.Table, lotterystrategy.Columns, sqlgraph.NewFieldSpec(lotterystrategy.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(lotterystrategy.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(lotterystrategy.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(lotterystrategy.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(lotterystrategy.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.StrategyID(); ok {
		_spec.SetField(lotterystrategy.FieldStrategyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RuleModels(); ok {
		_spec.SetField(lotterystrategy.FieldRuleModels, field.TypeString, value)
	}
	if _u.mutation.RuleModelsCleared() {
		_spec.ClearField(lotterystrategy.FieldRuleModels, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotterystrategy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LotteryStrategyUpdateOne is the builder for updating a single LotteryStrategy entity.
type LotteryStrategyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LotteryStrategyMutation
}

// SetCreatedAt sets the "created_at" field.
func (_u *LotteryStrategyUpdateOne) SetCreatedAt(v time.Time) *LotteryStrategyUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *LotteryStrategyUpdateOne) SetNillableCreatedAt(v *time.Time) *LotteryStrategyUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *LotteryStrategyUpdateOne) ClearCreatedAt() *LotteryStrategyUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LotteryStrategyUpdateOne) SetUpdatedAt(v time.Time) *LotteryStrategyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *LotteryStrategyUpdateOne) SetNillableUpdatedAt(v *time.Time) *LotteryStrategyUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *LotteryStrategyUpdateOne) ClearUpdatedAt() *LotteryStrategyUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetStrategyID sets the "strategy_id" field.
func (_u *LotteryStrategyUpdateOne) SetStrategyID(v string) *LotteryStrategyUpdateOne {
	_u.mutation.SetStrategyID(v)
	return _u
}

// SetNillableStrategyID sets the "strategy_id" field if the given value is not nil.
func (_u *LotteryStrategyUpdateOne) SetNillableStrategyID(v *string) *LotteryStrategyUpdateOne {
	if v != nil {
		_u.SetStrategyID(*v)
	}
	return _u
}

// SetRuleModels sets the "rule_models" field.
func (_u *LotteryStrategyUpdateOne) SetRuleModels(v string) *LotteryStrategyUpdateOne {
	_u.mutation.SetRuleModels(v)
	return _u
}

// SetNillableRuleModels sets the "rule_models" field if the given value is not nil.
func (_u *LotteryStrategyUpdateOne) SetNillableRuleModels(v *string) *LotteryStrategyUpdateOne {
	if v != nil {
		_u.SetRuleModels(*v)
	}
	return _u
}

// ClearRuleModels clears the value of the "rule_models" field.
func (_u *LotteryStrategyUpdateOne) ClearRuleModels() *LotteryStrategyUpdateOne {
	_u.mutation.ClearRuleModels()
	return _u
}

// Mutation returns the LotteryStrategyMutation object of the builder.
func (_u *LotteryStrategyUpdateOne) Mutation() *LotteryStrategyMutation {
	return _u.mutation
}

// Where appends a list predicates to the LotteryStrategyUpdate builder.
func (_u *LotteryStrategyUpdateOne) Where(ps ...predicate.LotteryStrategy) *LotteryStrategyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LotteryStrategyUpdateOne) Select(field string, fields ...string) *LotteryStrategyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LotteryStrategy entity.
func (_u *LotteryStrategyUpdateOne) Save(ctx context.Context) (*LotteryStrategy, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryStrategyUpdateOne) SaveX(ctx context.Context) *LotteryStrategy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LotteryStrategyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryStrategyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LotteryStrategyUpdateOne) check() error {
	if v, ok := _u.mutation.StrategyID(); ok {
		if err := lotterystrategy.StrategyIDValidator(v); err != nil {
			return &ValidationError{Name: "strategy_id", err: fmt.Errorf(`ent: validator failed for field "LotteryStrategy.strategy_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RuleModels(); ok {
		if err := lotterystrategy.RuleModelsValidator(v); err != nil {
			return &ValidationError{Name: "rule_models", err: fmt.Errorf(`ent: validator failed for field "LotteryStrategy.rule_models": %w`, err)}
		}
	}
	return nil
}

func (_u *LotteryStrategyUpdateOne) sqlSave(ctx context.Context) (_node *LotteryStrategy, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lotterystrategy.Table, lotterystrategy.Columns, sqlgraph.NewFieldSpec(lotterystrategy.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LotteryStrategy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lotterystrategy.FieldID)
		for _, f := range fields {
			if !lotterystrategy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lotterystrategy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(lotterystrategy.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(lotterystrategy.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(lotterystrategy.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(lotterystrategy.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.StrategyID(); ok {
		_spec.SetField(lotterystrategy.FieldStrategyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RuleModels(); ok {
		_spec.SetField(lotterystrategy.FieldRuleModels, field.TypeString, value)
	}
	if _u.mutation.RuleModelsCleared() {
		_spec.ClearField(lotterystrategy.FieldRuleModels, field.TypeString)
	}
	_node = &LotteryStrategy{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotterystrategy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
