// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/marketing-platform/internal/lottery/data/ent/lotteryactivity"
	"github.com/marketing-platform/internal/lottery/data/ent/predicate"
)

// LotteryActivityDelete is the builder for deleting a LotteryActivity entity.
type LotteryActivityDelete struct {
	config
	hooks    []Hook
	mutation *LotteryActivityMutation
}

// Where appends a list predicates to the LotteryActivityDelete builder.
func (_d *LotteryActivityDelete) Where(ps ...predicate.LotteryActivity) *LotteryActivityDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *LotteryActivityDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LotteryActivityDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *LotteryActivityDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(lotteryactivity.Table, sqlgraph.NewFieldSpec(lotteryactivity.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// LotteryActivityDeleteOne is the builder for deleting a single LotteryActivity entity.
type LotteryActivityDeleteOne struct {
	_d *LotteryActivityDelete
}

// Where appends a list predicates to the LotteryActivityDelete builder.
func (_d *LotteryActivityDeleteOne) Where(ps ...predicate.LotteryActivity) *LotteryActivityDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *LotteryActivityDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{lotteryactivity.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LotteryActivityDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
