// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/marketing-platform/internal/lottery/data/ent/lotterystrategy"
)

// LotteryStrategy is the model entity for the LotteryStrategy schema.
type LotteryStrategy struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// StrategyID holds the value of the "strategy_id" field.
	StrategyID string `json:"strategy_id,omitempty"`
	// RuleModels holds the value of the "rule_models" field.
	RuleModels   *string `json:"rule_models,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LotteryStrategy) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case lotterystrategy.FieldStrategyID, lotterystrategy.FieldRuleModels:
			values[i] = new(sql.NullString)
		case lotterystrategy.FieldCreatedAt, lotterystrategy.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case lotterystrategy.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LotteryStrategy fields.
func (_m *LotteryStrategy) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case lotterystrategy.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case lotterystrategy.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case lotterystrategy.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case lotterystrategy.FieldStrategyID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field strategy_id", values[i])
			} else if value.Valid {
				_m.StrategyID = value.String
			}
		case lotterystrategy.FieldRuleModels:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rule_models", values[i])
			} else if value.Valid {
				_m.RuleModels = new(string)
				*_m.RuleModels = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LotteryStrategy.
// This includes values selected through modifiers, order, etc.
func (_m *LotteryStrategy) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this LotteryStrategy.
// Note that you need to call LotteryStrategy.Unwrap() before calling this method if this LotteryStrategy
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LotteryStrategy) Update() *LotteryStrategyUpdateOne {
	return NewLotteryStrategyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LotteryStrategy entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LotteryStrategy) Unwrap() *LotteryStrategy {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LotteryStrategy is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LotteryStrategy) String() string {
	var builder strings.Builder
	builder.WriteString("LotteryStrategy(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("strategy_id=")
	builder.WriteString(_m.StrategyID)
	builder.WriteString(", ")
	if v := _m.RuleModels; v != nil {
		builder.WriteString("rule_models=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// LotteryStrategies is a parsable slice of LotteryStrategy.
type LotteryStrategies []*LotteryStrategy
