// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/google/uuid"
	"github.com/marketing-platform/internal/lottery/data/ent/lotteryactivity"
	"github.com/marketing-platform/internal/lottery/data/ent/lotteryorder"
	"github.com/marketing-platform/internal/lottery/data/ent/lotterystrategy"
	"github.com/marketing-platform/internal/lottery/data/ent/schema"
	"github.com/marketing-platform/internal/lottery/data/ent/strategyaward"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	lotteryactivityFields := schema.LotteryActivity{}.Fields()
	_ = lotteryactivityFields
	// lotteryactivityDescActivityID is the schema descriptor for activity_id field.
	lotteryactivityDescActivityID := lotteryactivityFields[1].Descriptor()
	// lotteryactivity.ActivityIDValidator is a validator for the "activity_id" field. It is called by the builders before save.
	lotteryactivity.ActivityIDValidator = lotteryactivityDescActivityID.Validators[0].(func(string) error)
	// lotteryactivityDescActivityName is the schema descriptor for activity_name field.
	lotteryactivityDescActivityName := lotteryactivityFields[2].Descriptor()
	// lotteryactivity.ActivityNameValidator is a validator for the "activity_name" field. It is called by the builders before save.
	lotteryactivity.ActivityNameValidator = lotteryactivityDescActivityName.Validators[0].(func(string) error)
	// lotteryactivityDescStrategyID is the schema descriptor for strategy_id field.
	lotteryactivityDescStrategyID := lotteryactivityFields[3].Descriptor()
	// lotteryactivity.StrategyIDValidator is a validator for the "strategy_id" field. It is called by the builders before save.
	lotteryactivity.StrategyIDValidator = lotteryactivityDescStrategyID.Validators[0].(func(string) error)
	// lotteryactivityDescActivityState is the schema descriptor for activity_state field.
	lotteryactivityDescActivityState := lotteryactivityFields[4].Descriptor()
	// lotteryactivity.DefaultActivityState holds the default value on creation for the activity_state field.
	lotteryactivity.DefaultActivityState = lotteryactivityDescActivityState.Default.(int32)
	// lotteryactivityDescID is the schema descriptor for id field.
	lotteryactivityDescID := lotteryactivityFields[0].Descriptor()
	// lotteryactivity.DefaultID holds the default value on creation for the id field.
	lotteryactivity.DefaultID = lotteryactivityDescID.Default.(func() uuid.UUID)
	lotteryorderFields := schema.LotteryOrder{}.Fields()
	_ = lotteryorderFields
	// lotteryorderDescOrderID is the schema descriptor for order_id field.
	lotteryorderDescOrderID := lotteryorderFields[1].Descriptor()
	// lotteryorder.OrderIDValidator is a validator for the "order_id" field. It is called by the builders before save.
	lotteryorder.OrderIDValidator = lotteryorderDescOrderID.Validators[0].(func(string) error)
	// lotteryorderDescActivityID is the schema descriptor for activity_id field.
	lotteryorderDescActivityID := lotteryorderFields[2].Descriptor()
	// lotteryorder.ActivityIDValidator is a validator for the "activity_id" field. It is called by the builders before save.
	lotteryorder.ActivityIDValidator = lotteryorderDescActivityID.Validators[0].(func(string) error)
	// lotteryorderDescAwardID is the schema descriptor for award_id field.
	lotteryorderDescAwardID := lotteryorderFields[4].Descriptor()
	// lotteryorder.AwardIDValidator is a validator for the "award_id" field. It is called by the builders before save.
	lotteryorder.AwardIDValidator = lotteryorderDescAwardID.Validators[0].(func(string) error)
	// lotteryorderDescAwardState is the schema descriptor for award_state field.
	lotteryorderDescAwardState := lotteryorderFields[5].Descriptor()
	// lotteryorder.DefaultAwardState holds the default value on creation for the award_state field.
	lotteryorder.DefaultAwardState = lotteryorderDescAwardState.Default.(int32)
	// lotteryorderDescID is the schema descriptor for id field.
	lotteryorderDescID := lotteryorderFields[0].Descriptor()
	// lotteryorder.DefaultID holds the default value on creation for the id field.
	lotteryorder.DefaultID = lotteryorderDescID.Default.(func() uuid.UUID)
	lotterystrategyFields := schema.LotteryStrategy{}.Fields()
	_ = lotterystrategyFields
	// lotterystrategyDescStrategyID is the schema descriptor for strategy_id field.
	lotterystrategyDescStrategyID := lotterystrategyFields[1].Descriptor()
	// lotterystrategy.StrategyIDValidator is a validator for the "strategy_id" field. It is called by the builders before save.
	lotterystrategy.StrategyIDValidator = lotterystrategyDescStrategyID.Validators[0].(func(string) error)
	// lotterystrategyDescRuleModels is the schema descriptor for rule_models field.
	lotterystrategyDescRuleModels := lotterystrategyFields[2].Descriptor()
	// lotterystrategy.RuleModelsValidator is a validator for the "rule_models" field. It is called by the builders before save.
	lotterystrategy.RuleModelsValidator = lotterystrategyDescRuleModels.Validators[0].(func(string) error)
	// lotterystrategyDescID is the schema descriptor for id field.
	lotterystrategyDescID := lotterystrategyFields[0].Descriptor()
	// lotterystrategy.DefaultID holds the default value on creation for the id field.
	lotterystrategy.DefaultID = lotterystrategyDescID.Default.(func() uuid.UUID)
	strategyawardFields := schema.StrategyAward{}.Fields()
	_ = strategyawardFields
	// strategyawardDescStrategyID is the schema descriptor for strategy_id field.
	strategyawardDescStrategyID := strategyawardFields[1].Descriptor()
	// strategyaward.StrategyIDValidator is a validator for the "strategy_id" field. It is called by the builders before save.
	strategyaward.StrategyIDValidator = strategyawardDescStrategyID.Validators[0].(func(string) error)
	// strategyawardDescAwardID is the schema descriptor for award_id field.
	strategyawardDescAwardID := strategyawardFields[2].Descriptor()
	// strategyaward.AwardIDValidator is a validator for the "award_id" field. It is called by the builders before save.
	strategyaward.AwardIDValidator = strategyawardDescAwardID.Validators[0].(func(string) error)
	// strategyawardDescAwardName is the schema descriptor for award_name field.
	strategyawardDescAwardName := strategyawardFields[3].Descriptor()
	// strategyaward.AwardNameValidator is a validator for the "award_name" field. It is called by the builders before save.
	strategyaward.AwardNameValidator = strategyawardDescAwardName.Validators[0].(func(string) error)
	// strategyawardDescAwardCount is the schema descriptor for award_count field.
	strategyawardDescAwardCount := strategyawardFields[5].Descriptor()
	// strategyaward.DefaultAwardCount holds the default value on creation for the award_count field.
	strategyaward.DefaultAwardCount = strategyawardDescAwardCount.Default.(int32)
	// strategyawardDescRuleModels is the schema descriptor for rule_models field.
	strategyawardDescRuleModels := strategyawardFields[6].Descriptor()
	// strategyaward.RuleModelsValidator is a validator for the "rule_models" field. It is called by the builders before save.
	strategyaward.RuleModelsValidator = strategyawardDescRuleModels.Validators[0].(func(string) error)
	// strategyawardDescID is the schema descriptor for id field.
	strategyawardDescID := strategyawardFields[0].Descriptor()
	// strategyaward.DefaultID holds the default value on creation for the id field.
	strategyaward.DefaultID = strategyawardDescID.Default.(func() uuid.UUID)
}
