// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/marketing-platform/internal/lottery/data/ent/strategyaward"
)

// StrategyAward is the model entity for the StrategyAward schema.
type StrategyAward struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// StrategyID holds the value of the "strategy_id" field.
	StrategyID string `json:"strategy_id,omitempty"`
	// AwardID holds the value of the "award_id" field.
	AwardID string `json:"award_id,omitempty"`
	// AwardName holds the value of the "award_name" field.
	AwardName string `json:"award_name,omitempty"`
	// AwardRate holds the value of the "award_rate" field.
	AwardRate float64 `json:"award_rate,omitempty"`
	// AwardCount holds the value of the "award_count" field.
	AwardCount int32 `json:"award_count,omitempty"`
	// RuleModels holds the value of the "rule_models" field.
	RuleModels   *string `json:"rule_models,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*StrategyAward) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case strategyaward.FieldAwardRate:
			values[i] = new(sql.NullFloat64)
		case strategyaward.FieldAwardCount:
			values[i] = new(sql.NullInt64)
		case strategyaward.FieldStrategyID, strategyaward.FieldAwardID, strategyaward.FieldAwardName, strategyaward.FieldRuleModels:
			values[i] = new(sql.NullString)
		case strategyaward.FieldCreatedAt, strategyaward.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case strategyaward.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the StrategyAward fields.
func (_m *StrategyAward) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case strategyaward.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case strategyaward.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case strategyaward.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case strategyaward.FieldStrategyID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field strategy_id", values[i])
			} else if value.Valid {
				_m.StrategyID = value.String
			}
		case strategyaward.FieldAwardID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field award_id", values[i])
			} else if value.Valid {
				_m.AwardID = value.String
			}
		case strategyaward.FieldAwardName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field award_name", values[i])
			} else if value.Valid {
				_m.AwardName = value.String
			}
		case strategyaward.FieldAwardRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field award_rate", values[i])
			} else if value.Valid {
				_m.AwardRate = value.Float64
			}
		case strategyaward.FieldAwardCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field award_count", values[i])
			} else if value.Valid {
				_m.AwardCount = int32(value.Int64)
			}
		case strategyaward.FieldRuleModels:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rule_models", values[i])
			} else if value.Valid {
				_m.RuleModels = new(string)
				*_m.RuleModels = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the StrategyAward.
// This includes values selected through modifiers, order, etc.
func (_m *StrategyAward) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this StrategyAward.
// Note that you need to call StrategyAward.Unwrap() before calling this method if this StrategyAward
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *StrategyAward) Update() *StrategyAwardUpdateOne {
	return NewStrategyAwardClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the StrategyAward entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *StrategyAward) Unwrap() *StrategyAward {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: StrategyAward is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *StrategyAward) String() string {
	var builder strings.Builder
	builder.WriteString("StrategyAward(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("strategy_id=")
	builder.WriteString(_m.StrategyID)
	builder.WriteString(", ")
	builder.WriteString("award_id=")
	builder.WriteString(_m.AwardID)
	builder.WriteString(", ")
	builder.WriteString("award_name=")
	builder.WriteString(_m.AwardName)
	builder.WriteString(", ")
	builder.WriteString("award_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.AwardRate))
	builder.WriteString(", ")
	builder.WriteString("award_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.AwardCount))
	builder.WriteString(", ")
	if v := _m.RuleModels; v != nil {
		builder.WriteString("rule_models=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// StrategyAwards is a parsable slice of StrategyAward.
type StrategyAwards []*StrategyAward
