// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/marketing-platform/internal/lottery/data/ent/strategyaward"
)

// StrategyAwardCreate is the builder for creating a StrategyAward entity.
type StrategyAwardCreate struct {
	config
	mutation *StrategyAwardMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *StrategyAwardCreate) SetCreatedAt(v time.Time) *StrategyAwardCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *StrategyAwardCreate) SetNillableCreatedAt(v *time.Time) *StrategyAwardCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *StrategyAwardCreate) SetUpdatedAt(v time.Time) *StrategyAwardCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *StrategyAwardCreate) SetNillableUpdatedAt(v *time.Time) *StrategyAwardCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetStrategyID sets the "strategy_id" field.
func (_c *StrategyAwardCreate) SetStrategyID(v string) *StrategyAwardCreate {
	_c.mutation.SetStrategyID(v)
	return _c
}

// SetAwardID sets the "award_id" field.
func (_c *StrategyAwardCreate) SetAwardID(v string) *StrategyAwardCreate {
	_c.mutation.SetAwardID(v)
	return _c
}

// SetAwardName sets the "award_name" field.
func (_c *StrategyAwardCreate) SetAwardName(v string) *StrategyAwardCreate {
	_c.mutation.SetAwardName(v)
	return _c
}

// SetAwardRate sets the "award_rate" field.
func (_c *StrategyAwardCreate) SetAwardRate(v float64) *StrategyAwardCreate {
	_c.mutation.SetAwardRate(v)
	return _c
}

// SetAwardCount sets the "award_count" field.
func (_c *StrategyAwardCreate) SetAwardCount(v int32) *StrategyAwardCreate {
	_c.mutation.SetAwardCount(v)
	return _c
}

// SetNillableAwardCount sets the "award_count" field if the given value is not nil.
func (_c *StrategyAwardCreate) SetNillableAwardCount(v *int32) *StrategyAwardCreate {
	if v != nil {
		_c.SetAwardCount(*v)
	}
	return _c
}

// SetRuleModels sets the "rule_models" field.
func (_c *StrategyAwardCreate) SetRuleModels(v string) *StrategyAwardCreate {
	_c.mutation.SetRuleModels(v)
	return _c
}

// SetNillableRuleModels sets the "rule_models" field if the given value is not nil.
func (_c *StrategyAwardCreate) SetNillableRuleModels(v *string) *StrategyAwardCreate {
	if v != nil {
		_c.SetRuleModels(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *StrategyAwardCreate) SetID(v uuid.UUID) *StrategyAwardCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *StrategyAwardCreate) SetNillableID(v *uuid.UUID) *StrategyAwardCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the StrategyAwardMutation object of the builder.
func (_c *StrategyAwardCreate) Mutation() *StrategyAwardMutation {
	return _c.mutation
}

// Save creates the StrategyAward in the database.
func (_c *StrategyAwardCreate) Save(ctx context.Context) (*StrategyAward, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StrategyAwardCreate) SaveX(ctx context.Context) *StrategyAward {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StrategyAwardCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StrategyAwardCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StrategyAwardCreate) defaults() {
	if _, ok := _c.mutation.AwardCount(); !ok {
		v := strategyaward.DefaultAwardCount
		_c.mutation.SetAwardCount(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := strategyaward.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StrategyAwardCreate) check() error {
	if _, ok := _c.mutation.StrategyID(); !ok {
		return &ValidationError{Name: "strategy_id", err: errors.New(`ent: missing required field "StrategyAward.strategy_id"`)}
	}
	if v, ok := _c.mutation.StrategyID(); ok {
		if err := strategyaward.StrategyIDValidator(v); err != nil {
			return &ValidationError{Name: "strategy_id", err: fmt.Errorf(`ent: validator failed for field "StrategyAward.strategy_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AwardID(); !ok {
		return &ValidationError{Name: "award_id", err: errors.New(`ent: missing required field "StrategyAward.award_id"`)}
	}
	if v, ok := _c.mutation.AwardID(); ok {
		if err := strategyaward.AwardIDValidator(v); err != nil {
			return &ValidationError{Name: "award_id", err: fmt.Errorf(`ent: validator failed for field "StrategyAward.award_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AwardName(); !ok {
		return &ValidationError{Name: "award_name", err: errors.New(`ent: missing required field "StrategyAward.award_name"`)}
	}
	if v, ok := _c.mutation.AwardName(); ok {
		if err := strategyaward.AwardNameValidator(v); err != nil {
			return &ValidationError{Name: "award_name", err: fmt.Errorf(`ent: validator failed for field "StrategyAward.award_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AwardRate(); !ok {
		return &ValidationError{Name: "award_rate", err: errors.New(`ent: missing required field "StrategyAward.award_rate"`)}
	}
	if _, ok := _c.mutation.AwardCount(); !ok {
		return &ValidationError{Name: "award_count", err: errors.New(`ent: missing required field "StrategyAward.award_count"`)}
	}
	if v, ok := _c.mutation.RuleModels(); ok {
		if err := strategyaward.RuleModelsValidator(v); err != nil {
			return &ValidationError{Name: "rule_models", err: fmt.Errorf(`ent: validator failed for field "StrategyAward.rule_models": %w`, err)}
		}
	}
	return nil
}

func (_c *StrategyAwardCreate) sqlSave(ctx context.Context) (*StrategyAward, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StrategyAwardCreate) createSpec() (*StrategyAward, *sqlgraph.CreateSpec) {
	var (
		_node = &StrategyAward{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(strategyaward.Table, sqlgraph.NewFieldSpec(strategyaward.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(strategyaward.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(strategyaward.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.StrategyID(); ok {
		_spec.SetField(strategyaward.FieldStrategyID, field.TypeString, value)
		_node.StrategyID = value
	}
	if value, ok := _c.mutation.AwardID(); ok {
		_spec.SetField(strategyaward.FieldAwardID, field.TypeString, value)
		_node.AwardID = value
	}
	if value, ok := _c.mutation.AwardName(); ok {
		_spec.SetField(strategyaward.FieldAwardName, field.TypeString, value)
		_node.AwardName = value
	}
	if value, ok := _c.mutation.AwardRate(); ok {
		_spec.SetField(strategyaward.FieldAwardRate, field.TypeFloat64, value)
		_node.AwardRate = value
	}
	if value, ok := _c.mutation.AwardCount(); ok {
		_spec.SetField(strategyaward.FieldAwardCount, field.TypeInt32, value)
		_node.AwardCount = value
	}
	if value, ok := _c.mutation.RuleModels(); ok {
		_spec.SetField(strategyaward.FieldRuleModels, field.TypeString, value)
		_node.RuleModels = &value
	}
	return _node, _spec
}

// StrategyAwardCreateBulk is the builder for creating many StrategyAward entities in bulk.
type StrategyAwardCreateBulk struct {
	config
	err      error
	builders []*StrategyAwardCreate
}

// Save creates the StrategyAward entities in the database.
func (_c *StrategyAwardCreateBulk) Save(ctx context.Context) ([]*StrategyAward, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*StrategyAward, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StrategyAwardMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StrategyAwardCreateBulk) SaveX(ctx context.Context) []*StrategyAward {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StrategyAwardCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StrategyAwardCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
