// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/marketing-platform/internal/stock/data/ent/stockitem"
)

// StockItem is the model entity for the StockItem schema.
type StockItem struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// StockKey holds the value of the "stock_key" field.
	StockKey string `json:"stock_key,omitempty"`
	// StockName holds the value of the "stock_name" field.
	StockName string `json:"stock_name,omitempty"`
	// StockType holds the value of the "stock_type" field.
	StockType string `json:"stock_type,omitempty"`
	// Stock holds the value of the "stock" field.
	Stock int32 `json:"stock,omitempty"`
	// Total holds the value of the "total" field.
	Total        int32 `json:"total,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*StockItem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case stockitem.FieldStock, stockitem.FieldTotal:
			values[i] = new(sql.NullInt64)
		case stockitem.FieldStockKey, stockitem.FieldStockName, stockitem.FieldStockType:
			values[i] = new(sql.NullString)
		case stockitem.FieldCreatedAt, stockitem.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case stockitem.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the StockItem fields.
func (_m *StockItem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case stockitem.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case stockitem.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case stockitem.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case stockitem.FieldStockKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stock_key", values[i])
			} else if value.Valid {
				_m.StockKey = value.String
			}
		case stockitem.FieldStockName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stock_name", values[i])
			} else if value.Valid {
				_m.StockName = value.String
			}
		case stockitem.FieldStockType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stock_type", values[i])
			} else if value.Valid {
				_m.StockType = value.String
			}
		case stockitem.FieldStock:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field stock", values[i])
			} else if value.Valid {
				_m.Stock = int32(value.Int64)
			}
		case stockitem.FieldTotal:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total", values[i])
			} else if value.Valid {
				_m.Total = int32(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the StockItem.
// This includes values selected through modifiers, order, etc.
func (_m *StockItem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this StockItem.
// Note that you need to call StockItem.Unwrap() before calling this method if this StockItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *StockItem) Update() *StockItemUpdateOne {
	return NewStockItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the StockItem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *StockItem) Unwrap() *StockItem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: StockItem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *StockItem) String() string {
	var builder strings.Builder
	builder.WriteString("StockItem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("stock_key=")
	builder.WriteString(_m.StockKey)
	builder.WriteString(", ")
	builder.WriteString("stock_name=")
	builder.WriteString(_m.StockName)
	builder.WriteString(", ")
	builder.WriteString("stock_type=")
	builder.WriteString(_m.StockType)
	builder.WriteString(", ")
	builder.WriteString("stock=")
	builder.WriteString(fmt.Sprintf("%v", _m.Stock))
	builder.WriteString(", ")
	builder.WriteString("total=")
	builder.WriteString(fmt.Sprintf("%v", _m.Total))
	builder.WriteByte(')')
	return builder.String()
}

// StockItems is a parsable slice of StockItem.
type StockItems []*StockItem
